// Generates one `class XIcon extends Svg` per fixed SVG in ./icons/ (see
// convert.ts). Forked from pmndrs/uikit @ 0d4d887
// (packages/icons/lucide/core/generate.ts) — retargeted from `@pmndrs/uikit`
// to `@three-flatland/uikit` and from the split core/react layout to this
// single package's `src/` (vanilla) + `src/react/` (React wrappers, see
// generate-react.ts) layout.
import { readdir, readFile, writeFile } from 'fs/promises'

const baseDir = './icons/'
const outDir = './src/'

async function main() {
  const icons = await readdir(baseDir)
  const names: string[] = []
  for (const icon of icons) {
    if (icon === '.gitkeep') {
      continue
    }
    const name = getName(icon)
    names.push(name)
    const iconName = icon.slice(0, -4)
    const raw = await readFile(`${baseDir}${icon}`)
    const svg = raw.toString()
    const code = `
      /* eslint-disable -- generated by scripts/generate.ts from lucide-static; do not hand-edit */
      import { Svg } from '@three-flatland/uikit'
      import type { RenderContext, SvgProperties, SvgOutProperties, InProperties, WithSignal } from '@three-flatland/uikit'
      const content = \`${svg}\`;
      export class ${name}Icon<OutProperties extends SvgOutProperties = SvgOutProperties> extends Svg<OutProperties> {
        constructor(
          inputProperties?: InProperties<OutProperties>,
          initialClasses?: Array<SvgProperties | string>,
          config?: {
            renderContext?: RenderContext
            defaultOverrides?: InProperties<OutProperties>
            defaults?: WithSignal<OutProperties>
          },
        ) {
          super(inputProperties, initialClasses, {
            ...config,
            defaultOverrides: {
              icon: '${iconName}',
              content,
              width: 24,
              height: 24,
              ...config?.defaultOverrides
            } as InProperties<OutProperties>,
          })
        }
      }
      export const ${name} = ${name}Icon
    `
    await writeFile(`${outDir}${name}.ts`, code)
  }
  await writeFile(
    `${outDir}index.ts`,
    names.map((name) => `export * from './${name}.js';`).join('\n') + '\n'
  )
}

function getName(file: string): string {
  const name = file.slice(0, -4)
  return name[0]!.toUpperCase() + name.slice(1).replace(/-./g, (x) => x[1]!.toUpperCase())
}

main()
