//! Golden interop fixture: `../fixtures/golden/golden.ts` and
//! `../fixtures/golden/golden.findings.json` are the same two files the TS
//! client's `src/goldenFixture.test.ts` loads. Both sides assert their
//! `document/parse` output against the identical expected JSON — this is
//! the one test that actually catches a Rust/TypeScript protocol drift,
//! rather than each side merely being internally self-consistent.
//!
//! The golden JSON was generated by driving this exact binary through the
//! real wire protocol (not by calling `find_zzfx_calls` directly) with the
//! synthetic URI `file:///golden.ts` — see the header comment in
//! `golden.findings.json`'s sibling `golden.ts` and
//! `tools/codelens-service/CLAUDE.md` for how to regenerate it if the
//! fixture or the extraction logic changes.

use std::io::{BufReader, Read, Write};
use std::process::{Command, Stdio};

use codelens_service::model::Finding;
use serde_json::{Value, json};

const GOLDEN_URI: &str = "file:///golden.ts";

fn fixture_path(name: &str) -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../fixtures/golden")
        .join(name)
}

fn write_frame<W: Write>(writer: &mut W, body: &[u8]) {
    write!(writer, "Content-Length: {}\r\n\r\n", body.len()).unwrap();
    writer.write_all(body).unwrap();
    writer.flush().unwrap();
}

fn read_frame<R: Read>(reader: &mut R) -> Vec<u8> {
    let mut content_length = None;
    loop {
        let mut line_bytes = Vec::new();
        let mut byte = [0u8; 1];
        loop {
            reader.read_exact(&mut byte).unwrap();
            line_bytes.push(byte[0]);
            if byte[0] == b'\n' {
                break;
            }
        }
        let line = String::from_utf8(line_bytes).unwrap();
        let trimmed = line.trim_end_matches(['\r', '\n']);
        if trimmed.is_empty() {
            break;
        }
        if let Some((name, value)) = trimmed.split_once(':')
            && name.eq_ignore_ascii_case("Content-Length")
        {
            content_length = Some(value.trim().parse::<usize>().unwrap());
        }
    }
    let len = content_length.expect("response must have Content-Length");
    let mut buf = vec![0u8; len];
    reader.read_exact(&mut buf).unwrap();
    buf
}

#[test]
fn document_parse_matches_the_golden_fixture_exactly() {
    let golden_ts = std::fs::read_to_string(fixture_path("golden.ts")).unwrap();
    // Deserialize into the typed Finding struct, not a generic Value:
    // serde_json::Value's equality is JSON-text-format-sensitive (a
    // Number parsed from "1.0" does not equal one parsed from "1", even
    // though both are the same f64) — comparing typed f64 fields instead
    // makes this a genuine semantic-equality check, immune to incidental
    // number formatting differences introduced by however the golden file
    // was generated or hand-edited.
    let golden_findings: Vec<Finding> = serde_json::from_str(
        &std::fs::read_to_string(fixture_path("golden.findings.json")).unwrap(),
    )
    .unwrap();

    let exe = env!("CARGO_BIN_EXE_codelens-service");
    let mut child = Command::new(exe)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::inherit())
        .spawn()
        .expect("failed to spawn codelens-service");
    let mut stdin = child.stdin.take().unwrap();
    let mut stdout = BufReader::new(child.stdout.take().unwrap());

    let dir = tempfile::tempdir().unwrap();
    write_frame(
        &mut stdin,
        &serde_json::to_vec(&json!({
            "jsonrpc": "2.0",
            "id": 1,
            "method": "initialize",
            "params": {
                "workspaceRoot": dir.path().to_string_lossy(),
                "storageUri": dir.path().join("storage").to_string_lossy(),
            }
        }))
        .unwrap(),
    );
    let init_response = read_frame(&mut stdout);
    let init_response: Value = serde_json::from_slice(&init_response).unwrap();
    // Raw-JSON check, not through the typed InitializeResult: serde
    // deserializes a missing key and an explicit `null` into the exact
    // same `Option::None`, so a typed comparison can't tell "degraded key
    // omitted" (the actual, intended wire contract) apart from a
    // regression that starts sending `"degraded": null`. `.get()` on a
    // serde_json::Value::Object returns None only when the key is truly
    // absent — Some(&Value::Null) if it's present-but-null.
    assert!(
        init_response["result"].get("degraded").is_none(),
        "initialize's response must OMIT the degraded key when not degraded (not send \"degraded\": null); got {init_response}"
    );

    write_frame(
        &mut stdin,
        &serde_json::to_vec(&json!({
            "jsonrpc": "2.0",
            "id": 2,
            "method": "document/parse",
            "params": { "uri": GOLDEN_URI, "text": golden_ts },
        }))
        .unwrap(),
    );
    let response = read_frame(&mut stdout);
    let response: Value = serde_json::from_slice(&response).unwrap();
    let actual_findings: Vec<Finding> =
        serde_json::from_value(response["result"]["findings"].clone()).unwrap();

    assert_eq!(
        actual_findings, golden_findings,
        "document/parse output for the golden fixture drifted from golden.findings.json.\n\
         If this is an intentional protocol/extraction change, regenerate the golden file \
         (see tools/codelens-service/CLAUDE.md) and update BOTH this test and \
         src/goldenFixture.test.ts's expectations together."
    );

    // Same "typed comparison can't see this" gap as the degraded check
    // above: golden.ts's `zzfx(1, 0.1, 440)` call (all-literal args, no
    // var reference) must have its `varRef` key OMITTED from the wire
    // JSON, not present as `null` — verified directly on the raw
    // response, not via the typed Vec<Finding> comparison just above.
    // Found by params rather than a hardcoded index, so this doesn't
    // silently start checking the wrong finding if golden.ts gains or
    // loses an earlier entry.
    let raw_findings = response["result"]["findings"].as_array().unwrap();
    let literal_call = raw_findings
        .iter()
        .find(|f| f["payload"]["params"] == json!([1.0, 0.1, 440.0]))
        .expect("golden.ts must still contain the zzfx(1, 0.1, 440) literal call");
    assert!(
        literal_call["payload"].get("varRef").is_none(),
        "a literal-args call's payload must OMIT the varRef key, not send \"varRef\": null; got {literal_call}"
    );

    // The specific regression this unit exists to prevent: a type-annotated
    // declarator's defRange must land INSIDE the initializer, past the `=`
    // — not at the declarator's start (the name). golden.ts's
    // `explosionPreset` declaration is `const explosionPreset: number[] =
    // [0.6, ...]`; `=` sits at byte/character 32 on that line, so a
    // defRange starting anywhere at or before 32 would mean the old,
    // whole-declarator bug is back.
    let explosion_finding = actual_findings
        .iter()
        .find(|f| {
            f.as_zzfx_call()
                .and_then(|p| p.var_ref.as_ref())
                .is_some_and(|v| v.name == "explosionPreset")
        })
        .expect("golden.ts must still declare and reference explosionPreset");
    let def_range = explosion_finding
        .as_zzfx_call()
        .unwrap()
        .var_ref
        .as_ref()
        .unwrap()
        .def_range
        .expect("explosionPreset has an initializer; defRange must be Some");
    assert!(
        def_range.start.character > 32,
        "defRange must start past the '=' (character 32 on this fixture's declarator line), \
         got character {} — this is exactly the whole-declarator regression this test guards against",
        def_range.start.character
    );

    // zzfxm.song: the var-form entry (laserSong) must resolve a varRef whose
    // defRange lands inside the initializer, same "past the `=`" contract as
    // zzfx's varRef.defRange — it's the identical resolve_var_ref path.
    let laser_song = actual_findings
        .iter()
        .find(|f| {
            f.as_zzfxm_song()
                .and_then(|p| p.var_ref.as_ref())
                .is_some_and(|v| v.name == "laserSong")
        })
        .expect("golden.ts must still declare and reference laserSong via zzfxm");
    let song_def_range = laser_song
        .as_zzfxm_song()
        .unwrap()
        .var_ref
        .as_ref()
        .unwrap()
        .def_range
        .expect("laserSong has an initializer; defRange must be Some");
    assert!(
        song_def_range.start.character > 16,
        "laserSong's defRange must start past the '=' (character 16 on \
         \"const laserSong = ...\"'s declarator line), got character {}",
        song_def_range.start.character
    );

    // zzfxm.song literal form (playInlineSong) must have NO varRef at all —
    // raw JSON check, not the typed comparison, for the same
    // present-vs-omitted reason as the literal zzfx call check above.
    let inline_song = raw_findings
        .iter()
        .find(|f| {
            f["kind"] == "zzfxm.song"
                && f["payload"]["argRange"]["start"]["character"] == 8
                && f["range"]["start"]["line"] == 45
        })
        .expect("golden.ts must still contain the inline-literal zzfxm song call");
    assert!(
        inline_song["payload"].get("varRef").is_none(),
        "a literal-array zzfxm call's payload must OMIT the varRef key; got {inline_song}"
    );

    // audio.file: pathRange must slice to exactly the path text, no quotes —
    // the same slice-equality proof the TS side pins in
    // src/goldenFixture.test.ts, run here against the Rust-computed range
    // and the ACTUAL golden.ts source text (not the golden JSON's own
    // "path" field, which would make this circular).
    let ambient_ogg = actual_findings
        .iter()
        .find(|f| f.as_audio_file().is_some_and(|p| p.path == "ambient.ogg"))
        .expect("golden.ts must still reference ambient.ogg");
    let ambient_mp3 = actual_findings
        .iter()
        .find(|f| f.as_audio_file().is_some_and(|p| p.path == "ambient.mp3"))
        .expect("golden.ts must still reference ambient.mp3");
    assert_eq!(
        ambient_ogg.range, ambient_mp3.range,
        "both strings in the Howler src array must share the enclosing new Howl(...) call's range"
    );
    for finding in [ambient_ogg, ambient_mp3] {
        let payload = finding.as_audio_file().unwrap();
        let lines: Vec<&str> = golden_ts.lines().collect();
        let line = lines[payload.path_range.start.line as usize];
        let sliced = &line[payload.path_range.start.character as usize
            ..payload.path_range.end.character as usize];
        assert_eq!(
            sliced, payload.path,
            "pathRange must slice to exactly the path text out of the real source, no quotes"
        );
    }

    // Wad (github.com/rserota/wad) coverage, pinned by name rather than
    // implied by the generic nested-object case above: file-mode source
    // (a string nested in `new Wad({...})`'s object arg) IS a finding,
    // slice-equality-proven same as the Howler case; synthesis-mode source
    // ('sine', no audio extension) is NOT — both directions asserted
    // explicitly, not just left to the full-array equality above to catch.
    let wad_jump = actual_findings
        .iter()
        .find(|f| {
            f.as_audio_file()
                .is_some_and(|p| p.path == "sounds/jump.wav")
        })
        .expect("golden.ts must still reference sounds/jump.wav via new Wad({...})");
    let wad_payload = wad_jump.as_audio_file().unwrap();
    let wad_lines: Vec<&str> = golden_ts.lines().collect();
    let wad_line = wad_lines[wad_payload.path_range.start.line as usize];
    let wad_sliced = &wad_line[wad_payload.path_range.start.character as usize
        ..wad_payload.path_range.end.character as usize];
    assert_eq!(
        wad_sliced, wad_payload.path,
        "Wad's pathRange must slice to exactly the path text, no quotes"
    );
    assert!(
        !actual_findings
            .iter()
            .any(|f| f.as_audio_file().is_some_and(|p| p.path == "sine")),
        "new Wad({{source: 'sine'}}) is synthesis mode, not a file reference — must NOT be a finding"
    );

    write_frame(
        &mut stdin,
        &serde_json::to_vec(&json!({"jsonrpc": "2.0", "id": 3, "method": "shutdown"})).unwrap(),
    );
    read_frame(&mut stdout);
    let status = child.wait().unwrap();
    assert!(status.success());
}
