// Auto-generated WebGPU function wrappers for WASM.
// WASM imported functions cannot have their address taken (not in indirect call table).
// These non-inline wrappers ensure addressable function pointers.
//
// Generated by generate-wgpu-shim.py — do not edit

#include "emscripten_wgpu_shim.h"

WGPUInstance wgpuCreateInstance(WGPU_NULLABLE WGPUInstanceDescriptor const * descriptor) { return __wasm_import_wgpuCreateInstance(descriptor); }
void wgpuGetInstanceFeatures(WGPUSupportedInstanceFeatures * features) { __wasm_import_wgpuGetInstanceFeatures(features); }
WGPUStatus wgpuGetInstanceLimits(WGPUInstanceLimits * limits) { return __wasm_import_wgpuGetInstanceLimits(limits); }
WGPUBool wgpuHasInstanceFeature(WGPUInstanceFeatureName feature) { return __wasm_import_wgpuHasInstanceFeature(feature); }
WGPUProc wgpuGetProcAddress(WGPUStringView procName) { return __wasm_import_wgpuGetProcAddress(procName); }
WGPUDevice wgpuAdapterCreateDevice(WGPUAdapter adapter, WGPU_NULLABLE WGPUDeviceDescriptor const * descriptor) { return __wasm_import_wgpuAdapterCreateDevice(adapter, descriptor); }
void wgpuAdapterGetFeatures(WGPUAdapter adapter, WGPUSupportedFeatures * features) { __wasm_import_wgpuAdapterGetFeatures(adapter, features); }
WGPUStatus wgpuAdapterGetFormatCapabilities(WGPUAdapter adapter, WGPUTextureFormat format, WGPUDawnFormatCapabilities * capabilities) { return __wasm_import_wgpuAdapterGetFormatCapabilities(adapter, format, capabilities); }
WGPUStatus wgpuAdapterGetInfo(WGPUAdapter adapter, WGPUAdapterInfo * info) { return __wasm_import_wgpuAdapterGetInfo(adapter, info); }
WGPUInstance wgpuAdapterGetInstance(WGPUAdapter adapter) { return __wasm_import_wgpuAdapterGetInstance(adapter); }
WGPUStatus wgpuAdapterGetLimits(WGPUAdapter adapter, WGPULimits * limits) { return __wasm_import_wgpuAdapterGetLimits(adapter, limits); }
WGPUBool wgpuAdapterHasFeature(WGPUAdapter adapter, WGPUFeatureName feature) { return __wasm_import_wgpuAdapterHasFeature(adapter, feature); }
WGPUFuture wgpuAdapterRequestDevice(WGPUAdapter adapter, WGPU_NULLABLE WGPUDeviceDescriptor const * descriptor, WGPURequestDeviceCallbackInfo callbackInfo) { return __wasm_import_wgpuAdapterRequestDevice(adapter, descriptor, callbackInfo); }
void wgpuAdapterAddRef(WGPUAdapter adapter) { __wasm_import_wgpuAdapterAddRef(adapter); }
void wgpuAdapterRelease(WGPUAdapter adapter) { __wasm_import_wgpuAdapterRelease(adapter); }
void wgpuAdapterInfoFreeMembers(WGPUAdapterInfo adapterInfo) { __wasm_import_wgpuAdapterInfoFreeMembers(adapterInfo); }
void wgpuAdapterPropertiesMemoryHeapsFreeMembers(WGPUAdapterPropertiesMemoryHeaps adapterPropertiesMemoryHeaps) { __wasm_import_wgpuAdapterPropertiesMemoryHeapsFreeMembers(adapterPropertiesMemoryHeaps); }
void wgpuAdapterPropertiesSubgroupMatrixConfigsFreeMembers(WGPUAdapterPropertiesSubgroupMatrixConfigs adapterPropertiesSubgroupMatrixConfigs) { __wasm_import_wgpuAdapterPropertiesSubgroupMatrixConfigsFreeMembers(adapterPropertiesSubgroupMatrixConfigs); }
void wgpuBindGroupSetLabel(WGPUBindGroup bindGroup, WGPUStringView label) { __wasm_import_wgpuBindGroupSetLabel(bindGroup, label); }
void wgpuBindGroupAddRef(WGPUBindGroup bindGroup) { __wasm_import_wgpuBindGroupAddRef(bindGroup); }
void wgpuBindGroupRelease(WGPUBindGroup bindGroup) { __wasm_import_wgpuBindGroupRelease(bindGroup); }
void wgpuBindGroupLayoutSetLabel(WGPUBindGroupLayout bindGroupLayout, WGPUStringView label) { __wasm_import_wgpuBindGroupLayoutSetLabel(bindGroupLayout, label); }
void wgpuBindGroupLayoutAddRef(WGPUBindGroupLayout bindGroupLayout) { __wasm_import_wgpuBindGroupLayoutAddRef(bindGroupLayout); }
void wgpuBindGroupLayoutRelease(WGPUBindGroupLayout bindGroupLayout) { __wasm_import_wgpuBindGroupLayoutRelease(bindGroupLayout); }
WGPUTexelBufferView wgpuBufferCreateTexelView(WGPUBuffer buffer, WGPUTexelBufferViewDescriptor const * descriptor) { return __wasm_import_wgpuBufferCreateTexelView(buffer, descriptor); }
void wgpuBufferDestroy(WGPUBuffer buffer) { __wasm_import_wgpuBufferDestroy(buffer); }
void const * wgpuBufferGetConstMappedRange(WGPUBuffer buffer, size_t offset, size_t size) { return __wasm_import_wgpuBufferGetConstMappedRange(buffer, offset, size); }
void * wgpuBufferGetMappedRange(WGPUBuffer buffer, size_t offset, size_t size) { return __wasm_import_wgpuBufferGetMappedRange(buffer, offset, size); }
WGPUBufferMapState wgpuBufferGetMapState(WGPUBuffer buffer) { return __wasm_import_wgpuBufferGetMapState(buffer); }
uint64_t wgpuBufferGetSize(WGPUBuffer buffer) { return __wasm_import_wgpuBufferGetSize(buffer); }
WGPUBufferUsage wgpuBufferGetUsage(WGPUBuffer buffer) { return __wasm_import_wgpuBufferGetUsage(buffer); }
WGPUFuture wgpuBufferMapAsync(WGPUBuffer buffer, WGPUMapMode mode, size_t offset, size_t size, WGPUBufferMapCallbackInfo callbackInfo) { return __wasm_import_wgpuBufferMapAsync(buffer, mode, offset, size, callbackInfo); }
WGPUStatus wgpuBufferReadMappedRange(WGPUBuffer buffer, size_t offset, void * data, size_t size) { return __wasm_import_wgpuBufferReadMappedRange(buffer, offset, data, size); }
void wgpuBufferSetLabel(WGPUBuffer buffer, WGPUStringView label) { __wasm_import_wgpuBufferSetLabel(buffer, label); }
void wgpuBufferUnmap(WGPUBuffer buffer) { __wasm_import_wgpuBufferUnmap(buffer); }
WGPUStatus wgpuBufferWriteMappedRange(WGPUBuffer buffer, size_t offset, void const * data, size_t size) { return __wasm_import_wgpuBufferWriteMappedRange(buffer, offset, data, size); }
void wgpuBufferAddRef(WGPUBuffer buffer) { __wasm_import_wgpuBufferAddRef(buffer); }
void wgpuBufferRelease(WGPUBuffer buffer) { __wasm_import_wgpuBufferRelease(buffer); }
void wgpuCommandBufferSetLabel(WGPUCommandBuffer commandBuffer, WGPUStringView label) { __wasm_import_wgpuCommandBufferSetLabel(commandBuffer, label); }
void wgpuCommandBufferAddRef(WGPUCommandBuffer commandBuffer) { __wasm_import_wgpuCommandBufferAddRef(commandBuffer); }
void wgpuCommandBufferRelease(WGPUCommandBuffer commandBuffer) { __wasm_import_wgpuCommandBufferRelease(commandBuffer); }
WGPUComputePassEncoder wgpuCommandEncoderBeginComputePass(WGPUCommandEncoder commandEncoder, WGPU_NULLABLE WGPUComputePassDescriptor const * descriptor) { return __wasm_import_wgpuCommandEncoderBeginComputePass(commandEncoder, descriptor); }
WGPURenderPassEncoder wgpuCommandEncoderBeginRenderPass(WGPUCommandEncoder commandEncoder, WGPURenderPassDescriptor const * descriptor) { return __wasm_import_wgpuCommandEncoderBeginRenderPass(commandEncoder, descriptor); }
void wgpuCommandEncoderClearBuffer(WGPUCommandEncoder commandEncoder, WGPUBuffer buffer, uint64_t offset, uint64_t size) { __wasm_import_wgpuCommandEncoderClearBuffer(commandEncoder, buffer, offset, size); }
void wgpuCommandEncoderCopyBufferToBuffer(WGPUCommandEncoder commandEncoder, WGPUBuffer source, uint64_t sourceOffset, WGPUBuffer destination, uint64_t destinationOffset, uint64_t size) { __wasm_import_wgpuCommandEncoderCopyBufferToBuffer(commandEncoder, source, sourceOffset, destination, destinationOffset, size); }
void wgpuCommandEncoderCopyBufferToTexture(WGPUCommandEncoder commandEncoder, WGPUTexelCopyBufferInfo const * source, WGPUTexelCopyTextureInfo const * destination, WGPUExtent3D const * copySize) { __wasm_import_wgpuCommandEncoderCopyBufferToTexture(commandEncoder, source, destination, copySize); }
void wgpuCommandEncoderCopyTextureToBuffer(WGPUCommandEncoder commandEncoder, WGPUTexelCopyTextureInfo const * source, WGPUTexelCopyBufferInfo const * destination, WGPUExtent3D const * copySize) { __wasm_import_wgpuCommandEncoderCopyTextureToBuffer(commandEncoder, source, destination, copySize); }
void wgpuCommandEncoderCopyTextureToTexture(WGPUCommandEncoder commandEncoder, WGPUTexelCopyTextureInfo const * source, WGPUTexelCopyTextureInfo const * destination, WGPUExtent3D const * copySize) { __wasm_import_wgpuCommandEncoderCopyTextureToTexture(commandEncoder, source, destination, copySize); }
WGPUCommandBuffer wgpuCommandEncoderFinish(WGPUCommandEncoder commandEncoder, WGPU_NULLABLE WGPUCommandBufferDescriptor const * descriptor) { return __wasm_import_wgpuCommandEncoderFinish(commandEncoder, descriptor); }
void wgpuCommandEncoderInjectValidationError(WGPUCommandEncoder commandEncoder, WGPUStringView message) { __wasm_import_wgpuCommandEncoderInjectValidationError(commandEncoder, message); }
void wgpuCommandEncoderInsertDebugMarker(WGPUCommandEncoder commandEncoder, WGPUStringView markerLabel) { __wasm_import_wgpuCommandEncoderInsertDebugMarker(commandEncoder, markerLabel); }
void wgpuCommandEncoderPopDebugGroup(WGPUCommandEncoder commandEncoder) { __wasm_import_wgpuCommandEncoderPopDebugGroup(commandEncoder); }
void wgpuCommandEncoderPushDebugGroup(WGPUCommandEncoder commandEncoder, WGPUStringView groupLabel) { __wasm_import_wgpuCommandEncoderPushDebugGroup(commandEncoder, groupLabel); }
void wgpuCommandEncoderResolveQuerySet(WGPUCommandEncoder commandEncoder, WGPUQuerySet querySet, uint32_t firstQuery, uint32_t queryCount, WGPUBuffer destination, uint64_t destinationOffset) { __wasm_import_wgpuCommandEncoderResolveQuerySet(commandEncoder, querySet, firstQuery, queryCount, destination, destinationOffset); }
void wgpuCommandEncoderSetLabel(WGPUCommandEncoder commandEncoder, WGPUStringView label) { __wasm_import_wgpuCommandEncoderSetLabel(commandEncoder, label); }
void wgpuCommandEncoderWriteBuffer(WGPUCommandEncoder commandEncoder, WGPUBuffer buffer, uint64_t bufferOffset, uint8_t const * data, uint64_t size) { __wasm_import_wgpuCommandEncoderWriteBuffer(commandEncoder, buffer, bufferOffset, data, size); }
void wgpuCommandEncoderWriteTimestamp(WGPUCommandEncoder commandEncoder, WGPUQuerySet querySet, uint32_t queryIndex) { __wasm_import_wgpuCommandEncoderWriteTimestamp(commandEncoder, querySet, queryIndex); }
void wgpuCommandEncoderAddRef(WGPUCommandEncoder commandEncoder) { __wasm_import_wgpuCommandEncoderAddRef(commandEncoder); }
void wgpuCommandEncoderRelease(WGPUCommandEncoder commandEncoder) { __wasm_import_wgpuCommandEncoderRelease(commandEncoder); }
void wgpuComputePassEncoderDispatchWorkgroups(WGPUComputePassEncoder computePassEncoder, uint32_t workgroupCountX, uint32_t workgroupCountY, uint32_t workgroupCountZ) { __wasm_import_wgpuComputePassEncoderDispatchWorkgroups(computePassEncoder, workgroupCountX, workgroupCountY, workgroupCountZ); }
void wgpuComputePassEncoderDispatchWorkgroupsIndirect(WGPUComputePassEncoder computePassEncoder, WGPUBuffer indirectBuffer, uint64_t indirectOffset) { __wasm_import_wgpuComputePassEncoderDispatchWorkgroupsIndirect(computePassEncoder, indirectBuffer, indirectOffset); }
void wgpuComputePassEncoderEnd(WGPUComputePassEncoder computePassEncoder) { __wasm_import_wgpuComputePassEncoderEnd(computePassEncoder); }
void wgpuComputePassEncoderInsertDebugMarker(WGPUComputePassEncoder computePassEncoder, WGPUStringView markerLabel) { __wasm_import_wgpuComputePassEncoderInsertDebugMarker(computePassEncoder, markerLabel); }
void wgpuComputePassEncoderPopDebugGroup(WGPUComputePassEncoder computePassEncoder) { __wasm_import_wgpuComputePassEncoderPopDebugGroup(computePassEncoder); }
void wgpuComputePassEncoderPushDebugGroup(WGPUComputePassEncoder computePassEncoder, WGPUStringView groupLabel) { __wasm_import_wgpuComputePassEncoderPushDebugGroup(computePassEncoder, groupLabel); }
void wgpuComputePassEncoderSetBindGroup(WGPUComputePassEncoder computePassEncoder, uint32_t groupIndex, WGPU_NULLABLE WGPUBindGroup group, size_t dynamicOffsetCount, uint32_t const * dynamicOffsets) { __wasm_import_wgpuComputePassEncoderSetBindGroup(computePassEncoder, groupIndex, group, dynamicOffsetCount, dynamicOffsets); }
void wgpuComputePassEncoderSetImmediates(WGPUComputePassEncoder computePassEncoder, uint32_t offset, void const * data, size_t size) { __wasm_import_wgpuComputePassEncoderSetImmediates(computePassEncoder, offset, data, size); }
void wgpuComputePassEncoderSetLabel(WGPUComputePassEncoder computePassEncoder, WGPUStringView label) { __wasm_import_wgpuComputePassEncoderSetLabel(computePassEncoder, label); }
void wgpuComputePassEncoderSetPipeline(WGPUComputePassEncoder computePassEncoder, WGPUComputePipeline pipeline) { __wasm_import_wgpuComputePassEncoderSetPipeline(computePassEncoder, pipeline); }
void wgpuComputePassEncoderSetResourceTable(WGPUComputePassEncoder computePassEncoder, WGPU_NULLABLE WGPUResourceTable table) { __wasm_import_wgpuComputePassEncoderSetResourceTable(computePassEncoder, table); }
void wgpuComputePassEncoderWriteTimestamp(WGPUComputePassEncoder computePassEncoder, WGPUQuerySet querySet, uint32_t queryIndex) { __wasm_import_wgpuComputePassEncoderWriteTimestamp(computePassEncoder, querySet, queryIndex); }
void wgpuComputePassEncoderAddRef(WGPUComputePassEncoder computePassEncoder) { __wasm_import_wgpuComputePassEncoderAddRef(computePassEncoder); }
void wgpuComputePassEncoderRelease(WGPUComputePassEncoder computePassEncoder) { __wasm_import_wgpuComputePassEncoderRelease(computePassEncoder); }
WGPUBindGroupLayout wgpuComputePipelineGetBindGroupLayout(WGPUComputePipeline computePipeline, uint32_t groupIndex) { return __wasm_import_wgpuComputePipelineGetBindGroupLayout(computePipeline, groupIndex); }
void wgpuComputePipelineSetLabel(WGPUComputePipeline computePipeline, WGPUStringView label) { __wasm_import_wgpuComputePipelineSetLabel(computePipeline, label); }
void wgpuComputePipelineAddRef(WGPUComputePipeline computePipeline) { __wasm_import_wgpuComputePipelineAddRef(computePipeline); }
void wgpuComputePipelineRelease(WGPUComputePipeline computePipeline) { __wasm_import_wgpuComputePipelineRelease(computePipeline); }
void wgpuDawnDrmFormatCapabilitiesFreeMembers(WGPUDawnDrmFormatCapabilities dawnDrmFormatCapabilities) { __wasm_import_wgpuDawnDrmFormatCapabilitiesFreeMembers(dawnDrmFormatCapabilities); }
WGPUBindGroup wgpuDeviceCreateBindGroup(WGPUDevice device, WGPUBindGroupDescriptor const * descriptor) { return __wasm_import_wgpuDeviceCreateBindGroup(device, descriptor); }
WGPUBindGroupLayout wgpuDeviceCreateBindGroupLayout(WGPUDevice device, WGPUBindGroupLayoutDescriptor const * descriptor) { return __wasm_import_wgpuDeviceCreateBindGroupLayout(device, descriptor); }
WGPU_NULLABLE WGPUBuffer wgpuDeviceCreateBuffer(WGPUDevice device, WGPUBufferDescriptor const * descriptor) { return __wasm_import_wgpuDeviceCreateBuffer(device, descriptor); }
WGPUCommandEncoder wgpuDeviceCreateCommandEncoder(WGPUDevice device, WGPU_NULLABLE WGPUCommandEncoderDescriptor const * descriptor) { return __wasm_import_wgpuDeviceCreateCommandEncoder(device, descriptor); }
WGPUComputePipeline wgpuDeviceCreateComputePipeline(WGPUDevice device, WGPUComputePipelineDescriptor const * descriptor) { return __wasm_import_wgpuDeviceCreateComputePipeline(device, descriptor); }
WGPUFuture wgpuDeviceCreateComputePipelineAsync(WGPUDevice device, WGPUComputePipelineDescriptor const * descriptor, WGPUCreateComputePipelineAsyncCallbackInfo callbackInfo) { return __wasm_import_wgpuDeviceCreateComputePipelineAsync(device, descriptor, callbackInfo); }
WGPUBuffer wgpuDeviceCreateErrorBuffer(WGPUDevice device, WGPUBufferDescriptor const * descriptor) { return __wasm_import_wgpuDeviceCreateErrorBuffer(device, descriptor); }
WGPUExternalTexture wgpuDeviceCreateErrorExternalTexture(WGPUDevice device) { return __wasm_import_wgpuDeviceCreateErrorExternalTexture(device); }
WGPUShaderModule wgpuDeviceCreateErrorShaderModule(WGPUDevice device, WGPUShaderModuleDescriptor const * descriptor, WGPUStringView errorMessage) { return __wasm_import_wgpuDeviceCreateErrorShaderModule(device, descriptor, errorMessage); }
WGPUTexture wgpuDeviceCreateErrorTexture(WGPUDevice device, WGPUTextureDescriptor const * descriptor) { return __wasm_import_wgpuDeviceCreateErrorTexture(device, descriptor); }
WGPUExternalTexture wgpuDeviceCreateExternalTexture(WGPUDevice device, WGPUExternalTextureDescriptor const * externalTextureDescriptor) { return __wasm_import_wgpuDeviceCreateExternalTexture(device, externalTextureDescriptor); }
WGPUPipelineLayout wgpuDeviceCreatePipelineLayout(WGPUDevice device, WGPUPipelineLayoutDescriptor const * descriptor) { return __wasm_import_wgpuDeviceCreatePipelineLayout(device, descriptor); }
WGPUQuerySet wgpuDeviceCreateQuerySet(WGPUDevice device, WGPUQuerySetDescriptor const * descriptor) { return __wasm_import_wgpuDeviceCreateQuerySet(device, descriptor); }
WGPURenderBundleEncoder wgpuDeviceCreateRenderBundleEncoder(WGPUDevice device, WGPURenderBundleEncoderDescriptor const * descriptor) { return __wasm_import_wgpuDeviceCreateRenderBundleEncoder(device, descriptor); }
WGPURenderPipeline wgpuDeviceCreateRenderPipeline(WGPUDevice device, WGPURenderPipelineDescriptor const * descriptor) { return __wasm_import_wgpuDeviceCreateRenderPipeline(device, descriptor); }
WGPUFuture wgpuDeviceCreateRenderPipelineAsync(WGPUDevice device, WGPURenderPipelineDescriptor const * descriptor, WGPUCreateRenderPipelineAsyncCallbackInfo callbackInfo) { return __wasm_import_wgpuDeviceCreateRenderPipelineAsync(device, descriptor, callbackInfo); }
WGPUResourceTable wgpuDeviceCreateResourceTable(WGPUDevice device, WGPUResourceTableDescriptor const * descriptor) { return __wasm_import_wgpuDeviceCreateResourceTable(device, descriptor); }
WGPUSampler wgpuDeviceCreateSampler(WGPUDevice device, WGPU_NULLABLE WGPUSamplerDescriptor const * descriptor) { return __wasm_import_wgpuDeviceCreateSampler(device, descriptor); }
WGPUShaderModule wgpuDeviceCreateShaderModule(WGPUDevice device, WGPUShaderModuleDescriptor const * descriptor) { return __wasm_import_wgpuDeviceCreateShaderModule(device, descriptor); }
WGPUTexture wgpuDeviceCreateTexture(WGPUDevice device, WGPUTextureDescriptor const * descriptor) { return __wasm_import_wgpuDeviceCreateTexture(device, descriptor); }
void wgpuDeviceDestroy(WGPUDevice device) { __wasm_import_wgpuDeviceDestroy(device); }
void wgpuDeviceForceLoss(WGPUDevice device, WGPUDeviceLostReason type, WGPUStringView message) { __wasm_import_wgpuDeviceForceLoss(device, type, message); }
WGPUAdapter wgpuDeviceGetAdapter(WGPUDevice device) { return __wasm_import_wgpuDeviceGetAdapter(device); }
WGPUStatus wgpuDeviceGetAdapterInfo(WGPUDevice device, WGPUAdapterInfo * adapterInfo) { return __wasm_import_wgpuDeviceGetAdapterInfo(device, adapterInfo); }
WGPUStatus wgpuDeviceGetAHardwareBufferProperties(WGPUDevice device, void * handle, WGPUAHardwareBufferProperties * properties) { return __wasm_import_wgpuDeviceGetAHardwareBufferProperties(device, handle, properties); }
void wgpuDeviceGetFeatures(WGPUDevice device, WGPUSupportedFeatures * features) { __wasm_import_wgpuDeviceGetFeatures(device, features); }
WGPUStatus wgpuDeviceGetLimits(WGPUDevice device, WGPULimits * limits) { return __wasm_import_wgpuDeviceGetLimits(device, limits); }
WGPUFuture wgpuDeviceGetLostFuture(WGPUDevice device) { return __wasm_import_wgpuDeviceGetLostFuture(device); }
WGPUQueue wgpuDeviceGetQueue(WGPUDevice device) { return __wasm_import_wgpuDeviceGetQueue(device); }
WGPUBool wgpuDeviceHasFeature(WGPUDevice device, WGPUFeatureName feature) { return __wasm_import_wgpuDeviceHasFeature(device, feature); }
WGPUSharedBufferMemory wgpuDeviceImportSharedBufferMemory(WGPUDevice device, WGPUSharedBufferMemoryDescriptor const * descriptor) { return __wasm_import_wgpuDeviceImportSharedBufferMemory(device, descriptor); }
WGPUSharedFence wgpuDeviceImportSharedFence(WGPUDevice device, WGPUSharedFenceDescriptor const * descriptor) { return __wasm_import_wgpuDeviceImportSharedFence(device, descriptor); }
WGPUSharedTextureMemory wgpuDeviceImportSharedTextureMemory(WGPUDevice device, WGPUSharedTextureMemoryDescriptor const * descriptor) { return __wasm_import_wgpuDeviceImportSharedTextureMemory(device, descriptor); }
void wgpuDeviceInjectError(WGPUDevice device, WGPUErrorType type, WGPUStringView message) { __wasm_import_wgpuDeviceInjectError(device, type, message); }
WGPUFuture wgpuDevicePopErrorScope(WGPUDevice device, WGPUPopErrorScopeCallbackInfo callbackInfo) { return __wasm_import_wgpuDevicePopErrorScope(device, callbackInfo); }
void wgpuDevicePushErrorScope(WGPUDevice device, WGPUErrorFilter filter) { __wasm_import_wgpuDevicePushErrorScope(device, filter); }
void wgpuDeviceSetLabel(WGPUDevice device, WGPUStringView label) { __wasm_import_wgpuDeviceSetLabel(device, label); }
void wgpuDeviceSetLoggingCallback(WGPUDevice device, WGPULoggingCallbackInfo callbackInfo) { __wasm_import_wgpuDeviceSetLoggingCallback(device, callbackInfo); }
void wgpuDeviceTick(WGPUDevice device) { __wasm_import_wgpuDeviceTick(device); }
void wgpuDeviceValidateTextureDescriptor(WGPUDevice device, WGPUTextureDescriptor const * descriptor) { __wasm_import_wgpuDeviceValidateTextureDescriptor(device, descriptor); }
void wgpuDeviceAddRef(WGPUDevice device) { __wasm_import_wgpuDeviceAddRef(device); }
void wgpuDeviceRelease(WGPUDevice device) { __wasm_import_wgpuDeviceRelease(device); }
void wgpuExternalTextureDestroy(WGPUExternalTexture externalTexture) { __wasm_import_wgpuExternalTextureDestroy(externalTexture); }
void wgpuExternalTextureExpire(WGPUExternalTexture externalTexture) { __wasm_import_wgpuExternalTextureExpire(externalTexture); }
void wgpuExternalTextureRefresh(WGPUExternalTexture externalTexture) { __wasm_import_wgpuExternalTextureRefresh(externalTexture); }
void wgpuExternalTextureSetLabel(WGPUExternalTexture externalTexture, WGPUStringView label) { __wasm_import_wgpuExternalTextureSetLabel(externalTexture, label); }
void wgpuExternalTextureAddRef(WGPUExternalTexture externalTexture) { __wasm_import_wgpuExternalTextureAddRef(externalTexture); }
void wgpuExternalTextureRelease(WGPUExternalTexture externalTexture) { __wasm_import_wgpuExternalTextureRelease(externalTexture); }
WGPUSurface wgpuInstanceCreateSurface(WGPUInstance instance, WGPUSurfaceDescriptor const * descriptor) { return __wasm_import_wgpuInstanceCreateSurface(instance, descriptor); }
void wgpuInstanceGetWGSLLanguageFeatures(WGPUInstance instance, WGPUSupportedWGSLLanguageFeatures * features) { __wasm_import_wgpuInstanceGetWGSLLanguageFeatures(instance, features); }
WGPUBool wgpuInstanceHasWGSLLanguageFeature(WGPUInstance instance, WGPUWGSLLanguageFeatureName feature) { return __wasm_import_wgpuInstanceHasWGSLLanguageFeature(instance, feature); }
void wgpuInstanceProcessEvents(WGPUInstance instance) { __wasm_import_wgpuInstanceProcessEvents(instance); }
WGPUFuture wgpuInstanceRequestAdapter(WGPUInstance instance, WGPU_NULLABLE WGPURequestAdapterOptions const * options, WGPURequestAdapterCallbackInfo callbackInfo) { return __wasm_import_wgpuInstanceRequestAdapter(instance, options, callbackInfo); }
WGPUWaitStatus wgpuInstanceWaitAny(WGPUInstance instance, size_t futureCount, WGPU_NULLABLE WGPUFutureWaitInfo * futures, uint64_t timeoutNS) { return __wasm_import_wgpuInstanceWaitAny(instance, futureCount, futures, timeoutNS); }
void wgpuInstanceAddRef(WGPUInstance instance) { __wasm_import_wgpuInstanceAddRef(instance); }
void wgpuInstanceRelease(WGPUInstance instance) { __wasm_import_wgpuInstanceRelease(instance); }
void wgpuPipelineLayoutSetLabel(WGPUPipelineLayout pipelineLayout, WGPUStringView label) { __wasm_import_wgpuPipelineLayoutSetLabel(pipelineLayout, label); }
void wgpuPipelineLayoutAddRef(WGPUPipelineLayout pipelineLayout) { __wasm_import_wgpuPipelineLayoutAddRef(pipelineLayout); }
void wgpuPipelineLayoutRelease(WGPUPipelineLayout pipelineLayout) { __wasm_import_wgpuPipelineLayoutRelease(pipelineLayout); }
void wgpuQuerySetDestroy(WGPUQuerySet querySet) { __wasm_import_wgpuQuerySetDestroy(querySet); }
uint32_t wgpuQuerySetGetCount(WGPUQuerySet querySet) { return __wasm_import_wgpuQuerySetGetCount(querySet); }
WGPUQueryType wgpuQuerySetGetType(WGPUQuerySet querySet) { return __wasm_import_wgpuQuerySetGetType(querySet); }
void wgpuQuerySetSetLabel(WGPUQuerySet querySet, WGPUStringView label) { __wasm_import_wgpuQuerySetSetLabel(querySet, label); }
void wgpuQuerySetAddRef(WGPUQuerySet querySet) { __wasm_import_wgpuQuerySetAddRef(querySet); }
void wgpuQuerySetRelease(WGPUQuerySet querySet) { __wasm_import_wgpuQuerySetRelease(querySet); }
void wgpuQueueCopyExternalTextureForBrowser(WGPUQueue queue, WGPUImageCopyExternalTexture const * source, WGPUTexelCopyTextureInfo const * destination, WGPUExtent3D const * copySize, WGPUCopyTextureForBrowserOptions const * options) { __wasm_import_wgpuQueueCopyExternalTextureForBrowser(queue, source, destination, copySize, options); }
void wgpuQueueCopyTextureForBrowser(WGPUQueue queue, WGPUTexelCopyTextureInfo const * source, WGPUTexelCopyTextureInfo const * destination, WGPUExtent3D const * copySize, WGPUCopyTextureForBrowserOptions const * options) { __wasm_import_wgpuQueueCopyTextureForBrowser(queue, source, destination, copySize, options); }
WGPUFuture wgpuQueueOnSubmittedWorkDone(WGPUQueue queue, WGPUQueueWorkDoneCallbackInfo callbackInfo) { return __wasm_import_wgpuQueueOnSubmittedWorkDone(queue, callbackInfo); }
void wgpuQueueSetLabel(WGPUQueue queue, WGPUStringView label) { __wasm_import_wgpuQueueSetLabel(queue, label); }
void wgpuQueueSubmit(WGPUQueue queue, size_t commandCount, WGPUCommandBuffer const * commands) { __wasm_import_wgpuQueueSubmit(queue, commandCount, commands); }
void wgpuQueueWriteBuffer(WGPUQueue queue, WGPUBuffer buffer, uint64_t bufferOffset, void const * data, size_t size) { __wasm_import_wgpuQueueWriteBuffer(queue, buffer, bufferOffset, data, size); }
void wgpuQueueWriteTexture(WGPUQueue queue, WGPUTexelCopyTextureInfo const * destination, void const * data, size_t dataSize, WGPUTexelCopyBufferLayout const * dataLayout, WGPUExtent3D const * writeSize) { __wasm_import_wgpuQueueWriteTexture(queue, destination, data, dataSize, dataLayout, writeSize); }
void wgpuQueueAddRef(WGPUQueue queue) { __wasm_import_wgpuQueueAddRef(queue); }
void wgpuQueueRelease(WGPUQueue queue) { __wasm_import_wgpuQueueRelease(queue); }
void wgpuRenderBundleSetLabel(WGPURenderBundle renderBundle, WGPUStringView label) { __wasm_import_wgpuRenderBundleSetLabel(renderBundle, label); }
void wgpuRenderBundleAddRef(WGPURenderBundle renderBundle) { __wasm_import_wgpuRenderBundleAddRef(renderBundle); }
void wgpuRenderBundleRelease(WGPURenderBundle renderBundle) { __wasm_import_wgpuRenderBundleRelease(renderBundle); }
void wgpuRenderBundleEncoderDraw(WGPURenderBundleEncoder renderBundleEncoder, uint32_t vertexCount, uint32_t instanceCount, uint32_t firstVertex, uint32_t firstInstance) { __wasm_import_wgpuRenderBundleEncoderDraw(renderBundleEncoder, vertexCount, instanceCount, firstVertex, firstInstance); }
void wgpuRenderBundleEncoderDrawIndexed(WGPURenderBundleEncoder renderBundleEncoder, uint32_t indexCount, uint32_t instanceCount, uint32_t firstIndex, int32_t baseVertex, uint32_t firstInstance) { __wasm_import_wgpuRenderBundleEncoderDrawIndexed(renderBundleEncoder, indexCount, instanceCount, firstIndex, baseVertex, firstInstance); }
void wgpuRenderBundleEncoderDrawIndexedIndirect(WGPURenderBundleEncoder renderBundleEncoder, WGPUBuffer indirectBuffer, uint64_t indirectOffset) { __wasm_import_wgpuRenderBundleEncoderDrawIndexedIndirect(renderBundleEncoder, indirectBuffer, indirectOffset); }
void wgpuRenderBundleEncoderDrawIndirect(WGPURenderBundleEncoder renderBundleEncoder, WGPUBuffer indirectBuffer, uint64_t indirectOffset) { __wasm_import_wgpuRenderBundleEncoderDrawIndirect(renderBundleEncoder, indirectBuffer, indirectOffset); }
WGPURenderBundle wgpuRenderBundleEncoderFinish(WGPURenderBundleEncoder renderBundleEncoder, WGPU_NULLABLE WGPURenderBundleDescriptor const * descriptor) { return __wasm_import_wgpuRenderBundleEncoderFinish(renderBundleEncoder, descriptor); }
void wgpuRenderBundleEncoderInsertDebugMarker(WGPURenderBundleEncoder renderBundleEncoder, WGPUStringView markerLabel) { __wasm_import_wgpuRenderBundleEncoderInsertDebugMarker(renderBundleEncoder, markerLabel); }
void wgpuRenderBundleEncoderPopDebugGroup(WGPURenderBundleEncoder renderBundleEncoder) { __wasm_import_wgpuRenderBundleEncoderPopDebugGroup(renderBundleEncoder); }
void wgpuRenderBundleEncoderPushDebugGroup(WGPURenderBundleEncoder renderBundleEncoder, WGPUStringView groupLabel) { __wasm_import_wgpuRenderBundleEncoderPushDebugGroup(renderBundleEncoder, groupLabel); }
void wgpuRenderBundleEncoderSetBindGroup(WGPURenderBundleEncoder renderBundleEncoder, uint32_t groupIndex, WGPU_NULLABLE WGPUBindGroup group, size_t dynamicOffsetCount, uint32_t const * dynamicOffsets) { __wasm_import_wgpuRenderBundleEncoderSetBindGroup(renderBundleEncoder, groupIndex, group, dynamicOffsetCount, dynamicOffsets); }
void wgpuRenderBundleEncoderSetImmediates(WGPURenderBundleEncoder renderBundleEncoder, uint32_t offset, void const * data, size_t size) { __wasm_import_wgpuRenderBundleEncoderSetImmediates(renderBundleEncoder, offset, data, size); }
void wgpuRenderBundleEncoderSetIndexBuffer(WGPURenderBundleEncoder renderBundleEncoder, WGPUBuffer buffer, WGPUIndexFormat format, uint64_t offset, uint64_t size) { __wasm_import_wgpuRenderBundleEncoderSetIndexBuffer(renderBundleEncoder, buffer, format, offset, size); }
void wgpuRenderBundleEncoderSetLabel(WGPURenderBundleEncoder renderBundleEncoder, WGPUStringView label) { __wasm_import_wgpuRenderBundleEncoderSetLabel(renderBundleEncoder, label); }
void wgpuRenderBundleEncoderSetPipeline(WGPURenderBundleEncoder renderBundleEncoder, WGPURenderPipeline pipeline) { __wasm_import_wgpuRenderBundleEncoderSetPipeline(renderBundleEncoder, pipeline); }
void wgpuRenderBundleEncoderSetResourceTable(WGPURenderBundleEncoder renderBundleEncoder, WGPU_NULLABLE WGPUResourceTable table) { __wasm_import_wgpuRenderBundleEncoderSetResourceTable(renderBundleEncoder, table); }
void wgpuRenderBundleEncoderSetVertexBuffer(WGPURenderBundleEncoder renderBundleEncoder, uint32_t slot, WGPU_NULLABLE WGPUBuffer buffer, uint64_t offset, uint64_t size) { __wasm_import_wgpuRenderBundleEncoderSetVertexBuffer(renderBundleEncoder, slot, buffer, offset, size); }
void wgpuRenderBundleEncoderAddRef(WGPURenderBundleEncoder renderBundleEncoder) { __wasm_import_wgpuRenderBundleEncoderAddRef(renderBundleEncoder); }
void wgpuRenderBundleEncoderRelease(WGPURenderBundleEncoder renderBundleEncoder) { __wasm_import_wgpuRenderBundleEncoderRelease(renderBundleEncoder); }
void wgpuRenderPassEncoderBeginOcclusionQuery(WGPURenderPassEncoder renderPassEncoder, uint32_t queryIndex) { __wasm_import_wgpuRenderPassEncoderBeginOcclusionQuery(renderPassEncoder, queryIndex); }
void wgpuRenderPassEncoderDraw(WGPURenderPassEncoder renderPassEncoder, uint32_t vertexCount, uint32_t instanceCount, uint32_t firstVertex, uint32_t firstInstance) { __wasm_import_wgpuRenderPassEncoderDraw(renderPassEncoder, vertexCount, instanceCount, firstVertex, firstInstance); }
void wgpuRenderPassEncoderDrawIndexed(WGPURenderPassEncoder renderPassEncoder, uint32_t indexCount, uint32_t instanceCount, uint32_t firstIndex, int32_t baseVertex, uint32_t firstInstance) { __wasm_import_wgpuRenderPassEncoderDrawIndexed(renderPassEncoder, indexCount, instanceCount, firstIndex, baseVertex, firstInstance); }
void wgpuRenderPassEncoderDrawIndexedIndirect(WGPURenderPassEncoder renderPassEncoder, WGPUBuffer indirectBuffer, uint64_t indirectOffset) { __wasm_import_wgpuRenderPassEncoderDrawIndexedIndirect(renderPassEncoder, indirectBuffer, indirectOffset); }
void wgpuRenderPassEncoderDrawIndirect(WGPURenderPassEncoder renderPassEncoder, WGPUBuffer indirectBuffer, uint64_t indirectOffset) { __wasm_import_wgpuRenderPassEncoderDrawIndirect(renderPassEncoder, indirectBuffer, indirectOffset); }
void wgpuRenderPassEncoderEnd(WGPURenderPassEncoder renderPassEncoder) { __wasm_import_wgpuRenderPassEncoderEnd(renderPassEncoder); }
void wgpuRenderPassEncoderEndOcclusionQuery(WGPURenderPassEncoder renderPassEncoder) { __wasm_import_wgpuRenderPassEncoderEndOcclusionQuery(renderPassEncoder); }
void wgpuRenderPassEncoderExecuteBundles(WGPURenderPassEncoder renderPassEncoder, size_t bundleCount, WGPURenderBundle const * bundles) { __wasm_import_wgpuRenderPassEncoderExecuteBundles(renderPassEncoder, bundleCount, bundles); }
void wgpuRenderPassEncoderInsertDebugMarker(WGPURenderPassEncoder renderPassEncoder, WGPUStringView markerLabel) { __wasm_import_wgpuRenderPassEncoderInsertDebugMarker(renderPassEncoder, markerLabel); }
void wgpuRenderPassEncoderMultiDrawIndexedIndirect(WGPURenderPassEncoder renderPassEncoder, WGPUBuffer indirectBuffer, uint64_t indirectOffset, uint32_t maxDrawCount, WGPU_NULLABLE WGPUBuffer drawCountBuffer, uint64_t drawCountBufferOffset) { __wasm_import_wgpuRenderPassEncoderMultiDrawIndexedIndirect(renderPassEncoder, indirectBuffer, indirectOffset, maxDrawCount, drawCountBuffer, drawCountBufferOffset); }
void wgpuRenderPassEncoderMultiDrawIndirect(WGPURenderPassEncoder renderPassEncoder, WGPUBuffer indirectBuffer, uint64_t indirectOffset, uint32_t maxDrawCount, WGPU_NULLABLE WGPUBuffer drawCountBuffer, uint64_t drawCountBufferOffset) { __wasm_import_wgpuRenderPassEncoderMultiDrawIndirect(renderPassEncoder, indirectBuffer, indirectOffset, maxDrawCount, drawCountBuffer, drawCountBufferOffset); }
void wgpuRenderPassEncoderPixelLocalStorageBarrier(WGPURenderPassEncoder renderPassEncoder) { __wasm_import_wgpuRenderPassEncoderPixelLocalStorageBarrier(renderPassEncoder); }
void wgpuRenderPassEncoderPopDebugGroup(WGPURenderPassEncoder renderPassEncoder) { __wasm_import_wgpuRenderPassEncoderPopDebugGroup(renderPassEncoder); }
void wgpuRenderPassEncoderPushDebugGroup(WGPURenderPassEncoder renderPassEncoder, WGPUStringView groupLabel) { __wasm_import_wgpuRenderPassEncoderPushDebugGroup(renderPassEncoder, groupLabel); }
void wgpuRenderPassEncoderSetBindGroup(WGPURenderPassEncoder renderPassEncoder, uint32_t groupIndex, WGPU_NULLABLE WGPUBindGroup group, size_t dynamicOffsetCount, uint32_t const * dynamicOffsets) { __wasm_import_wgpuRenderPassEncoderSetBindGroup(renderPassEncoder, groupIndex, group, dynamicOffsetCount, dynamicOffsets); }
void wgpuRenderPassEncoderSetBlendConstant(WGPURenderPassEncoder renderPassEncoder, WGPUColor const * color) { __wasm_import_wgpuRenderPassEncoderSetBlendConstant(renderPassEncoder, color); }
void wgpuRenderPassEncoderSetImmediates(WGPURenderPassEncoder renderPassEncoder, uint32_t offset, void const * data, size_t size) { __wasm_import_wgpuRenderPassEncoderSetImmediates(renderPassEncoder, offset, data, size); }
void wgpuRenderPassEncoderSetIndexBuffer(WGPURenderPassEncoder renderPassEncoder, WGPUBuffer buffer, WGPUIndexFormat format, uint64_t offset, uint64_t size) { __wasm_import_wgpuRenderPassEncoderSetIndexBuffer(renderPassEncoder, buffer, format, offset, size); }
void wgpuRenderPassEncoderSetLabel(WGPURenderPassEncoder renderPassEncoder, WGPUStringView label) { __wasm_import_wgpuRenderPassEncoderSetLabel(renderPassEncoder, label); }
void wgpuRenderPassEncoderSetPipeline(WGPURenderPassEncoder renderPassEncoder, WGPURenderPipeline pipeline) { __wasm_import_wgpuRenderPassEncoderSetPipeline(renderPassEncoder, pipeline); }
void wgpuRenderPassEncoderSetResourceTable(WGPURenderPassEncoder renderPassEncoder, WGPU_NULLABLE WGPUResourceTable table) { __wasm_import_wgpuRenderPassEncoderSetResourceTable(renderPassEncoder, table); }
void wgpuRenderPassEncoderSetScissorRect(WGPURenderPassEncoder renderPassEncoder, uint32_t x, uint32_t y, uint32_t width, uint32_t height) { __wasm_import_wgpuRenderPassEncoderSetScissorRect(renderPassEncoder, x, y, width, height); }
void wgpuRenderPassEncoderSetStencilReference(WGPURenderPassEncoder renderPassEncoder, uint32_t reference) { __wasm_import_wgpuRenderPassEncoderSetStencilReference(renderPassEncoder, reference); }
void wgpuRenderPassEncoderSetVertexBuffer(WGPURenderPassEncoder renderPassEncoder, uint32_t slot, WGPU_NULLABLE WGPUBuffer buffer, uint64_t offset, uint64_t size) { __wasm_import_wgpuRenderPassEncoderSetVertexBuffer(renderPassEncoder, slot, buffer, offset, size); }
void wgpuRenderPassEncoderSetViewport(WGPURenderPassEncoder renderPassEncoder, float x, float y, float width, float height, float minDepth, float maxDepth) { __wasm_import_wgpuRenderPassEncoderSetViewport(renderPassEncoder, x, y, width, height, minDepth, maxDepth); }
void wgpuRenderPassEncoderWriteTimestamp(WGPURenderPassEncoder renderPassEncoder, WGPUQuerySet querySet, uint32_t queryIndex) { __wasm_import_wgpuRenderPassEncoderWriteTimestamp(renderPassEncoder, querySet, queryIndex); }
void wgpuRenderPassEncoderAddRef(WGPURenderPassEncoder renderPassEncoder) { __wasm_import_wgpuRenderPassEncoderAddRef(renderPassEncoder); }
void wgpuRenderPassEncoderRelease(WGPURenderPassEncoder renderPassEncoder) { __wasm_import_wgpuRenderPassEncoderRelease(renderPassEncoder); }
WGPUBindGroupLayout wgpuRenderPipelineGetBindGroupLayout(WGPURenderPipeline renderPipeline, uint32_t groupIndex) { return __wasm_import_wgpuRenderPipelineGetBindGroupLayout(renderPipeline, groupIndex); }
void wgpuRenderPipelineSetLabel(WGPURenderPipeline renderPipeline, WGPUStringView label) { __wasm_import_wgpuRenderPipelineSetLabel(renderPipeline, label); }
void wgpuRenderPipelineAddRef(WGPURenderPipeline renderPipeline) { __wasm_import_wgpuRenderPipelineAddRef(renderPipeline); }
void wgpuRenderPipelineRelease(WGPURenderPipeline renderPipeline) { __wasm_import_wgpuRenderPipelineRelease(renderPipeline); }
void wgpuResourceTableDestroy(WGPUResourceTable resourceTable) { __wasm_import_wgpuResourceTableDestroy(resourceTable); }
uint32_t wgpuResourceTableGetSize(WGPUResourceTable resourceTable) { return __wasm_import_wgpuResourceTableGetSize(resourceTable); }
uint32_t wgpuResourceTableInsertBinding(WGPUResourceTable resourceTable, WGPUBindingResource const * resource) { return __wasm_import_wgpuResourceTableInsertBinding(resourceTable, resource); }
WGPUStatus wgpuResourceTableRemoveBinding(WGPUResourceTable resourceTable, uint32_t slot) { return __wasm_import_wgpuResourceTableRemoveBinding(resourceTable, slot); }
WGPUStatus wgpuResourceTableUpdate(WGPUResourceTable resourceTable, uint32_t slot, WGPUBindingResource const * resource) { return __wasm_import_wgpuResourceTableUpdate(resourceTable, slot, resource); }
void wgpuResourceTableAddRef(WGPUResourceTable resourceTable) { __wasm_import_wgpuResourceTableAddRef(resourceTable); }
void wgpuResourceTableRelease(WGPUResourceTable resourceTable) { __wasm_import_wgpuResourceTableRelease(resourceTable); }
void wgpuSamplerSetLabel(WGPUSampler sampler, WGPUStringView label) { __wasm_import_wgpuSamplerSetLabel(sampler, label); }
void wgpuSamplerAddRef(WGPUSampler sampler) { __wasm_import_wgpuSamplerAddRef(sampler); }
void wgpuSamplerRelease(WGPUSampler sampler) { __wasm_import_wgpuSamplerRelease(sampler); }
WGPUFuture wgpuShaderModuleGetCompilationInfo(WGPUShaderModule shaderModule, WGPUCompilationInfoCallbackInfo callbackInfo) { return __wasm_import_wgpuShaderModuleGetCompilationInfo(shaderModule, callbackInfo); }
void wgpuShaderModuleSetLabel(WGPUShaderModule shaderModule, WGPUStringView label) { __wasm_import_wgpuShaderModuleSetLabel(shaderModule, label); }
void wgpuShaderModuleAddRef(WGPUShaderModule shaderModule) { __wasm_import_wgpuShaderModuleAddRef(shaderModule); }
void wgpuShaderModuleRelease(WGPUShaderModule shaderModule) { __wasm_import_wgpuShaderModuleRelease(shaderModule); }
WGPUStatus wgpuSharedBufferMemoryBeginAccess(WGPUSharedBufferMemory sharedBufferMemory, WGPUBuffer buffer, WGPUSharedBufferMemoryBeginAccessDescriptor const * descriptor) { return __wasm_import_wgpuSharedBufferMemoryBeginAccess(sharedBufferMemory, buffer, descriptor); }
WGPUBuffer wgpuSharedBufferMemoryCreateBuffer(WGPUSharedBufferMemory sharedBufferMemory, WGPU_NULLABLE WGPUBufferDescriptor const * descriptor) { return __wasm_import_wgpuSharedBufferMemoryCreateBuffer(sharedBufferMemory, descriptor); }
WGPUStatus wgpuSharedBufferMemoryEndAccess(WGPUSharedBufferMemory sharedBufferMemory, WGPUBuffer buffer, WGPUSharedBufferMemoryEndAccessState * descriptor) { return __wasm_import_wgpuSharedBufferMemoryEndAccess(sharedBufferMemory, buffer, descriptor); }
WGPUStatus wgpuSharedBufferMemoryGetProperties(WGPUSharedBufferMemory sharedBufferMemory, WGPUSharedBufferMemoryProperties * properties) { return __wasm_import_wgpuSharedBufferMemoryGetProperties(sharedBufferMemory, properties); }
WGPUBool wgpuSharedBufferMemoryIsDeviceLost(WGPUSharedBufferMemory sharedBufferMemory) { return __wasm_import_wgpuSharedBufferMemoryIsDeviceLost(sharedBufferMemory); }
void wgpuSharedBufferMemorySetLabel(WGPUSharedBufferMemory sharedBufferMemory, WGPUStringView label) { __wasm_import_wgpuSharedBufferMemorySetLabel(sharedBufferMemory, label); }
void wgpuSharedBufferMemoryAddRef(WGPUSharedBufferMemory sharedBufferMemory) { __wasm_import_wgpuSharedBufferMemoryAddRef(sharedBufferMemory); }
void wgpuSharedBufferMemoryRelease(WGPUSharedBufferMemory sharedBufferMemory) { __wasm_import_wgpuSharedBufferMemoryRelease(sharedBufferMemory); }
void wgpuSharedBufferMemoryEndAccessStateFreeMembers(WGPUSharedBufferMemoryEndAccessState sharedBufferMemoryEndAccessState) { __wasm_import_wgpuSharedBufferMemoryEndAccessStateFreeMembers(sharedBufferMemoryEndAccessState); }
void wgpuSharedFenceExportInfo(WGPUSharedFence sharedFence, WGPUSharedFenceExportInfo * info) { __wasm_import_wgpuSharedFenceExportInfo(sharedFence, info); }
void wgpuSharedFenceSetLabel(WGPUSharedFence sharedFence, WGPUStringView label) { __wasm_import_wgpuSharedFenceSetLabel(sharedFence, label); }
void wgpuSharedFenceAddRef(WGPUSharedFence sharedFence) { __wasm_import_wgpuSharedFenceAddRef(sharedFence); }
void wgpuSharedFenceRelease(WGPUSharedFence sharedFence) { __wasm_import_wgpuSharedFenceRelease(sharedFence); }
WGPUStatus wgpuSharedTextureMemoryBeginAccess(WGPUSharedTextureMemory sharedTextureMemory, WGPUTexture texture, WGPUSharedTextureMemoryBeginAccessDescriptor const * descriptor) { return __wasm_import_wgpuSharedTextureMemoryBeginAccess(sharedTextureMemory, texture, descriptor); }
WGPUTexture wgpuSharedTextureMemoryCreateTexture(WGPUSharedTextureMemory sharedTextureMemory, WGPU_NULLABLE WGPUTextureDescriptor const * descriptor) { return __wasm_import_wgpuSharedTextureMemoryCreateTexture(sharedTextureMemory, descriptor); }
WGPUStatus wgpuSharedTextureMemoryEndAccess(WGPUSharedTextureMemory sharedTextureMemory, WGPUTexture texture, WGPUSharedTextureMemoryEndAccessState * descriptor) { return __wasm_import_wgpuSharedTextureMemoryEndAccess(sharedTextureMemory, texture, descriptor); }
WGPUStatus wgpuSharedTextureMemoryGetProperties(WGPUSharedTextureMemory sharedTextureMemory, WGPUSharedTextureMemoryProperties * properties) { return __wasm_import_wgpuSharedTextureMemoryGetProperties(sharedTextureMemory, properties); }
WGPUBool wgpuSharedTextureMemoryIsDeviceLost(WGPUSharedTextureMemory sharedTextureMemory) { return __wasm_import_wgpuSharedTextureMemoryIsDeviceLost(sharedTextureMemory); }
void wgpuSharedTextureMemorySetLabel(WGPUSharedTextureMemory sharedTextureMemory, WGPUStringView label) { __wasm_import_wgpuSharedTextureMemorySetLabel(sharedTextureMemory, label); }
void wgpuSharedTextureMemoryAddRef(WGPUSharedTextureMemory sharedTextureMemory) { __wasm_import_wgpuSharedTextureMemoryAddRef(sharedTextureMemory); }
void wgpuSharedTextureMemoryRelease(WGPUSharedTextureMemory sharedTextureMemory) { __wasm_import_wgpuSharedTextureMemoryRelease(sharedTextureMemory); }
void wgpuSharedTextureMemoryEndAccessStateFreeMembers(WGPUSharedTextureMemoryEndAccessState sharedTextureMemoryEndAccessState) { __wasm_import_wgpuSharedTextureMemoryEndAccessStateFreeMembers(sharedTextureMemoryEndAccessState); }
void wgpuSupportedFeaturesFreeMembers(WGPUSupportedFeatures supportedFeatures) { __wasm_import_wgpuSupportedFeaturesFreeMembers(supportedFeatures); }
void wgpuSupportedInstanceFeaturesFreeMembers(WGPUSupportedInstanceFeatures supportedInstanceFeatures) { __wasm_import_wgpuSupportedInstanceFeaturesFreeMembers(supportedInstanceFeatures); }
void wgpuSupportedWGSLLanguageFeaturesFreeMembers(WGPUSupportedWGSLLanguageFeatures supportedWGSLLanguageFeatures) { __wasm_import_wgpuSupportedWGSLLanguageFeaturesFreeMembers(supportedWGSLLanguageFeatures); }
void wgpuSurfaceConfigure(WGPUSurface surface, WGPUSurfaceConfiguration const * config) { __wasm_import_wgpuSurfaceConfigure(surface, config); }
WGPUStatus wgpuSurfaceGetCapabilities(WGPUSurface surface, WGPUAdapter adapter, WGPUSurfaceCapabilities * capabilities) { return __wasm_import_wgpuSurfaceGetCapabilities(surface, adapter, capabilities); }
void wgpuSurfaceGetCurrentTexture(WGPUSurface surface, WGPUSurfaceTexture * surfaceTexture) { __wasm_import_wgpuSurfaceGetCurrentTexture(surface, surfaceTexture); }
WGPUStatus wgpuSurfacePresent(WGPUSurface surface) { return __wasm_import_wgpuSurfacePresent(surface); }
void wgpuSurfaceSetLabel(WGPUSurface surface, WGPUStringView label) { __wasm_import_wgpuSurfaceSetLabel(surface, label); }
void wgpuSurfaceUnconfigure(WGPUSurface surface) { __wasm_import_wgpuSurfaceUnconfigure(surface); }
void wgpuSurfaceAddRef(WGPUSurface surface) { __wasm_import_wgpuSurfaceAddRef(surface); }
void wgpuSurfaceRelease(WGPUSurface surface) { __wasm_import_wgpuSurfaceRelease(surface); }
void wgpuSurfaceCapabilitiesFreeMembers(WGPUSurfaceCapabilities surfaceCapabilities) { __wasm_import_wgpuSurfaceCapabilitiesFreeMembers(surfaceCapabilities); }
void wgpuTexelBufferViewSetLabel(WGPUTexelBufferView texelBufferView, WGPUStringView label) { __wasm_import_wgpuTexelBufferViewSetLabel(texelBufferView, label); }
void wgpuTexelBufferViewAddRef(WGPUTexelBufferView texelBufferView) { __wasm_import_wgpuTexelBufferViewAddRef(texelBufferView); }
void wgpuTexelBufferViewRelease(WGPUTexelBufferView texelBufferView) { __wasm_import_wgpuTexelBufferViewRelease(texelBufferView); }
WGPUTextureView wgpuTextureCreateErrorView(WGPUTexture texture, WGPU_NULLABLE WGPUTextureViewDescriptor const * descriptor) { return __wasm_import_wgpuTextureCreateErrorView(texture, descriptor); }
WGPUTextureView wgpuTextureCreateView(WGPUTexture texture, WGPU_NULLABLE WGPUTextureViewDescriptor const * descriptor) { return __wasm_import_wgpuTextureCreateView(texture, descriptor); }
void wgpuTextureDestroy(WGPUTexture texture) { __wasm_import_wgpuTextureDestroy(texture); }
uint32_t wgpuTextureGetDepthOrArrayLayers(WGPUTexture texture) { return __wasm_import_wgpuTextureGetDepthOrArrayLayers(texture); }
WGPUTextureDimension wgpuTextureGetDimension(WGPUTexture texture) { return __wasm_import_wgpuTextureGetDimension(texture); }
WGPUTextureFormat wgpuTextureGetFormat(WGPUTexture texture) { return __wasm_import_wgpuTextureGetFormat(texture); }
uint32_t wgpuTextureGetHeight(WGPUTexture texture) { return __wasm_import_wgpuTextureGetHeight(texture); }
uint32_t wgpuTextureGetMipLevelCount(WGPUTexture texture) { return __wasm_import_wgpuTextureGetMipLevelCount(texture); }
uint32_t wgpuTextureGetSampleCount(WGPUTexture texture) { return __wasm_import_wgpuTextureGetSampleCount(texture); }
WGPUTextureViewDimension wgpuTextureGetTextureBindingViewDimension(WGPUTexture texture) { return __wasm_import_wgpuTextureGetTextureBindingViewDimension(texture); }
WGPUTextureUsage wgpuTextureGetUsage(WGPUTexture texture) { return __wasm_import_wgpuTextureGetUsage(texture); }
uint32_t wgpuTextureGetWidth(WGPUTexture texture) { return __wasm_import_wgpuTextureGetWidth(texture); }
void wgpuTexturePin(WGPUTexture texture, WGPUTextureUsage usage) { __wasm_import_wgpuTexturePin(texture, usage); }
void wgpuTextureSetLabel(WGPUTexture texture, WGPUStringView label) { __wasm_import_wgpuTextureSetLabel(texture, label); }
void wgpuTextureSetOwnershipForMemoryDump(WGPUTexture texture, uint64_t ownerGuid) { __wasm_import_wgpuTextureSetOwnershipForMemoryDump(texture, ownerGuid); }
void wgpuTextureUnpin(WGPUTexture texture) { __wasm_import_wgpuTextureUnpin(texture); }
void wgpuTextureAddRef(WGPUTexture texture) { __wasm_import_wgpuTextureAddRef(texture); }
void wgpuTextureRelease(WGPUTexture texture) { __wasm_import_wgpuTextureRelease(texture); }
void wgpuTextureViewSetLabel(WGPUTextureView textureView, WGPUStringView label) { __wasm_import_wgpuTextureViewSetLabel(textureView, label); }
void wgpuTextureViewAddRef(WGPUTextureView textureView) { __wasm_import_wgpuTextureViewAddRef(textureView); }
void wgpuTextureViewRelease(WGPUTextureView textureView) { __wasm_import_wgpuTextureViewRelease(textureView); }
