/**
 * WASM loader for the Skia WebGPU (Dawn/Graphite) variant.
 *
 * Instantiates skia-wgpu.wasm with:
 *   - "wgpu" module: WebGPU C API function imports
 *   - "env" module: Skia runtime stubs (logging, semaphores)
 *   - "wasi_snapshot_preview1" module: minimal WASI stubs
 *
 * Struct offsets are imported from wgpu-layouts.json (generated by
 * emit_wgpu_layouts.zig using Zig comptime @offsetOf — provably correct).
 * Enum maps are imported from wgpu-enums.generated.ts (generated from
 * Dawn's webgpu.h by generate-wgpu-bridge.py).
 *
 * @internal
 */

import { createEnvImports, createWasiImports, instantiateWasm } from './wasm-loader-shared'
import W from './wgpu-layouts.json'
import {
  WGPUAddressMode,
  WGPUBlendFactor,
  WGPUBlendOperation,
  WGPUBufferBindingType,
  WGPUCompareFunction,
  WGPUCullMode,
  WGPUFeatureName,
  WGPUFilterMode,
  WGPUFrontFace,
  WGPUIndexFormat,
  WGPULoadOp,
  WGPUMipmapFilterMode,
  WGPUPrimitiveTopology,
  WGPUSamplerBindingType,
  WGPUStencilOperation,
  WGPUStoreOp,
  WGPUStorageTextureAccess,
  WGPUTextureAspect,
  WGPUTextureDimension,
  WGPUTextureFormat,
  WGPUTextureSampleType,
  WGPUTextureViewDimension,
  WGPUVertexFormat,
  WGPUVertexStepMode,
} from './wgpu-enums.generated'

// ── WebGPU object handle tables ──

interface PendingCallback {
  futureId: bigint
  invoke: () => void
}

interface BufferMapping {
  buffer: GPUBuffer
  jsArrayBuffer: ArrayBuffer
  wasmPtr: number
  offset: number
  size: number
}

interface WGPUState {
  device: GPUDevice
  queue: GPUQueue
  memory: WebAssembly.Memory
  objects: Map<number, unknown>
  refCounts: Map<number, number>
  nextHandle: number
  reverseMap: WeakMap<object, number>
  deviceHandle: number
  queueHandle: number
  // Buffer mapping: buffer handle → active mapping info
  mappings: Map<number, BufferMapping>
  // Pending async callbacks (future ID → callback)
  pendingCallbacks: Map<bigint, PendingCallback>
  nextFutureId: bigint
  // WASM exports for memory allocation and function calls
  malloc: ((size: number) => number) | null
  free: ((ptr: number) => void) | null
  table: WebAssembly.Table | null
  // Pre-allocated empty WGPUStringView {data=0, length=0} for callback messages
  emptyStringViewPtr: number
  // View → Texture parent mapping (for compositing — find what texture a view belongs to)
  viewToTexture: Map<number, GPUTexture>
  // Last render pass color target texture (for compositing)
  lastRenderTargetTexture: GPUTexture | null
}

function createWGPUState(device: GPUDevice): WGPUState {
  const state: WGPUState = {
    device,
    queue: device.queue,
    memory: null!,
    objects: new Map(),
    refCounts: new Map(),
    nextHandle: 1,
    reverseMap: new WeakMap(),
    deviceHandle: 0,
    queueHandle: 0,
    mappings: new Map(),
    pendingCallbacks: new Map(),
    nextFutureId: 1n,
    malloc: null,
    free: null,
    table: null,
    emptyStringViewPtr: 0,
    viewToTexture: new Map(),
    lastRenderTargetTexture: null,
  }
  state.deviceHandle = registerObject(state, device)
  state.queueHandle = registerObject(state, state.queue)
  return state
}

function registerObject(state: WGPUState, obj: unknown): number {
  const handle = state.nextHandle++
  state.objects.set(handle, obj)
  state.refCounts.set(handle, 1)
  if (obj && typeof obj === 'object') {
    state.reverseMap.set(obj, handle)
  }
  return handle
}

function addRefObject(state: WGPUState, handle: number): void {
  const rc = state.refCounts.get(handle)
  if (rc !== undefined) state.refCounts.set(handle, rc + 1)
}

function getObject<T>(state: WGPUState, handle: number): T | null {
  return (state.objects.get(handle) as T) ?? null
}

function releaseObject(state: WGPUState, handle: number): void {
  const rc = state.refCounts.get(handle)
  if (rc === undefined) return
  if (rc > 1) {
    state.refCounts.set(handle, rc - 1)
    return
  }
  const obj = state.objects.get(handle)
  if (obj && typeof obj === 'object') {
    state.reverseMap.delete(obj)
  }
  state.objects.delete(handle)
  state.refCounts.delete(handle)
}

// ── Memory helpers ──

function readU32(state: WGPUState, ptr: number): number {
  return new Uint32Array(state.memory.buffer, ptr, 1)[0]!
}

function readU64(state: WGPUState, ptr: number): bigint {
  return new BigUint64Array(state.memory.buffer, ptr, 1)[0]!
}

function readI32(state: WGPUState, ptr: number): number {
  return new Int32Array(state.memory.buffer, ptr, 1)[0]!
}

function readF32(state: WGPUState, ptr: number): number {
  return new Float32Array(state.memory.buffer, ptr, 1)[0]!
}

function readF64(state: WGPUState, ptr: number): number {
  return new Float64Array(state.memory.buffer, ptr, 1)[0]!
}

function writeU32(state: WGPUState, ptr: number, value: number): void {
  new Uint32Array(state.memory.buffer, ptr, 1)[0] = value
}

function writeU64(state: WGPUState, ptr: number, value: bigint): void {
  new BigUint64Array(state.memory.buffer, ptr, 1)[0] = value
}

// WGPU_WHOLE_SIZE = UINT64_MAX — means "use the whole buffer"
const WGPU_WHOLE_SIZE = 0xFFFFFFFFFFFFFFFFn
// Dawn uses UINT32_MAX as "undefined" sentinel for counts and strides
const u32OrUndef = (v: number) => v === 0xFFFFFFFF ? undefined : v

function readStringView(state: WGPUState, ptr: number): string {
  const dataPtr = readU32(state, ptr)
  if (dataPtr === 0) return ''
  const length = readU32(state, ptr + 4)
  if (length === 0xFFFFFFFF) {
    const mem = new Uint8Array(state.memory.buffer)
    let end = dataPtr
    while (mem[end] !== 0) end++
    if (end === dataPtr) return ''
    return new TextDecoder().decode(mem.subarray(dataPtr, end))
  }
  if (length === 0) return ''
  return new TextDecoder().decode(new Uint8Array(state.memory.buffer, dataPtr, length))
}

// ── Field reader: reads a value from WASM memory at base + layout.offset ──

type LayoutField = { readonly offset: number; readonly size: number; readonly type: string }

function field(state: WGPUState, base: number, f: LayoutField): number {
  const addr = base + f.offset
  switch (f.type) {
    case 'ptr': return readU32(state, addr)
    case 'u32': return readU32(state, addr)
    case 'i32': return readI32(state, addr)
    case 'u16': return new Uint16Array(state.memory.buffer, addr, 1)[0]!
    case 'f32': return readF32(state, addr)
    case 'f64': return readF64(state, addr)
    case 'u64': return Number(readU64(state, addr))
    default: return readU32(state, addr)
  }
}

function fieldU64(state: WGPUState, base: number, f: LayoutField): bigint {
  return readU64(state, base + f.offset)
}

// ── Enum lookup helper ──

function enumStr<T>(map: Record<number, string>, value: number): T {
  return (map[value] ?? map[1]) as T
}

// ── WebGPU imports ──

function createWGPUImports(state: WGPUState): Record<string, WebAssembly.ImportValue> {
  const { device, queue } = state
  const noop = (..._args: unknown[]) => 0

  // Layout aliases for frequently used structs
  const L = {
    buf: W.WGPUBufferDescriptor.fields,
    tex: W.WGPUTextureDescriptor.fields,
    sampler: W.WGPUSamplerDescriptor.fields,
    bglDesc: W.WGPUBindGroupLayoutDescriptor.fields,
    bglEntry: W.WGPUBindGroupLayoutEntry.fields,
    bufBind: W.WGPUBufferBindingLayout.fields,
    samplerBind: W.WGPUSamplerBindingLayout.fields,
    texBind: W.WGPUTextureBindingLayout.fields,
    storageBind: W.WGPUStorageTextureBindingLayout.fields,
    bgDesc: W.WGPUBindGroupDescriptor.fields,
    bgEntry: W.WGPUBindGroupEntry.fields,
    plDesc: W.WGPUPipelineLayoutDescriptor.fields,
    rpDesc: W.WGPURenderPipelineDescriptor.fields,
    vtxState: W.WGPUVertexState.fields,
    fragState: W.WGPUFragmentState.fields,
    primState: W.WGPUPrimitiveState.fields,
    msState: W.WGPUMultisampleState.fields,
    dsState: W.WGPUDepthStencilState.fields,
    stencilFace: W.WGPUStencilFaceState.fields,
    colorTarget: W.WGPUColorTargetState.fields,
    blend: W.WGPUBlendState.fields,
    vtxAttr: W.WGPUVertexAttribute.fields,
    vtxBuf: W.WGPUVertexBufferLayout.fields,
    rpPassDesc: W.WGPURenderPassDescriptor.fields,
    rpColor: W.WGPURenderPassColorAttachment.fields,
    rpDepth: W.WGPURenderPassDepthStencilAttachment.fields,
    cpDesc: W.WGPUComputePipelineDescriptor.fields,
    compState: W.WGPUComputeState.fields,
    copyBuf: W.WGPUTexelCopyBufferInfo.fields,
    copyBufLayout: W.WGPUTexelCopyBufferLayout.fields,
    copyTex: W.WGPUTexelCopyTextureInfo.fields,
    queryDesc: W.WGPUQuerySetDescriptor.fields,
    wgslSrc: W.WGPUShaderSourceWGSL.fields,
  }

  const impl: Record<string, WebAssembly.ImportValue> = {
    // ── Instance ──
    wgpuCreateInstance: noop,
    wgpuGetInstanceFeatures: noop,
    wgpuGetInstanceLimits: noop,
    wgpuHasInstanceFeature: noop,
    wgpuGetProcAddress: noop,

    // ── Adapter ──
    wgpuAdapterCreateDevice: noop,
    wgpuAdapterGetFeatures: noop,
    wgpuAdapterGetFormatCapabilities: noop,
    wgpuAdapterGetInfo: noop,
    wgpuAdapterGetInstance: noop,
    wgpuAdapterGetLimits: noop,
    wgpuAdapterHasFeature: noop,
    wgpuAdapterRequestDevice: noop,
    wgpuAdapterAddRef(handle: number) { addRefObject(state, handle) },
    wgpuAdapterRelease: noop,

    // ── Device: Resource Creation ──

    wgpuDeviceCreateBuffer(deviceHandle: number, ptr: number): number {
      const dev = getObject<GPUDevice>(state, deviceHandle)
      if (!dev) return 0
      const size = Number(fieldU64(state, ptr, L.buf.size))
      const usage = Number(fieldU64(state, ptr, L.buf.usage))
      const mappedAtCreation = field(state, ptr, L.buf.mappedAtCreation) !== 0
      return registerObject(state, dev.createBuffer({ size, usage, mappedAtCreation }))
    },

    wgpuDeviceCreateTexture(deviceHandle: number, ptr: number): number {
      const dev = getObject<GPUDevice>(state, deviceHandle)
      if (!dev) return 0
      const usage = Number(fieldU64(state, ptr, L.tex.usage))
      const dimension = field(state, ptr, L.tex.dimension)
      const sizeBase = ptr + L.tex.size.offset
      const width = readU32(state, sizeBase)
      const height = readU32(state, sizeBase + 4)
      const depthOrArrayLayers = readU32(state, sizeBase + 8)
      let format = enumStr<GPUTextureFormat>(WGPUTextureFormat, field(state, ptr, L.tex.format))
      const mipLevelCount = field(state, ptr, L.tex.mipLevelCount)
      const sampleCount = field(state, ptr, L.tex.sampleCount)
      // Ensure all textures have COPY_SRC | COPY_DST for compositing
      const actualUsage = usage | GPUTextureUsage.COPY_SRC | GPUTextureUsage.COPY_DST
      return registerObject(state, dev.createTexture({
        usage: actualUsage,
        dimension: enumStr<GPUTextureDimension>(WGPUTextureDimension, dimension),
        size: { width, height, depthOrArrayLayers },
        mipLevelCount,
        sampleCount,
        format,
      }))
    },

    wgpuDeviceCreateShaderModule(deviceHandle: number, descriptorPtr: number): number {
      const dev = getObject<GPUDevice>(state, deviceHandle)
      if (!dev) return 0
      const nextInChainPtr = readU32(state, descriptorPtr)
      if (nextInChainPtr === 0) return 0
      // WGPUShaderSourceWGSL: chain(8 bytes), code(WGPUStringView at offset 8)
      const code = readStringView(state, nextInChainPtr + L.wgslSrc.code.offset)
      if (!code) return 0
      return registerObject(state, dev.createShaderModule({ code }))
    },

    wgpuDeviceCreateSampler(deviceHandle: number, ptr: number): number {
      const dev = getObject<GPUDevice>(state, deviceHandle)
      if (!dev) return 0
      const compareVal = field(state, ptr, L.sampler.compare)
      const desc: GPUSamplerDescriptor = {
        addressModeU: enumStr(WGPUAddressMode, field(state, ptr, L.sampler.addressModeU)),
        addressModeV: enumStr(WGPUAddressMode, field(state, ptr, L.sampler.addressModeV)),
        addressModeW: enumStr(WGPUAddressMode, field(state, ptr, L.sampler.addressModeW)),
        magFilter: enumStr(WGPUFilterMode, field(state, ptr, L.sampler.magFilter)),
        minFilter: enumStr(WGPUFilterMode, field(state, ptr, L.sampler.minFilter)),
        mipmapFilter: enumStr(WGPUMipmapFilterMode, field(state, ptr, L.sampler.mipmapFilter)),
        lodMinClamp: field(state, ptr, L.sampler.lodMinClamp),
        lodMaxClamp: field(state, ptr, L.sampler.lodMaxClamp),
        maxAnisotropy: field(state, ptr, L.sampler.maxAnisotropy),
      }
      // compare=0 means undefined/not set
      if (compareVal !== 0) {
        desc.compare = enumStr(WGPUCompareFunction, compareVal)
      }
      return registerObject(state, dev.createSampler(desc))
    },

    wgpuDeviceCreateBindGroupLayout(deviceHandle: number, ptr: number): number {
      const dev = getObject<GPUDevice>(state, deviceHandle)
      if (!dev) return 0
      const entryCount = field(state, ptr, L.bglDesc.entryCount)
      const entriesPtr = field(state, ptr, L.bglDesc.entries)
      const stride = W.WGPUBindGroupLayoutEntry._size
      const entries: GPUBindGroupLayoutEntry[] = []

      for (let i = 0; i < entryCount; i++) {
        const e = entriesPtr + i * stride
        const entry: GPUBindGroupLayoutEntry = {
          binding: field(state, e, L.bglEntry.binding),
          visibility: Number(fieldU64(state, e, L.bglEntry.visibility)),
        }

        // Buffer binding
        const bufBase = e + L.bglEntry.buffer.offset
        const bufType = field(state, bufBase, L.bufBind.type)
        if (bufType > 1) { // >1 means not Undefined (0 or 1)
          entry.buffer = {
            type: enumStr(WGPUBufferBindingType, bufType),
            hasDynamicOffset: field(state, bufBase, L.bufBind.hasDynamicOffset) !== 0,
            minBindingSize: Number(fieldU64(state, bufBase, L.bufBind.minBindingSize)),
          }
        }

        // Sampler binding
        const samplerBase = e + L.bglEntry.sampler.offset
        const samplerType = field(state, samplerBase, L.samplerBind.type)
        if (samplerType > 1) {
          entry.sampler = { type: enumStr(WGPUSamplerBindingType, samplerType) }
        }

        // Texture binding
        const texBase = e + L.bglEntry.texture.offset
        const texSampleType = field(state, texBase, L.texBind.sampleType)
        if (texSampleType > 1) {
          entry.texture = {
            sampleType: enumStr(WGPUTextureSampleType, texSampleType),
            viewDimension: enumStr(WGPUTextureViewDimension, field(state, texBase, L.texBind.viewDimension)),
            multisampled: field(state, texBase, L.texBind.multisampled) !== 0,
          }
        }

        // Storage texture binding
        const stBase = e + L.bglEntry.storageTexture.offset
        const stAccess = field(state, stBase, L.storageBind.access)
        if (stAccess > 1) {
          entry.storageTexture = {
            access: enumStr(WGPUStorageTextureAccess, stAccess),
            format: enumStr(WGPUTextureFormat, field(state, stBase, L.storageBind.format)),
            viewDimension: enumStr(WGPUTextureViewDimension, field(state, stBase, L.storageBind.viewDimension)),
          }
        }

        entries.push(entry)
      }

      return registerObject(state, dev.createBindGroupLayout({ entries }))
    },

    wgpuDeviceCreateBindGroup(deviceHandle: number, ptr: number): number {
      const dev = getObject<GPUDevice>(state, deviceHandle)
      if (!dev) return 0
      const layoutHandle = field(state, ptr, L.bgDesc.layout)
      const layout = getObject<GPUBindGroupLayout>(state, layoutHandle)
      if (!layout) return 0
      const entryCount = field(state, ptr, L.bgDesc.entryCount)
      const entriesPtr = field(state, ptr, L.bgDesc.entries)
      const stride = W.WGPUBindGroupEntry._size
      const entries: GPUBindGroupEntry[] = []

      for (let i = 0; i < entryCount; i++) {
        const e = entriesPtr + i * stride
        const binding = field(state, e, L.bgEntry.binding)
        const bufferHandle = field(state, e, L.bgEntry.buffer)
        const samplerHandle = field(state, e, L.bgEntry.sampler)
        const textureViewHandle = field(state, e, L.bgEntry.textureView)

        const buffer = bufferHandle ? getObject<GPUBuffer>(state, bufferHandle) : null
        const sampler = samplerHandle ? getObject<GPUSampler>(state, samplerHandle) : null
        const textureView = textureViewHandle ? getObject<GPUTextureView>(state, textureViewHandle) : null

        if (buffer) {
          const offset = Number(fieldU64(state, e, L.bgEntry.offset))
          const rawSize = fieldU64(state, e, L.bgEntry.size)
          const size = rawSize === WGPU_WHOLE_SIZE ? undefined : Number(rawSize)
          entries.push({ binding, resource: { buffer, offset, size } })
        } else if (sampler) {
          entries.push({ binding, resource: sampler })
        } else if (textureView) {
          entries.push({ binding, resource: textureView })
        } else {
          console.warn(`[wgpu] createBindGroup entry ${i}: no valid resource (buf=${bufferHandle} sam=${samplerHandle} tv=${textureViewHandle})`)
        }
      }

      return registerObject(state, dev.createBindGroup({ layout, entries }))
    },

    wgpuDeviceCreatePipelineLayout(deviceHandle: number, ptr: number): number {
      const dev = getObject<GPUDevice>(state, deviceHandle)
      if (!dev) return 0
      const count = field(state, ptr, L.plDesc.bindGroupLayoutCount)
      const layoutsPtr = field(state, ptr, L.plDesc.bindGroupLayouts)
      const bindGroupLayouts: GPUBindGroupLayout[] = []
      for (let i = 0; i < count; i++) {
        const handle = readU32(state, layoutsPtr + i * 4)
        const bgl = getObject<GPUBindGroupLayout>(state, handle)
        if (bgl) bindGroupLayouts.push(bgl)
      }
      return registerObject(state, dev.createPipelineLayout({ bindGroupLayouts }))
    },

    wgpuDeviceCreateRenderPipeline(deviceHandle: number, ptr: number): number {
      const dev = getObject<GPUDevice>(state, deviceHandle)
      if (!dev) return 0

      // Layout (optional — 0 means auto)
      const layoutHandle = field(state, ptr, L.rpDesc.layout)
      const layout: GPUPipelineLayout | 'auto' = layoutHandle
        ? getObject<GPUPipelineLayout>(state, layoutHandle) ?? 'auto'
        : 'auto'

      // Vertex state (inline at rpDesc.vertex.offset)
      const vBase = ptr + L.rpDesc.vertex.offset
      const vertexModule = getObject<GPUShaderModule>(state, field(state, vBase, L.vtxState.module))
      if (!vertexModule) return 0
      const vertexEntryPoint = readStringView(state, vBase + L.vtxState.entryPoint.offset)

      // Vertex buffers
      const vtxBufCount = field(state, vBase, L.vtxState.bufferCount)
      const vtxBufsPtr = field(state, vBase, L.vtxState.buffers)
      const buffers: GPUVertexBufferLayout[] = []
      for (let i = 0; i < vtxBufCount; i++) {
        const b = vtxBufsPtr + i * W.WGPUVertexBufferLayout._size
        const stepModeVal = field(state, b, L.vtxBuf.stepMode)
        // stepMode 0 = VertexBufferNotUsed (Emscripten sentinel) — skip this slot
        if (stepModeVal === 0) {
          buffers.push(null as unknown as GPUVertexBufferLayout)
          continue
        }
        const attrCount = field(state, b, L.vtxBuf.attributeCount)
        const attrsPtr = field(state, b, L.vtxBuf.attributes)
        const attributes: GPUVertexAttribute[] = []
        for (let j = 0; j < attrCount; j++) {
          const a = attrsPtr + j * W.WGPUVertexAttribute._size
          attributes.push({
            format: enumStr<GPUVertexFormat>(WGPUVertexFormat, field(state, a, L.vtxAttr.format)),
            offset: Number(fieldU64(state, a, L.vtxAttr.offset)),
            shaderLocation: field(state, a, L.vtxAttr.shaderLocation),
          })
        }
        buffers.push({
          arrayStride: Number(fieldU64(state, b, L.vtxBuf.arrayStride)),
          stepMode: enumStr<GPUVertexStepMode>(WGPUVertexStepMode, stepModeVal),
          attributes,
        })
      }

      // Primitive state (inline)
      const pBase = ptr + L.rpDesc.primitive.offset
      const primitive: GPUPrimitiveState = {
        topology: enumStr(WGPUPrimitiveTopology, field(state, pBase, L.primState.topology)),
        frontFace: enumStr(WGPUFrontFace, field(state, pBase, L.primState.frontFace)),
        cullMode: enumStr(WGPUCullMode, field(state, pBase, L.primState.cullMode)),
      }
      const stripFmt = field(state, pBase, L.primState.stripIndexFormat)
      if (stripFmt !== 0) {
        primitive.stripIndexFormat = enumStr(WGPUIndexFormat, stripFmt)
      }

      // Depth/stencil (optional pointer)
      const dsPtr = field(state, ptr, L.rpDesc.depthStencil)
      let depthStencil: GPUDepthStencilState | undefined
      if (dsPtr) {
        const readStencilFace = (base: number): GPUStencilFaceState => ({
          compare: enumStr(WGPUCompareFunction, field(state, base, L.stencilFace.compare)),
          failOp: enumStr(WGPUStencilOperation, field(state, base, L.stencilFace.failOp)),
          depthFailOp: enumStr(WGPUStencilOperation, field(state, base, L.stencilFace.depthFailOp)),
          passOp: enumStr(WGPUStencilOperation, field(state, base, L.stencilFace.passOp)),
        })
        const dsFormat = enumStr<GPUTextureFormat>(WGPUTextureFormat, field(state, dsPtr, L.dsState.format))
        let stencilFront = readStencilFace(dsPtr + L.dsState.stencilFront.offset)
        let stencilBack = readStencilFace(dsPtr + L.dsState.stencilBack.offset)
        // Graphite uses compare='never' to mean "don't use stencil." On native Dawn with
        // depth-only formats this is fine (no stencil aspect). But browser WebGPU may use
        // depth24plus-stencil8 which HAS stencil — 'never' rejects all fragments.
        // Override to 'always' (passthrough) so depth works without stencil interference.
        if (dsFormat.includes('stencil')) {
          const pass: GPUStencilFaceState = { compare: 'always', failOp: 'keep', depthFailOp: 'keep', passOp: 'keep' }
          if (stencilFront.compare === 'never') stencilFront = pass
          if (stencilBack.compare === 'never') stencilBack = pass
        }
        depthStencil = {
          format: dsFormat,
          depthWriteEnabled: field(state, dsPtr, L.dsState.depthWriteEnabled) === 1,
          depthCompare: enumStr(WGPUCompareFunction, field(state, dsPtr, L.dsState.depthCompare)),
          stencilFront,
          stencilBack,
          stencilReadMask: field(state, dsPtr, L.dsState.stencilReadMask),
          stencilWriteMask: field(state, dsPtr, L.dsState.stencilWriteMask),
          depthBias: field(state, dsPtr, L.dsState.depthBias),
          depthBiasSlopeScale: field(state, dsPtr, L.dsState.depthBiasSlopeScale),
          depthBiasClamp: field(state, dsPtr, L.dsState.depthBiasClamp),
        }
      }

      // Multisample (inline)
      const msBase = ptr + L.rpDesc.multisample.offset
      const multisample: GPUMultisampleState = {
        count: field(state, msBase, L.msState.count),
        mask: field(state, msBase, L.msState.mask),
        alphaToCoverageEnabled: field(state, msBase, L.msState.alphaToCoverageEnabled) !== 0,
      }

      // Fragment state (optional pointer)
      const fragPtr = field(state, ptr, L.rpDesc.fragment)
      let fragment: GPUFragmentState | undefined
      if (fragPtr) {
        const fragModule = getObject<GPUShaderModule>(state, field(state, fragPtr, L.fragState.module))
        if (fragModule) {
          const fragEntryPoint = readStringView(state, fragPtr + L.fragState.entryPoint.offset)
          const targetCount = field(state, fragPtr, L.fragState.targetCount)
          const targetsPtr = field(state, fragPtr, L.fragState.targets)
          const targets: GPUColorTargetState[] = []
          for (let i = 0; i < targetCount; i++) {
            const t = targetsPtr + i * W.WGPUColorTargetState._size
            const target: GPUColorTargetState = {
              format: enumStr(WGPUTextureFormat, field(state, t, L.colorTarget.format)),
              writeMask: Number(fieldU64(state, t, L.colorTarget.writeMask)),
            }
            const blendPtr = field(state, t, L.colorTarget.blend)
            if (blendPtr) {
              const readBlendComponent = (base: number): GPUBlendComponent => ({
                operation: enumStr(WGPUBlendOperation, readU32(state, base)),
                srcFactor: enumStr(WGPUBlendFactor, readU32(state, base + 4)),
                dstFactor: enumStr(WGPUBlendFactor, readU32(state, base + 8)),
              })
              target.blend = {
                color: readBlendComponent(blendPtr + L.blend.color.offset),
                alpha: readBlendComponent(blendPtr + L.blend.alpha.offset),
              }
            }
            targets.push(target)
          }
          fragment = {
            module: fragModule,
            entryPoint: fragEntryPoint || undefined,
            targets,
          }
        }
      }

      const desc = {
        layout,
        vertex: {
          module: vertexModule,
          entryPoint: vertexEntryPoint || undefined,
          buffers,
        },
        primitive,
        depthStencil,
        multisample,
        fragment,
      }
      const pipeline = dev.createRenderPipeline(desc)
      return registerObject(state, pipeline)
    },

    wgpuDeviceCreateRenderPipelineAsync(_deviceHandle: number, _descriptorPtr: number, _callbackInfo: number): bigint {
      return 0n
    },

    wgpuDeviceCreateComputePipeline(deviceHandle: number, ptr: number): number {
      const dev = getObject<GPUDevice>(state, deviceHandle)
      if (!dev) return 0
      const layoutHandle = field(state, ptr, L.cpDesc.layout)
      const layout: GPUPipelineLayout | 'auto' = layoutHandle
        ? getObject<GPUPipelineLayout>(state, layoutHandle) ?? 'auto'
        : 'auto'
      const compBase = ptr + L.cpDesc.compute.offset
      const module = getObject<GPUShaderModule>(state, field(state, compBase, L.compState.module))
      if (!module) return 0
      const entryPoint = readStringView(state, compBase + L.compState.entryPoint.offset)
      return registerObject(state, dev.createComputePipeline({
        layout,
        compute: { module, entryPoint: entryPoint || undefined },
      }))
    },

    wgpuDeviceCreateQuerySet(deviceHandle: number, ptr: number): number {
      const dev = getObject<GPUDevice>(state, deviceHandle)
      if (!dev) return 0
      return registerObject(state, dev.createQuerySet({
        type: enumStr(WGPUTextureFormat, field(state, ptr, L.queryDesc.type)) as GPUQueryType,
        count: field(state, ptr, L.queryDesc.count),
      }))
    },

    wgpuDeviceCreateCommandEncoder(deviceHandle: number, _descriptorPtr: number): number {
      const dev = getObject<GPUDevice>(state, deviceHandle)
      if (!dev) return 0
      return registerObject(state, dev.createCommandEncoder())
    },

    wgpuDeviceGetLimits(_deviceHandle: number, limitsPtr: number): number {
      const lim = device.limits
      const F = W.WGPULimits.fields
      // Write all limit fields into WASM memory at the given pointer
      writeU32(state, limitsPtr + F.maxTextureDimension1D.offset, lim.maxTextureDimension1D)
      writeU32(state, limitsPtr + F.maxTextureDimension2D.offset, lim.maxTextureDimension2D)
      writeU32(state, limitsPtr + F.maxTextureDimension3D.offset, lim.maxTextureDimension3D)
      writeU32(state, limitsPtr + F.maxTextureArrayLayers.offset, lim.maxTextureArrayLayers)
      writeU32(state, limitsPtr + F.maxBindGroups.offset, lim.maxBindGroups)
      writeU32(state, limitsPtr + F.maxBindGroupsPlusVertexBuffers.offset, lim.maxBindGroupsPlusVertexBuffers ?? 24)
      writeU32(state, limitsPtr + F.maxBindingsPerBindGroup.offset, lim.maxBindingsPerBindGroup)
      writeU32(state, limitsPtr + F.maxDynamicUniformBuffersPerPipelineLayout.offset, lim.maxDynamicUniformBuffersPerPipelineLayout)
      writeU32(state, limitsPtr + F.maxDynamicStorageBuffersPerPipelineLayout.offset, lim.maxDynamicStorageBuffersPerPipelineLayout)
      writeU32(state, limitsPtr + F.maxSampledTexturesPerShaderStage.offset, lim.maxSampledTexturesPerShaderStage)
      writeU32(state, limitsPtr + F.maxSamplersPerShaderStage.offset, lim.maxSamplersPerShaderStage)
      writeU32(state, limitsPtr + F.maxStorageBuffersPerShaderStage.offset, lim.maxStorageBuffersPerShaderStage)
      writeU32(state, limitsPtr + F.maxStorageTexturesPerShaderStage.offset, lim.maxStorageTexturesPerShaderStage)
      writeU32(state, limitsPtr + F.maxUniformBuffersPerShaderStage.offset, lim.maxUniformBuffersPerShaderStage)
      writeU64(state, limitsPtr + F.maxUniformBufferBindingSize.offset, BigInt(lim.maxUniformBufferBindingSize))
      writeU64(state, limitsPtr + F.maxStorageBufferBindingSize.offset, BigInt(lim.maxStorageBufferBindingSize))
      writeU32(state, limitsPtr + F.minUniformBufferOffsetAlignment.offset, lim.minUniformBufferOffsetAlignment)
      writeU32(state, limitsPtr + F.minStorageBufferOffsetAlignment.offset, lim.minStorageBufferOffsetAlignment)
      writeU32(state, limitsPtr + F.maxVertexBuffers.offset, lim.maxVertexBuffers)
      writeU64(state, limitsPtr + F.maxBufferSize.offset, BigInt(lim.maxBufferSize))
      writeU32(state, limitsPtr + F.maxVertexAttributes.offset, lim.maxVertexAttributes)
      writeU32(state, limitsPtr + F.maxVertexBufferArrayStride.offset, lim.maxVertexBufferArrayStride)
      writeU32(state, limitsPtr + F.maxInterStageShaderVariables.offset, lim.maxInterStageShaderVariables)
      writeU32(state, limitsPtr + F.maxColorAttachments.offset, lim.maxColorAttachments)
      writeU32(state, limitsPtr + F.maxColorAttachmentBytesPerSample.offset, lim.maxColorAttachmentBytesPerSample)
      writeU32(state, limitsPtr + F.maxComputeWorkgroupStorageSize.offset, lim.maxComputeWorkgroupStorageSize)
      writeU32(state, limitsPtr + F.maxComputeInvocationsPerWorkgroup.offset, lim.maxComputeInvocationsPerWorkgroup)
      writeU32(state, limitsPtr + F.maxComputeWorkgroupSizeX.offset, lim.maxComputeWorkgroupSizeX)
      writeU32(state, limitsPtr + F.maxComputeWorkgroupSizeY.offset, lim.maxComputeWorkgroupSizeY)
      writeU32(state, limitsPtr + F.maxComputeWorkgroupSizeZ.offset, lim.maxComputeWorkgroupSizeZ)
      writeU32(state, limitsPtr + F.maxComputeWorkgroupsPerDimension.offset, lim.maxComputeWorkgroupsPerDimension)
      writeU32(state, limitsPtr + F.maxImmediateSize.offset, 0) // Dawn extension, not in WebGPU spec
      return 1 // WGPUStatus_Success
    },
    wgpuDeviceHasFeature(_deviceHandle: number, feature: number): number {
      // Use generated enum map: Dawn feature value → kebab-case string
      const name = WGPUFeatureName[feature]
      // The enum map generates kebab-case but GPUDevice.features uses the spec names.
      // Most match directly; Dawn extensions (0x50000+) won't be in the browser.
      const has = name ? device.features.has(name) : false
      return has ? 1 : 0
    },
    wgpuDeviceGetFeatures: noop,
    wgpuDeviceGetAdapter(_deviceHandle: number): number {
      // Return a dummy adapter handle — Graphite uses this for adapter queries
      return registerObject(state, { _type: 'adapter' })
    },
    wgpuDeviceGetQueue(_deviceHandle: number): number {
      return state.queueHandle
    },
    wgpuDeviceTick: noop,
    wgpuDeviceAddRef(handle: number) { addRefObject(state, handle) },
    wgpuDeviceRelease: noop,
    wgpuDeviceSetUncapturedErrorCallback: noop,
    wgpuDeviceSetDeviceLostCallback: noop,
    wgpuDevicePopErrorScope(_deviceHandle: number, callbackInfoPtr: number): bigint {
      // WGPUPopErrorScopeCallbackInfo: nextInChain(0), mode(4), callback(8), userdata1(12), userdata2(16)
      const callbackFnPtr = readU32(state, callbackInfoPtr + 8)
      const userdata1 = readU32(state, callbackInfoPtr + 12)
      const userdata2 = readU32(state, callbackInfoPtr + 16)
      const futureId = state.nextFutureId++
      state.pendingCallbacks.set(futureId, {
        futureId,
        invoke: () => {
          if (state.table && callbackFnPtr) {
            const fn = state.table.get(callbackFnPtr) as (...args: number[]) => void
            // callback(status, type, message_ptr, userdata1, userdata2)
            // WGPUStringView passed by pointer on WASM32
            fn(1, 1, state.emptyStringViewPtr, userdata1, userdata2)
          }
        },
      })
      return futureId
    },
    wgpuDevicePushErrorScope: noop,
    wgpuDeviceDestroy: noop,

    // ── Queue ──

    wgpuQueueSubmit(queueHandle: number, commandCount: number, commandsPtr: number): void {
      const q = getObject<GPUQueue>(state, queueHandle)
      if (!q) return
      const buffers: GPUCommandBuffer[] = []
      for (let i = 0; i < commandCount; i++) {
        const cmdHandle = readU32(state, commandsPtr + i * 4)
        const cmd = getObject<GPUCommandBuffer>(state, cmdHandle)
        if (cmd) buffers.push(cmd)
      }
      q.submit(buffers)
    },

    wgpuQueueWriteBuffer(
      queueHandle: number,
      bufferHandle: number,
      bufferOffset: bigint,
      dataPtr: number,
      size: number,
    ): void {
      const q = getObject<GPUQueue>(state, queueHandle)
      const buf = getObject<GPUBuffer>(state, bufferHandle)
      if (!q || !buf) return
      const data = new Uint8Array(state.memory.buffer, dataPtr, size)
      q.writeBuffer(buf, Number(bufferOffset), data)
    },

    wgpuQueueWriteTexture(
      queueHandle: number,
      destPtr: number,
      dataPtr: number,
      dataSize: bigint,
      layoutPtr: number,
      sizePtr: number,
    ): void {
      const q = getObject<GPUQueue>(state, queueHandle)
      if (!q) return
      const texture = getObject<GPUTexture>(state, field(state, destPtr, L.copyTex.texture))
      if (!texture) return
      const origin = destPtr + L.copyTex.origin.offset
      const dest: GPUTexelCopyTextureInfo = {
        texture,
        mipLevel: field(state, destPtr, L.copyTex.mipLevel),
        origin: [readU32(state, origin), readU32(state, origin + 4), readU32(state, origin + 8)],
        aspect: enumStr(WGPUTextureAspect, field(state, destPtr, L.copyTex.aspect)),
      }
      const dataLayout: GPUTexelCopyBufferLayout = {
        offset: Number(readU64(state, layoutPtr + L.copyBufLayout.offset.offset)),
        bytesPerRow: u32OrUndef(field(state, layoutPtr, L.copyBufLayout.bytesPerRow)),
        rowsPerImage: u32OrUndef(field(state, layoutPtr, L.copyBufLayout.rowsPerImage)),
      }
      const size: GPUExtent3DStrict = {
        width: readU32(state, sizePtr),
        height: readU32(state, sizePtr + 4),
        depthOrArrayLayers: readU32(state, sizePtr + 8),
      }
      const data = new Uint8Array(state.memory.buffer, dataPtr, Number(dataSize))
      q.writeTexture(dest, data, dataLayout, size)
    },

    wgpuQueueAddRef(handle: number) { addRefObject(state, handle) },
    wgpuQueueRelease: noop,
    wgpuQueueOnSubmittedWorkDone(_queueHandle: number, callbackInfoPtr: number): bigint {
      // WGPUQueueWorkDoneCallbackInfo: nextInChain(0), mode(4), callback(8), userdata1(12), userdata2(16)
      const callbackFnPtr = readU32(state, callbackInfoPtr + 8)
      const userdata1 = readU32(state, callbackInfoPtr + 12)
      const userdata2 = readU32(state, callbackInfoPtr + 16)
      const futureId = state.nextFutureId++
      state.pendingCallbacks.set(futureId, {
        futureId,
        invoke: () => {
          if (state.table && callbackFnPtr) {
            const fn = state.table.get(callbackFnPtr) as (...args: number[]) => void
            // callback(status, message_ptr, userdata1, userdata2)
            // WGPUStringView passed by pointer on WASM32
            fn(1, state.emptyStringViewPtr, userdata1, userdata2)
          }
        },
      })
      return futureId
    },

    // ── Buffer ──

    wgpuBufferMapAsync(_bufferHandle: number, _mode: bigint, _offset: number, _size: number, _callbackInfo: number): bigint {
      // TODO: async buffer mapping — not used by Graphite for rendering init
      return 0n
    },
    wgpuBufferGetMappedRange(bufferHandle: number, offset: number, size: number): number {
      const buf = getObject<GPUBuffer>(state, bufferHandle)
      if (!buf || !state.malloc) return 0
      // size of -1 (0xFFFFFFFF / SIZE_MAX) means entire buffer
      const actualSize = (size === -1 || size === 0xFFFFFFFF) ? buf.size - offset : size
      const jsArrayBuffer = buf.getMappedRange(offset, actualSize)
      const wasmPtr = state.malloc(actualSize)
      if (!wasmPtr) return 0
      // For mappedAtCreation, the buffer starts zeroed — no need to copy in
      // Store mapping so unmap can copy back and free
      state.mappings.set(bufferHandle, { buffer: buf, jsArrayBuffer, wasmPtr, offset, size: actualSize })
      return wasmPtr
    },
    wgpuBufferGetConstMappedRange(bufferHandle: number, offset: number, size: number): number {
      // Same as getMappedRange for read-only access
      return (impl.wgpuBufferGetMappedRange as (h: number, o: number, s: number) => number)(bufferHandle, offset, size)
    },
    wgpuBufferUnmap(bufferHandle: number): void {
      const buf = getObject<GPUBuffer>(state, bufferHandle)
      if (!buf) return
      const mapping = state.mappings.get(bufferHandle)
      if (mapping) {
        // Copy data from WASM memory back to the mapped GPU buffer
        const src = new Uint8Array(state.memory.buffer, mapping.wasmPtr, mapping.size)
        const dst = new Uint8Array(mapping.jsArrayBuffer)
        dst.set(src)
        // Free WASM memory and clean up
        if (state.free) state.free(mapping.wasmPtr)
        state.mappings.delete(bufferHandle)
      }
      buf.unmap()
    },
    wgpuBufferGetMapState: noop,
    wgpuBufferGetUsage(bufferHandle: number): bigint {
      return BigInt(getObject<GPUBuffer>(state, bufferHandle)?.usage ?? 0)
    },
    wgpuBufferGetSize(bufferHandle: number): bigint {
      const buf = getObject<GPUBuffer>(state, bufferHandle)
      return BigInt(buf?.size ?? 0)
    },
    wgpuBufferAddRef(handle: number) { addRefObject(state, handle) },
    wgpuBufferRelease(handle: number) { releaseObject(state, handle) },
    wgpuBufferDestroy(handle: number) {
      const buf = getObject<GPUBuffer>(state, handle)
      if (buf) buf.destroy()
      releaseObject(state, handle)
    },

    // ── Texture ──

    wgpuTextureCreateView(texHandle: number, descriptorPtr: number): number {
      const tex = getObject<GPUTexture>(state, texHandle)
      if (!tex) return 0
      let viewHandle: number
      if (descriptorPtr === 0) {
        viewHandle = registerObject(state, tex.createView())
      } else {
        const tvFields = W.WGPUTextureViewDescriptor.fields
        const formatVal = field(state, descriptorPtr, tvFields.format)
        const dimVal = field(state, descriptorPtr, tvFields.dimension)
        const desc: GPUTextureViewDescriptor = {
          baseMipLevel: field(state, descriptorPtr, tvFields.baseMipLevel),
          mipLevelCount: u32OrUndef(field(state, descriptorPtr, tvFields.mipLevelCount)),
          baseArrayLayer: field(state, descriptorPtr, tvFields.baseArrayLayer),
          arrayLayerCount: u32OrUndef(field(state, descriptorPtr, tvFields.arrayLayerCount)),
        }
        if (formatVal !== 0) desc.format = enumStr(WGPUTextureFormat, formatVal)
        if (dimVal !== 0) desc.dimension = enumStr(WGPUTextureViewDimension, dimVal)
        const aspectVal = field(state, descriptorPtr, tvFields.aspect)
        if (aspectVal !== 0) desc.aspect = enumStr(WGPUTextureAspect, aspectVal)
        viewHandle = registerObject(state, tex.createView(desc))
      }
      // Track view→texture mapping for compositing
      state.viewToTexture.set(viewHandle, tex)
      return viewHandle
    },
    wgpuTextureGetWidth(texHandle: number): number {
      return getObject<GPUTexture>(state, texHandle)?.width ?? 0
    },
    wgpuTextureGetHeight(texHandle: number): number {
      return getObject<GPUTexture>(state, texHandle)?.height ?? 0
    },
    wgpuTextureGetFormat(texHandle: number): number {
      // Reverse map format string → Dawn enum value
      const tex = getObject<GPUTexture>(state, texHandle)
      if (!tex) return 0
      const fmt = tex.format
      for (const [key, val] of Object.entries(WGPUTextureFormat)) {
        if (val === fmt) return Number(key)
      }
      return 0
    },
    wgpuTextureGetUsage(texHandle: number): bigint {
      return BigInt(getObject<GPUTexture>(state, texHandle)?.usage ?? 0)
    },
    wgpuTextureGetMipLevelCount(texHandle: number): number {
      return getObject<GPUTexture>(state, texHandle)?.mipLevelCount ?? 1
    },
    wgpuTextureGetSampleCount(texHandle: number): number {
      return getObject<GPUTexture>(state, texHandle)?.sampleCount ?? 1
    },
    wgpuTextureAddRef(handle: number) { addRefObject(state, handle) },
    wgpuTextureRelease(handle: number) { releaseObject(state, handle) },
    wgpuTextureDestroy(handle: number) {
      const tex = getObject<GPUTexture>(state, handle)
      if (tex) tex.destroy()
      releaseObject(state, handle)
    },

    // ── TextureView ──
    wgpuTextureViewAddRef(handle: number) { addRefObject(state, handle) },
    wgpuTextureViewRelease(handle: number) { releaseObject(state, handle) },

    // ── CommandEncoder ──

    wgpuCommandEncoderBeginRenderPass(encoderHandle: number, ptr: number): number {
      const encoder = getObject<GPUCommandEncoder>(state, encoderHandle)
      if (!encoder) return 0

      // Color attachments
      const colorCount = field(state, ptr, L.rpPassDesc.colorAttachmentCount)
      const colorsPtr = field(state, ptr, L.rpPassDesc.colorAttachments)
      const colorAttachments: GPURenderPassColorAttachment[] = []
      for (let i = 0; i < colorCount; i++) {
        const c = colorsPtr + i * W.WGPURenderPassColorAttachment._size
        const viewHandle = field(state, c, L.rpColor.view)
        const view = getObject<GPUTextureView>(state, viewHandle)
        if (!view) continue
        const clearBase = c + L.rpColor.clearValue.offset
        const attachment: GPURenderPassColorAttachment = {
          view,
          loadOp: enumStr(WGPULoadOp, field(state, c, L.rpColor.loadOp)),
          storeOp: enumStr(WGPUStoreOp, field(state, c, L.rpColor.storeOp)),
          clearValue: {
            r: readF64(state, clearBase),
            g: readF64(state, clearBase + 8),
            b: readF64(state, clearBase + 16),
            a: readF64(state, clearBase + 24),
          },
        }
        const resolveHandle = field(state, c, L.rpColor.resolveTarget)
        if (resolveHandle) {
          attachment.resolveTarget = getObject<GPUTextureView>(state, resolveHandle) ?? undefined
        }
        colorAttachments.push(attachment)
      }

      // Depth/stencil attachment (optional)
      const dsAttachPtr = field(state, ptr, L.rpPassDesc.depthStencilAttachment)
      let depthStencilAttachment: GPURenderPassDepthStencilAttachment | undefined
      if (dsAttachPtr) {
        const dsView = getObject<GPUTextureView>(state, field(state, dsAttachPtr, L.rpDepth.view))
        if (dsView) {
          const depthLoadOpVal = field(state, dsAttachPtr, L.rpDepth.depthLoadOp)
          depthStencilAttachment = {
            view: dsView,
            depthLoadOp: field(state, dsAttachPtr, L.rpDepth.depthLoadOp) ? enumStr(WGPULoadOp, field(state, dsAttachPtr, L.rpDepth.depthLoadOp)) : undefined,
            depthStoreOp: field(state, dsAttachPtr, L.rpDepth.depthStoreOp) ? enumStr(WGPUStoreOp, field(state, dsAttachPtr, L.rpDepth.depthStoreOp)) : undefined,
            depthClearValue: readF32(state, dsAttachPtr + L.rpDepth.depthClearValue.offset),
            depthReadOnly: field(state, dsAttachPtr, L.rpDepth.depthReadOnly) !== 0,
            stencilLoadOp: field(state, dsAttachPtr, L.rpDepth.stencilLoadOp) ? enumStr(WGPULoadOp, field(state, dsAttachPtr, L.rpDepth.stencilLoadOp)) : undefined,
            stencilStoreOp: field(state, dsAttachPtr, L.rpDepth.stencilStoreOp) ? enumStr(WGPUStoreOp, field(state, dsAttachPtr, L.rpDepth.stencilStoreOp)) : undefined,
            stencilClearValue: field(state, dsAttachPtr, L.rpDepth.stencilClearValue),
            stencilReadOnly: field(state, dsAttachPtr, L.rpDepth.stencilReadOnly) !== 0,
          }
        }
      }

      // Track last render pass color target for compositing
      const viewHandle = field(state, colorsPtr, L.rpColor.view)
      const parentTex = state.viewToTexture.get(viewHandle)
      if (parentTex) state.lastRenderTargetTexture = parentTex
      const renderPass = encoder.beginRenderPass({
        colorAttachments,
        depthStencilAttachment,
      })
      return registerObject(state, renderPass)
    },

    wgpuCommandEncoderBeginComputePass(encoderHandle: number, _descriptorPtr: number): number {
      const encoder = getObject<GPUCommandEncoder>(state, encoderHandle)
      if (!encoder) return 0
      return registerObject(state, encoder.beginComputePass())
    },

    wgpuCommandEncoderCopyBufferToBuffer(
      encoderHandle: number,
      srcHandle: number, srcOffset: bigint,
      dstHandle: number, dstOffset: bigint,
      size: bigint,
    ): void {
      const encoder = getObject<GPUCommandEncoder>(state, encoderHandle)
      const src = getObject<GPUBuffer>(state, srcHandle)
      const dst = getObject<GPUBuffer>(state, dstHandle)
      if (!encoder || !src || !dst) return
      encoder.copyBufferToBuffer(src, Number(srcOffset), dst, Number(dstOffset), Number(size))
    },

    wgpuCommandEncoderCopyBufferToTexture(
      encoderHandle: number, srcPtr: number, dstPtr: number, sizePtr: number,
    ): void {
      const encoder = getObject<GPUCommandEncoder>(state, encoderHandle)
      if (!encoder) return
      const layoutBase = srcPtr + L.copyBuf.layout.offset
      const source: GPUTexelCopyBufferInfo = {
        buffer: getObject<GPUBuffer>(state, field(state, srcPtr, L.copyBuf.buffer))!,
        offset: Number(readU64(state, layoutBase + L.copyBufLayout.offset.offset)),
        bytesPerRow: u32OrUndef(field(state, layoutBase, L.copyBufLayout.bytesPerRow)),
        rowsPerImage: u32OrUndef(field(state, layoutBase, L.copyBufLayout.rowsPerImage)),
      }
      const originBase = dstPtr + L.copyTex.origin.offset
      const destination: GPUTexelCopyTextureInfo = {
        texture: getObject<GPUTexture>(state, field(state, dstPtr, L.copyTex.texture))!,
        mipLevel: field(state, dstPtr, L.copyTex.mipLevel),
        origin: [readU32(state, originBase), readU32(state, originBase + 4), readU32(state, originBase + 8)],
        aspect: enumStr(WGPUTextureAspect, field(state, dstPtr, L.copyTex.aspect)),
      }
      const copySize: GPUExtent3DStrict = {
        width: readU32(state, sizePtr),
        height: readU32(state, sizePtr + 4),
        depthOrArrayLayers: readU32(state, sizePtr + 8),
      }
      encoder.copyBufferToTexture(source, destination, copySize)
    },

    wgpuCommandEncoderCopyTextureToBuffer(
      encoderHandle: number, srcPtr: number, dstPtr: number, sizePtr: number,
    ): void {
      const encoder = getObject<GPUCommandEncoder>(state, encoderHandle)
      if (!encoder) return
      const originBase = srcPtr + L.copyTex.origin.offset
      const source: GPUTexelCopyTextureInfo = {
        texture: getObject<GPUTexture>(state, field(state, srcPtr, L.copyTex.texture))!,
        mipLevel: field(state, srcPtr, L.copyTex.mipLevel),
        origin: [readU32(state, originBase), readU32(state, originBase + 4), readU32(state, originBase + 8)],
        aspect: enumStr(WGPUTextureAspect, field(state, srcPtr, L.copyTex.aspect)),
      }
      const layoutBase = dstPtr + L.copyBuf.layout.offset
      const destination: GPUTexelCopyBufferInfo = {
        buffer: getObject<GPUBuffer>(state, field(state, dstPtr, L.copyBuf.buffer))!,
        offset: Number(readU64(state, layoutBase + L.copyBufLayout.offset.offset)),
        bytesPerRow: u32OrUndef(field(state, layoutBase, L.copyBufLayout.bytesPerRow)),
        rowsPerImage: u32OrUndef(field(state, layoutBase, L.copyBufLayout.rowsPerImage)),
      }
      const copySize: GPUExtent3DStrict = {
        width: readU32(state, sizePtr),
        height: readU32(state, sizePtr + 4),
        depthOrArrayLayers: readU32(state, sizePtr + 8),
      }
      encoder.copyTextureToBuffer(source, destination, copySize)
    },

    wgpuCommandEncoderCopyTextureToTexture(
      encoderHandle: number, srcPtr: number, dstPtr: number, sizePtr: number,
    ): void {
      const encoder = getObject<GPUCommandEncoder>(state, encoderHandle)
      if (!encoder) return
      const readCopyTex = (p: number): GPUTexelCopyTextureInfo => {
        const o = p + L.copyTex.origin.offset
        return {
          texture: getObject<GPUTexture>(state, field(state, p, L.copyTex.texture))!,
          mipLevel: field(state, p, L.copyTex.mipLevel),
          origin: [readU32(state, o), readU32(state, o + 4), readU32(state, o + 8)],
          aspect: enumStr(WGPUTextureAspect, field(state, p, L.copyTex.aspect)),
        }
      }
      const copySize: GPUExtent3DStrict = {
        width: readU32(state, sizePtr),
        height: readU32(state, sizePtr + 4),
        depthOrArrayLayers: readU32(state, sizePtr + 8),
      }
      encoder.copyTextureToTexture(readCopyTex(srcPtr), readCopyTex(dstPtr), copySize)
    },

    wgpuCommandEncoderClearBuffer(
      encoderHandle: number, bufferHandle: number, offset: bigint, size: bigint,
    ): void {
      const encoder = getObject<GPUCommandEncoder>(state, encoderHandle)
      const buf = getObject<GPUBuffer>(state, bufferHandle)
      if (!encoder || !buf) return
      encoder.clearBuffer(buf, Number(offset), Number(size))
    },

    wgpuCommandEncoderFinish(encoderHandle: number, _descriptorPtr: number): number {
      const encoder = getObject<GPUCommandEncoder>(state, encoderHandle)
      if (!encoder) return 0
      return registerObject(state, encoder.finish())
    },
    wgpuCommandEncoderAddRef(handle: number) { addRefObject(state, handle) },
    wgpuCommandEncoderRelease(handle: number) { releaseObject(state, handle) },

    // ── RenderPassEncoder ──

    wgpuRenderPassEncoderSetPipeline(passHandle: number, pipelineHandle: number): void {
      const pass = getObject<GPURenderPassEncoder>(state, passHandle)
      const pipeline = getObject<GPURenderPipeline>(state, pipelineHandle)
      if (pass && pipeline) pass.setPipeline(pipeline)
    },
    wgpuRenderPassEncoderSetBindGroup(
      passHandle: number, index: number, groupHandle: number,
      dynOffsetCount: number, dynOffsetPtr: number,
    ): void {
      const pass = getObject<GPURenderPassEncoder>(state, passHandle)
      const group = getObject<GPUBindGroup>(state, groupHandle)
      if (!pass) return
      if (dynOffsetCount > 0) {
        const offsets = new Uint32Array(state.memory.buffer, dynOffsetPtr, dynOffsetCount)
        pass.setBindGroup(index, group, [...offsets])
      } else {
        pass.setBindGroup(index, group)
      }
    },
    wgpuRenderPassEncoderSetVertexBuffer(
      passHandle: number, slot: number, bufferHandle: number, offset: bigint, size: bigint,
    ): void {
      const pass = getObject<GPURenderPassEncoder>(state, passHandle)
      const buf = getObject<GPUBuffer>(state, bufferHandle)
      if (pass && buf) {
        const s = (size === WGPU_WHOLE_SIZE || size < 0n) ? undefined : Number(size)
        pass.setVertexBuffer(slot, buf, Number(offset), s)
      }
    },
    wgpuRenderPassEncoderSetIndexBuffer(
      passHandle: number, bufferHandle: number, format: number, offset: bigint, size: bigint,
    ): void {
      const pass = getObject<GPURenderPassEncoder>(state, passHandle)
      const buf = getObject<GPUBuffer>(state, bufferHandle)
      if (pass && buf) {
        const s = (size === WGPU_WHOLE_SIZE || size < 0n) ? undefined : Number(size)
        pass.setIndexBuffer(buf, enumStr<GPUIndexFormat>(WGPUIndexFormat, format), Number(offset), s)
      }
    },
    wgpuRenderPassEncoderSetViewport(
      passHandle: number, x: number, y: number, w: number, h: number, minDepth: number, maxDepth: number,
    ): void {
      const pass = getObject<GPURenderPassEncoder>(state, passHandle)
      if (pass) pass.setViewport(x, y, w, h, minDepth, maxDepth)
    },
    wgpuRenderPassEncoderSetScissorRect(
      passHandle: number, x: number, y: number, w: number, h: number,
    ): void {
      const pass = getObject<GPURenderPassEncoder>(state, passHandle)
      if (pass) pass.setScissorRect(x, y, w, h)
    },
    wgpuRenderPassEncoderSetBlendConstant(passHandle: number, colorPtr: number): void {
      const pass = getObject<GPURenderPassEncoder>(state, passHandle)
      if (!pass) return
      pass.setBlendConstant({
        r: readF64(state, colorPtr),
        g: readF64(state, colorPtr + 8),
        b: readF64(state, colorPtr + 16),
        a: readF64(state, colorPtr + 24),
      })
    },
    wgpuRenderPassEncoderDraw(
      passHandle: number, vertexCount: number, instanceCount: number,
      firstVertex: number, firstInstance: number,
    ): void {
      const pass = getObject<GPURenderPassEncoder>(state, passHandle)
      if (pass) pass.draw(vertexCount, instanceCount, firstVertex, firstInstance)
    },
    wgpuRenderPassEncoderDrawIndexed(
      passHandle: number, indexCount: number, instanceCount: number,
      firstIndex: number, baseVertex: number, firstInstance: number,
    ): void {
      const pass = getObject<GPURenderPassEncoder>(state, passHandle)
      if (pass) pass.drawIndexed(indexCount, instanceCount, firstIndex, baseVertex, firstInstance)
    },
    wgpuRenderPassEncoderDrawIndirect(passHandle: number, bufferHandle: number, offset: bigint): void {
      const pass = getObject<GPURenderPassEncoder>(state, passHandle)
      const buf = getObject<GPUBuffer>(state, bufferHandle)
      if (pass && buf) pass.drawIndirect(buf, Number(offset))
    },
    wgpuRenderPassEncoderDrawIndexedIndirect(passHandle: number, bufferHandle: number, offset: bigint): void {
      const pass = getObject<GPURenderPassEncoder>(state, passHandle)
      const buf = getObject<GPUBuffer>(state, bufferHandle)
      if (pass && buf) pass.drawIndexedIndirect(buf, Number(offset))
    },
    wgpuRenderPassEncoderEnd(passHandle: number): void {
      const pass = getObject<GPURenderPassEncoder>(state, passHandle)
      if (pass) pass.end()
    },
    wgpuRenderPassEncoderAddRef(handle: number) { addRefObject(state, handle) },
    wgpuRenderPassEncoderRelease(handle: number) { releaseObject(state, handle) },

    // ── ComputePassEncoder ──

    wgpuComputePassEncoderSetPipeline(passHandle: number, pipelineHandle: number): void {
      const pass = getObject<GPUComputePassEncoder>(state, passHandle)
      const pipeline = getObject<GPUComputePipeline>(state, pipelineHandle)
      if (pass && pipeline) pass.setPipeline(pipeline)
    },
    wgpuComputePassEncoderSetBindGroup(
      passHandle: number, index: number, groupHandle: number,
      dynOffsetCount: number, dynOffsetPtr: number,
    ): void {
      const pass = getObject<GPUComputePassEncoder>(state, passHandle)
      const group = getObject<GPUBindGroup>(state, groupHandle)
      if (!pass) return
      if (dynOffsetCount > 0) {
        const offsets = new Uint32Array(state.memory.buffer, dynOffsetPtr, dynOffsetCount)
        pass.setBindGroup(index, group, [...offsets])
      } else {
        pass.setBindGroup(index, group)
      }
    },
    wgpuComputePassEncoderDispatchWorkgroups(
      passHandle: number, x: number, y: number, z: number,
    ): void {
      const pass = getObject<GPUComputePassEncoder>(state, passHandle)
      if (pass) pass.dispatchWorkgroups(x, y, z)
    },
    wgpuComputePassEncoderDispatchWorkgroupsIndirect(
      passHandle: number, bufferHandle: number, offset: bigint,
    ): void {
      const pass = getObject<GPUComputePassEncoder>(state, passHandle)
      const buf = getObject<GPUBuffer>(state, bufferHandle)
      if (pass && buf) pass.dispatchWorkgroupsIndirect(buf, Number(offset))
    },
    wgpuComputePassEncoderEnd(passHandle: number): void {
      const pass = getObject<GPUComputePassEncoder>(state, passHandle)
      if (pass) pass.end()
    },
    wgpuComputePassEncoderAddRef(handle: number) { addRefObject(state, handle) },
    wgpuComputePassEncoderRelease(handle: number) { releaseObject(state, handle) },

    // ── CommandBuffer ──
    wgpuCommandBufferAddRef(handle: number) { addRefObject(state, handle) },
    wgpuCommandBufferRelease(handle: number) { releaseObject(state, handle) },

    // ── RenderPipeline ──
    wgpuRenderPipelineAddRef(handle: number) { addRefObject(state, handle) },
    wgpuRenderPipelineRelease(handle: number) { releaseObject(state, handle) },
    wgpuRenderPipelineGetBindGroupLayout(pipelineHandle: number, index: number): number {
      const pipeline = getObject<GPURenderPipeline>(state, pipelineHandle)
      if (!pipeline) return 0
      return registerObject(state, pipeline.getBindGroupLayout(index))
    },

    // ── ComputePipeline ──
    wgpuComputePipelineAddRef(handle: number) { addRefObject(state, handle) },
    wgpuComputePipelineRelease(handle: number) { releaseObject(state, handle) },
    wgpuComputePipelineGetBindGroupLayout(pipelineHandle: number, index: number): number {
      const pipeline = getObject<GPUComputePipeline>(state, pipelineHandle)
      if (!pipeline) return 0
      return registerObject(state, pipeline.getBindGroupLayout(index))
    },

    // ── Sampler ──
    wgpuSamplerAddRef(handle: number) { addRefObject(state, handle) },
    wgpuSamplerRelease(handle: number) { releaseObject(state, handle) },

    // ── ShaderModule ──
    wgpuShaderModuleAddRef(handle: number) { addRefObject(state, handle) },
    wgpuShaderModuleRelease(handle: number) { releaseObject(state, handle) },
    wgpuShaderModuleGetCompilationInfo(_moduleHandle: number, callbackInfoPtr: number): bigint {
      // WGPUCompilationInfoCallbackInfo: nextInChain(0), mode(4), callback(8), userdata1(12), userdata2(16)
      const callbackFnPtr = readU32(state, callbackInfoPtr + 8)
      const userdata1 = readU32(state, callbackInfoPtr + 12)
      const userdata2 = readU32(state, callbackInfoPtr + 16)
      const futureId = state.nextFutureId++

      // Allocate a minimal WGPUCompilationInfo in WASM memory: {nextInChain=0, messageCount=0, messages=0}
      const infoPtr = state.malloc ? state.malloc(12) : 0
      if (infoPtr) {
        writeU32(state, infoPtr, 0)     // nextInChain
        writeU32(state, infoPtr + 4, 0) // messageCount
        writeU32(state, infoPtr + 8, 0) // messages
      }

      state.pendingCallbacks.set(futureId, {
        futureId,
        invoke: () => {
          if (state.table && callbackFnPtr) {
            const fn = state.table.get(callbackFnPtr) as (...args: number[]) => void
            // callback(status=Success(1), compilationInfo, userdata1, userdata2)
            fn(1, infoPtr, userdata1, userdata2)
          }
          if (infoPtr && state.free) state.free(infoPtr)
        },
      })
      return futureId
    },

    // ── BindGroup / BindGroupLayout ──
    wgpuBindGroupAddRef(handle: number) { addRefObject(state, handle) },
    wgpuBindGroupRelease(handle: number) { releaseObject(state, handle) },
    wgpuBindGroupLayoutAddRef(handle: number) { addRefObject(state, handle) },
    wgpuBindGroupLayoutRelease(handle: number) { releaseObject(state, handle) },

    // ── PipelineLayout ──
    wgpuPipelineLayoutAddRef(handle: number) { addRefObject(state, handle) },
    wgpuPipelineLayoutRelease(handle: number) { releaseObject(state, handle) },

    // ── QuerySet ──
    wgpuQuerySetAddRef(handle: number) { addRefObject(state, handle) },
    wgpuQuerySetRelease(handle: number) { releaseObject(state, handle) },
    wgpuQuerySetDestroy(handle: number) { releaseObject(state, handle) },

    // ── Surface (not used — Three.js manages surfaces) ──
    wgpuSurfaceAddRef(handle: number) { addRefObject(state, handle) },
    wgpuSurfaceRelease: noop,

    // ── Instance lifecycle ──
    wgpuInstanceAddRef(handle: number) { addRefObject(state, handle) },
    wgpuInstanceRelease: noop,
    wgpuInstanceProcessEvents: noop,
    wgpuInstanceRequestAdapter: noop,
    wgpuInstanceCreateSurface: noop,
    wgpuInstanceWaitAny(_instanceHandle: number, futureCount: number, futuresPtr: number, _timeoutNS: bigint): number {
      // WGPUFutureWaitInfo: future(u64, offset 0), completed(u32, offset 8) — stride 16 (aligned to 8)
      const stride = 16
      for (let i = 0; i < futureCount; i++) {
        const entryPtr = futuresPtr + i * stride
        const futureId = readU64(state, entryPtr)
        const pending = state.pendingCallbacks.get(futureId)
        if (pending) {
          pending.invoke()
          state.pendingCallbacks.delete(futureId)
          writeU32(state, entryPtr + 8, 1) // completed = true
        }
      }
      return 0 // WGPUWaitStatus_Success
    },

    // ── Memory management ──
    wgpuAdapterInfoFreeMembers: noop,
    wgpuAdapterPropertiesMemoryHeapsFreeMembers: noop,
    wgpuSupportedFeaturesFreeMembers: noop,
    wgpuSupportedWGSLLanguageFeaturesFreeMembers: noop,
    wgpuSurfaceCapabilitiesFreeMembers: noop,

    // ── Render bundles ──
    wgpuRenderBundleAddRef(handle: number) { addRefObject(state, handle) },
    wgpuRenderBundleRelease: noop,
    wgpuRenderBundleEncoderFinish: noop,
    wgpuRenderBundleEncoderAddRef(handle: number) { addRefObject(state, handle) },
    wgpuRenderBundleEncoderRelease: noop,
    wgpuDeviceCreateRenderBundleEncoder: noop,

    // ── External textures (Dawn extensions) ──
    wgpuExternalTextureAddRef(handle: number) { addRefObject(state, handle) },
    wgpuExternalTextureRelease: noop,
    wgpuDeviceCreateExternalTexture: noop,

    // ── Shared resources (Dawn extensions) ──
    wgpuSharedBufferMemoryAddRef(handle: number) { addRefObject(state, handle) },
    wgpuSharedBufferMemoryRelease: noop,
    wgpuSharedTextureMemoryAddRef(handle: number) { addRefObject(state, handle) },
    wgpuSharedTextureMemoryRelease: noop,
    wgpuSharedFenceAddRef(handle: number) { addRefObject(state, handle) },
    wgpuSharedFenceRelease: noop,
  }

  return new Proxy(impl, {
    get: (target, name) => {
      if (typeof name !== 'string') return undefined
      if (name in target) return target[name]
      return (..._args: unknown[]) => 0
    },
  })
}

// ── Public API ──

export interface SkiaWGPUWasmInstance {
  exports: WebAssembly.Exports & {
    memory: WebAssembly.Memory
    skia_init_dawn: (deviceHandle: number, queueHandle: number) => void
    exports_skia_wgpu_destroy: () => void
    exports_skia_wgpu_begin_drawing: (targetHandle: number, w: number, h: number, retPtr: number) => number
    exports_skia_wgpu_end_drawing: () => void
    exports_skia_wgpu_flush: () => void
  }
  wgpuState: WGPUState
}

export async function loadSkiaWGPU(
  wasmUrl: string | URL,
  device: GPUDevice,
  preloadedResponse?: Promise<Response>,
): Promise<SkiaWGPUWasmInstance> {
  const state = createWGPUState(device)

  const importObject: WebAssembly.Imports = {
    wgpu: createWGPUImports(state),
    env: createEnvImports(),
    wasi_snapshot_preview1: createWasiImports(() => state.memory),
  }

  const response = preloadedResponse ?? fetch(wasmUrl)
  const { instance } = await instantiateWasm(response, importObject)

  state.memory = instance.exports.memory as WebAssembly.Memory
  // Wire up WASM memory allocator for buffer mapping
  // _Znwm = operator new(size_t), _ZdlPv = operator delete(void*)
  state.malloc = (instance.exports._Znwm as (size: number) => number) ?? null
  state.free = (instance.exports._ZdlPv as (ptr: number) => void) ?? null
  // Function table for invoking WASM callbacks
  state.table = (instance.exports.__indirect_function_table as WebAssembly.Table) ?? null
  // Pre-allocate an empty WGPUStringView for callback messages
  if (state.malloc) {
    state.emptyStringViewPtr = state.malloc(8)
    writeU32(state, state.emptyStringViewPtr, 0)     // data = null
    writeU32(state, state.emptyStringViewPtr + 4, 0)  // length = 0
  }

  return {
    exports: instance.exports as SkiaWGPUWasmInstance['exports'],
    wgpuState: state,
  }
}
