// Auto-generated by generate-wgpu-bridge.py — do not edit
// Source: src/zig/wgpu_shim/dawn/webgpu.h
//
// Dawn C enum values → WebGPU string values for the browser API.

/** WGPUAddressMode → GPUAddressMode */
export const WGPUAddressMode: Record<number, string> = {
  0x00000001: 'clamp-to-edge',
  0x00000002: 'repeat',
  0x00000003: 'mirror-repeat',
}

/** WGPUBlendFactor → GPUBlendFactor */
export const WGPUBlendFactor: Record<number, string> = {
  0x00000001: 'zero',
  0x00000002: 'one',
  0x00000003: 'src',
  0x00000004: 'one-minus-src',
  0x00000005: 'src-alpha',
  0x00000006: 'one-minus-src-alpha',
  0x00000007: 'dst',
  0x00000008: 'one-minus-dst',
  0x00000009: 'dst-alpha',
  0x0000000A: 'one-minus-dst-alpha',
  0x0000000B: 'src-alpha-saturated',
  0x0000000C: 'constant',
  0x0000000D: 'one-minus-constant',
  0x0000000E: 'src1',
  0x0000000F: 'one-minus-src1',
  0x00000010: 'src1-alpha',
  0x00000011: 'one-minus-src1-alpha',
}

/** WGPUBlendOperation → GPUBlendOperation */
export const WGPUBlendOperation: Record<number, string> = {
  0x00000001: 'add',
  0x00000002: 'subtract',
  0x00000003: 'reverse-subtract',
  0x00000004: 'min',
  0x00000005: 'max',
}

/** WGPUBufferBindingType → GPUBufferBindingType */
export const WGPUBufferBindingType: Record<number, string> = {
  0x00000000: 'binding-not-used',
  0x00000001: 'undefined',
  0x00000002: 'uniform',
  0x00000003: 'storage',
  0x00000004: 'read-only-storage',
}

/** WGPUCompareFunction → GPUCompareFunction */
export const WGPUCompareFunction: Record<number, string> = {
  0x00000001: 'never',
  0x00000002: 'less',
  0x00000003: 'equal',
  0x00000004: 'less-equal',
  0x00000005: 'greater',
  0x00000006: 'not-equal',
  0x00000007: 'greater-equal',
  0x00000008: 'always',
}

/** WGPUCullMode → GPUCullMode */
export const WGPUCullMode: Record<number, string> = {
  0x00000001: 'none',
  0x00000002: 'front',
  0x00000003: 'back',
}

/** WGPUFeatureName → GPUFeatureName */
export const WGPUFeatureName: Record<number, string> = {
  0x00000001: 'core-features-and-limits',
  0x00000002: 'depth-clip-control',
  0x00000003: 'depth32-float-stencil8',
  0x00000004: 'texture-compression-bc',
  0x00000005: 'texture-compression-bc-sliced3-d',
  0x00000006: 'texture-compression-etc2',
  0x00000007: 'texture-compression-astc',
  0x00000008: 'texture-compression-astc-sliced3-d',
  0x00000009: 'timestamp-query',
  0x0000000A: 'indirect-first-instance',
  0x0000000B: 'shader-f16',
  0x0000000C: 'rg11-b10-ufloat-renderable',
  0x0000000D: 'bgra8-unorm-storage',
  0x0000000E: 'float32-filterable',
  0x0000000F: 'float32-blendable',
  0x00000010: 'clip-distances',
  0x00000011: 'dual-source-blending',
  0x00000012: 'subgroups',
  0x00000013: 'texture-formats-tier1',
  0x00000014: 'texture-formats-tier2',
  0x00000015: 'primitive-index',
  0x00000016: 'texture-component-swizzle',
  0x00050000: 'dawn-internal-usages',
  0x00050001: 'dawn-multi-planar-formats',
  0x00050002: 'dawn-native',
  0x00050003: 'chromium-experimental-timestamp-query-inside-passes',
  0x00050004: 'implicit-device-synchronization',
  0x00050006: 'transient-attachments',
  0x00050007: 'msaa-render-to-single-sampled',
  0x00050008: 'd3-d11-multithread-protected',
  0x00050009: 'angle-texture-sharing',
  0x0005000A: 'pixel-local-storage-coherent',
  0x0005000B: 'pixel-local-storage-non-coherent',
  0x0005000C: 'unorm16-texture-formats',
  0x0005000D: 'multi-planar-format-extended-usages',
  0x0005000E: 'multi-planar-format-p010',
  0x0005000F: 'host-mapped-pointer',
  0x00050010: 'multi-planar-render-targets',
  0x00050011: 'multi-planar-format-nv12a',
  0x00050012: 'framebuffer-fetch',
  0x00050013: 'buffer-map-extended-usages',
  0x00050014: 'adapter-properties-memory-heaps',
  0x00050015: 'adapter-properties-d3-d',
  0x00050016: 'adapter-properties-vk',
  0x00050017: 'dawn-format-capabilities',
  0x00050018: 'dawn-drm-format-capabilities',
  0x00050019: 'multi-planar-format-nv16',
  0x0005001A: 'multi-planar-format-nv24',
  0x0005001B: 'multi-planar-format-p210',
  0x0005001C: 'multi-planar-format-p410',
  0x0005001D: 'shared-texture-memory-vk-dedicated-allocation',
  0x0005001E: 'shared-texture-memory-a-hardware-buffer',
  0x0005001F: 'shared-texture-memory-dma-buf',
  0x00050020: 'shared-texture-memory-opaque-fd',
  0x00050021: 'shared-texture-memory-zircon-handle',
  0x00050022: 'shared-texture-memory-dxgi-shared-handle',
  0x00050023: 'shared-texture-memory-d3-d11-texture2-d',
  0x00050024: 'shared-texture-memory-io-surface',
  0x00050025: 'shared-texture-memory-egl-image',
  0x00050026: 'shared-fence-vk-semaphore-opaque-fd',
  0x00050027: 'shared-fence-sync-fd',
  0x00050028: 'shared-fence-vk-semaphore-zircon-handle',
  0x00050029: 'shared-fence-dxgi-shared-handle',
  0x0005002A: 'shared-fence-mtl-shared-event',
  0x0005002B: 'shared-buffer-memory-d3-d12-resource',
  0x0005002C: 'static-samplers',
  0x0005002D: 'y-cb-cr-vulkan-samplers',
  0x0005002E: 'shader-module-compilation-options',
  0x0005002F: 'dawn-load-resolve-texture',
  0x00050030: 'dawn-partial-load-resolve-texture',
  0x00050031: 'multi-draw-indirect',
  0x00050032: 'dawn-texel-copy-buffer-row-alignment',
  0x00050033: 'flexible-texture-views',
  0x00050034: 'chromium-experimental-subgroup-matrix',
  0x00050035: 'shared-fence-egl-sync',
  0x00050036: 'dawn-device-allocator-control',
  0x00050037: 'adapter-properties-wgpu',
  0x00050038: 'shared-buffer-memory-d3-d12-shared-memory-file-mapping-handle',
  0x00050039: 'shared-texture-memory-d3-d12-resource',
  0x0005003A: 'chromium-experimental-sampling-resource-table',
  0x0005003B: 'chromium-experimental-subgroup-size-control',
  0x0005003C: 'atomic-vec2u-min-max',
  0x0005003D: 'unorm16-formats-for-external-texture',
  0x0005003E: 'opaque-y-cb-cr-android-for-external-texture',
  0x0005003F: 'unorm16-filterable',
  0x00050040: 'render-pass-render-area',
  0x00050041: 'dawn-native-spontaneous-queue-events',
  0x00050042: 'adapter-properties-drm',
}

/** WGPUFilterMode → GPUFilterMode */
export const WGPUFilterMode: Record<number, string> = {
  0x00000001: 'nearest',
  0x00000002: 'linear',
}

/** WGPUFrontFace → GPUFrontFace */
export const WGPUFrontFace: Record<number, string> = {
  0x00000001: 'ccw',
  0x00000002: 'cw',
}

/** WGPUIndexFormat → GPUIndexFormat */
export const WGPUIndexFormat: Record<number, string> = {
  0x00000001: 'uint16',
  0x00000002: 'uint32',
}

/** WGPULoadOp → GPULoadOp */
export const WGPULoadOp: Record<number, string> = {
  0x00000001: 'load',
  0x00000002: 'clear',
  0x00050003: 'expand-resolve-texture',
}

/** WGPUMipmapFilterMode → GPUMipmapFilterMode */
export const WGPUMipmapFilterMode: Record<number, string> = {
  0x00000001: 'nearest',
  0x00000002: 'linear',
}

/** WGPUPrimitiveTopology → GPUPrimitiveTopology */
export const WGPUPrimitiveTopology: Record<number, string> = {
  0x00000001: 'point-list',
  0x00000002: 'line-list',
  0x00000003: 'line-strip',
  0x00000004: 'triangle-list',
  0x00000005: 'triangle-strip',
}

/** WGPUQueryType → GPUQueryType */
export const WGPUQueryType: Record<number, string> = {
  0x00000001: 'occlusion',
  0x00000002: 'timestamp',
}

/** WGPUSamplerBindingType → GPUSamplerBindingType */
export const WGPUSamplerBindingType: Record<number, string> = {
  0x00000000: 'binding-not-used',
  0x00000001: 'undefined',
  0x00000002: 'filtering',
  0x00000003: 'non-filtering',
  0x00000004: 'comparison',
}

/** WGPUStencilOperation → GPUStencilOperation */
export const WGPUStencilOperation: Record<number, string> = {
  0x00000001: 'keep',
  0x00000002: 'zero',
  0x00000003: 'replace',
  0x00000004: 'invert',
  0x00000005: 'increment-clamp',
  0x00000006: 'decrement-clamp',
  0x00000007: 'increment-wrap',
  0x00000008: 'decrement-wrap',
}

/** WGPUStorageTextureAccess → GPUStorageTextureAccess */
export const WGPUStorageTextureAccess: Record<number, string> = {
  0x00000000: 'binding-not-used',
  0x00000001: 'undefined',
  0x00000002: 'write-only',
  0x00000003: 'read-only',
  0x00000004: 'read-write',
}

/** WGPUStoreOp → GPUStoreOp */
export const WGPUStoreOp: Record<number, string> = {
  0x00000001: 'store',
  0x00000002: 'discard',
}

/** WGPUTextureAspect → GPUTextureAspect */
export const WGPUTextureAspect: Record<number, string> = {
  0x00000001: 'all',
  0x00000002: 'stencil-only',
  0x00000003: 'depth-only',
  0x00050000: 'plane0-only',
  0x00050001: 'plane1-only',
  0x00050002: 'plane2-only',
}

/** WGPUTextureDimension → GPUTextureDimension */
export const WGPUTextureDimension: Record<number, string> = {
  0x00000001: '1-d',
  0x00000002: '2-d',
  0x00000003: '3-d',
}

/** WGPUTextureFormat → GPUTextureFormat */
export const WGPUTextureFormat: Record<number, string> = {
  0x00000001: 'r8unorm',
  0x00000002: 'r8snorm',
  0x00000003: 'r8uint',
  0x00000004: 'r8sint',
  0x00000005: 'r16unorm',
  0x00000006: 'r16snorm',
  0x00000007: 'r16uint',
  0x00000008: 'r16sint',
  0x00000009: 'r16float',
  0x0000000A: 'rg8unorm',
  0x0000000B: 'rg8snorm',
  0x0000000C: 'rg8uint',
  0x0000000D: 'rg8sint',
  0x0000000E: 'r32float',
  0x0000000F: 'r32uint',
  0x00000010: 'r32sint',
  0x00000011: 'rg16unorm',
  0x00000012: 'rg16snorm',
  0x00000013: 'rg16uint',
  0x00000014: 'rg16sint',
  0x00000015: 'rg16float',
  0x00000016: 'rgba8unorm',
  0x00000017: 'rgba8unorm-srgb',
  0x00000018: 'rgba8snorm',
  0x00000019: 'rgba8uint',
  0x0000001A: 'rgba8sint',
  0x0000001B: 'bgra8unorm',
  0x0000001C: 'bgra8unorm-srgb',
  0x0000001D: 'rgb10a2uint',
  0x0000001E: 'rgb10a2unorm',
  0x0000001F: 'rg11b10ufloat',
  0x00000020: 'rgb9e5ufloat',
  0x00000021: 'rg32float',
  0x00000022: 'rg32uint',
  0x00000023: 'rg32sint',
  0x00000024: 'rgba16unorm',
  0x00000025: 'rgba16snorm',
  0x00000026: 'rgba16uint',
  0x00000027: 'rgba16sint',
  0x00000028: 'rgba16float',
  0x00000029: 'rgba32float',
  0x0000002A: 'rgba32uint',
  0x0000002B: 'rgba32sint',
  0x0000002C: 'stencil8',
  0x0000002D: 'depth16unorm',
  0x0000002E: 'depth24plus',
  0x0000002F: 'depth24plus-stencil8',
  0x00000030: 'depth32float',
  0x00000031: 'depth32float-stencil8',
  0x00000032: 'bc1-rgba-unorm',
  0x00000033: 'bc1-rgba-unorm-srgb',
  0x00000034: 'bc2-rgba-unorm',
  0x00000035: 'bc2-rgba-unorm-srgb',
  0x00000036: 'bc3-rgba-unorm',
  0x00000037: 'bc3-rgba-unorm-srgb',
  0x00000038: 'bc4runorm',
  0x00000039: 'bc4rsnorm',
  0x0000003A: 'bc5rgunorm',
  0x0000003B: 'bc5rgsnorm',
  0x0000003C: 'bc6hrgbufloat',
  0x0000003D: 'bc6hrgbfloat',
  0x0000003E: 'bc7-rgba-unorm',
  0x0000003F: 'bc7-rgba-unorm-srgb',
  0x00000040: 'etc2-rgb8unorm',
  0x00000041: 'etc2-rgb8unorm-srgb',
  0x00000042: 'etc2-rgb8a1unorm',
  0x00000043: 'etc2-rgb8a1unorm-srgb',
  0x00000044: 'etc2-rgba8unorm',
  0x00000045: 'etc2-rgba8unorm-srgb',
  0x00000046: 'eac-r11unorm',
  0x00000047: 'eac-r11snorm',
  0x00000048: 'eac-rg11unorm',
  0x00000049: 'eac-rg11snorm',
  0x0000004A: 'astc-4x4-unorm',
  0x0000004B: 'astc-4x4-unorm-srgb',
  0x0000004C: 'astc-5x4-unorm',
  0x0000004D: 'astc-5x4-unorm-srgb',
  0x0000004E: 'astc-5x5-unorm',
  0x0000004F: 'astc-5x5-unorm-srgb',
  0x00000050: 'astc-6x5-unorm',
  0x00000051: 'astc-6x5-unorm-srgb',
  0x00000052: 'astc-6x6-unorm',
  0x00000053: 'astc-6x6-unorm-srgb',
  0x00000054: 'astc-8x5-unorm',
  0x00000055: 'astc-8x5-unorm-srgb',
  0x00000056: 'astc-8x6-unorm',
  0x00000057: 'astc-8x6-unorm-srgb',
  0x00000058: 'astc-8x8-unorm',
  0x00000059: 'astc-8x8-unorm-srgb',
  0x0000005A: 'astc-10x5-unorm',
  0x0000005B: 'astc-10x5-unorm-srgb',
  0x0000005C: 'astc-10x6-unorm',
  0x0000005D: 'astc-10x6-unorm-srgb',
  0x0000005E: 'astc-10x8-unorm',
  0x0000005F: 'astc-10x8-unorm-srgb',
  0x00000060: 'astc-10x10-unorm',
  0x00000061: 'astc-10x10-unorm-srgb',
  0x00000062: 'astc-12x10-unorm',
  0x00000063: 'astc-12x10-unorm-srgb',
  0x00000064: 'astc-12x12-unorm',
  0x00000065: 'astc-12x12-unorm-srgb',
  0x00050000: 'r8bg8biplanar420unorm',
  0x00050001: 'r10x6bg10x6biplanar420unorm',
  0x00050002: 'r8bg8a8triplanar420unorm',
  0x00050003: 'r8bg8biplanar422unorm',
  0x00050004: 'r8bg8biplanar444unorm',
  0x00050005: 'r10x6bg10x6biplanar422unorm',
  0x00050006: 'r10x6bg10x6biplanar444unorm',
  0x00050007: 'opaqueycbcrandroid',
}

/** WGPUTextureSampleType → GPUTextureSampleType */
export const WGPUTextureSampleType: Record<number, string> = {
  0x00000000: 'binding-not-used',
  0x00000001: 'undefined',
  0x00000002: 'float',
  0x00000003: 'unfilterable-float',
  0x00000004: 'depth',
  0x00000005: 'sint',
  0x00000006: 'uint',
}

/** WGPUTextureViewDimension → GPUTextureViewDimension */
export const WGPUTextureViewDimension: Record<number, string> = {
  0x00000001: '1-d',
  0x00000002: '2-d',
  0x00000003: '2-d-array',
  0x00000004: 'cube',
  0x00000005: 'cube-array',
  0x00000006: '3-d',
}

/** WGPUVertexFormat → GPUVertexFormat */
export const WGPUVertexFormat: Record<number, string> = {
  0x00000001: 'uint8',
  0x00000002: 'uint8x2',
  0x00000003: 'uint8x4',
  0x00000004: 'sint8',
  0x00000005: 'sint8x2',
  0x00000006: 'sint8x4',
  0x00000007: 'unorm8',
  0x00000008: 'unorm8x2',
  0x00000009: 'unorm8x4',
  0x0000000A: 'snorm8',
  0x0000000B: 'snorm8x2',
  0x0000000C: 'snorm8x4',
  0x0000000D: 'uint16',
  0x0000000E: 'uint16x2',
  0x0000000F: 'uint16x4',
  0x00000010: 'sint16',
  0x00000011: 'sint16x2',
  0x00000012: 'sint16x4',
  0x00000013: 'unorm16',
  0x00000014: 'unorm16x2',
  0x00000015: 'unorm16x4',
  0x00000016: 'snorm16',
  0x00000017: 'snorm16x2',
  0x00000018: 'snorm16x4',
  0x00000019: 'float16',
  0x0000001A: 'float16x2',
  0x0000001B: 'float16x4',
  0x0000001C: 'float32',
  0x0000001D: 'float32x2',
  0x0000001E: 'float32x3',
  0x0000001F: 'float32x4',
  0x00000020: 'uint32',
  0x00000021: 'uint32x2',
  0x00000022: 'uint32x3',
  0x00000023: 'uint32x4',
  0x00000024: 'sint32',
  0x00000025: 'sint32x2',
  0x00000026: 'sint32x3',
  0x00000027: 'sint32x4',
  0x00000028: 'unorm10_10_10_2',
  0x00000029: 'unorm8x4bgra',
}

/** WGPUVertexStepMode → GPUVertexStepMode */
export const WGPUVertexStepMode: Record<number, string> = {
  0x00000001: 'vertex',
  0x00000002: 'instance',
}
