// Auto-generated by generate-wgpu-bridge.py — do not edit
// Source: src/zig/wgpu_shim/dawn/webgpu.h
//
// WASM32 struct field offsets for parsing Dawn descriptors from memory.

export interface FieldDef {
  readonly offset: number
  readonly type: 'ptr' | 'u32' | 'i32' | 'u16' | 'u64' | 'f32' | 'f64' | 'bool'
}

export type StructLayout = Record<string, FieldDef>

/** WGPUBindGroupDescriptor — 24 bytes on WASM32 */
export const WGPUBindGroupDescriptor: StructLayout = {
  nextInChain: { offset: 0, type: 'ptr' },
  label_data: { offset: 4, type: 'ptr' },
  label_length: { offset: 8, type: 'u32' },
  layout: { offset: 12, type: 'ptr' },
  entryCount: { offset: 16, type: 'u32' },
  entries: { offset: 20, type: 'ptr' },
} as const
export const WGPUBindGroupDescriptor_SIZE = 24

/** WGPUBindGroupEntry — 40 bytes on WASM32 */
export const WGPUBindGroupEntry: StructLayout = {
  nextInChain: { offset: 0, type: 'ptr' },
  binding: { offset: 4, type: 'u32' },
  buffer: { offset: 8, type: 'ptr' },
  offset: { offset: 16, type: 'u64' },
  size: { offset: 24, type: 'u64' },
  sampler: { offset: 32, type: 'ptr' },
  textureView: { offset: 36, type: 'ptr' },
} as const
export const WGPUBindGroupEntry_SIZE = 40

/** WGPUBindGroupLayoutDescriptor — 20 bytes on WASM32 */
export const WGPUBindGroupLayoutDescriptor: StructLayout = {
  nextInChain: { offset: 0, type: 'ptr' },
  label_data: { offset: 4, type: 'ptr' },
  label_length: { offset: 8, type: 'u32' },
  entryCount: { offset: 12, type: 'u32' },
  entries: { offset: 16, type: 'ptr' },
} as const
export const WGPUBindGroupLayoutDescriptor_SIZE = 20

/** WGPUBindGroupLayoutEntry — 80 bytes on WASM32 */
export const WGPUBindGroupLayoutEntry: StructLayout = {
  nextInChain: { offset: 0, type: 'ptr' },
  binding: { offset: 4, type: 'u32' },
  visibility: { offset: 8, type: 'u32' },
  bindingArraySize: { offset: 12, type: 'u32' },
  buffer_nextInChain: { offset: 16, type: 'ptr' },
  buffer_type: { offset: 20, type: 'u32' },
  buffer_hasDynamicOffset: { offset: 24, type: 'bool' },
  buffer_minBindingSize: { offset: 32, type: 'u64' },
  sampler_nextInChain: { offset: 40, type: 'ptr' },
  sampler_type: { offset: 44, type: 'u32' },
  texture_nextInChain: { offset: 48, type: 'ptr' },
  texture_sampleType: { offset: 52, type: 'u32' },
  texture_viewDimension: { offset: 56, type: 'u32' },
  texture_multisampled: { offset: 60, type: 'bool' },
  storageTexture_nextInChain: { offset: 64, type: 'ptr' },
  storageTexture_access: { offset: 68, type: 'u32' },
  storageTexture_format: { offset: 72, type: 'u32' },
  storageTexture_viewDimension: { offset: 76, type: 'u32' },
} as const
export const WGPUBindGroupLayoutEntry_SIZE = 80

/** WGPUBlendComponent — 12 bytes on WASM32 */
export const WGPUBlendComponent: StructLayout = {
  operation: { offset: 0, type: 'u32' },
  srcFactor: { offset: 4, type: 'u32' },
  dstFactor: { offset: 8, type: 'u32' },
} as const
export const WGPUBlendComponent_SIZE = 12

/** WGPUBlendState — 24 bytes on WASM32 */
export const WGPUBlendState: StructLayout = {
  color_operation: { offset: 0, type: 'u32' },
  color_srcFactor: { offset: 4, type: 'u32' },
  color_dstFactor: { offset: 8, type: 'u32' },
  alpha_operation: { offset: 12, type: 'u32' },
  alpha_srcFactor: { offset: 16, type: 'u32' },
  alpha_dstFactor: { offset: 20, type: 'u32' },
} as const
export const WGPUBlendState_SIZE = 24

/** WGPUBufferDescriptor — 40 bytes on WASM32 */
export const WGPUBufferDescriptor: StructLayout = {
  nextInChain: { offset: 0, type: 'ptr' },
  label_data: { offset: 4, type: 'ptr' },
  label_length: { offset: 8, type: 'u32' },
  usage: { offset: 16, type: 'u64' },
  size: { offset: 24, type: 'u64' },
  mappedAtCreation: { offset: 32, type: 'bool' },
} as const
export const WGPUBufferDescriptor_SIZE = 40

/** WGPUChainedStruct — 8 bytes on WASM32 */
export const WGPUChainedStruct: StructLayout = {
  next: { offset: 0, type: 'ptr' },
  sType: { offset: 4, type: 'u32' },
} as const
export const WGPUChainedStruct_SIZE = 8

/** WGPUColor — 32 bytes on WASM32 */
export const WGPUColor: StructLayout = {
  r: { offset: 0, type: 'f64' },
  g: { offset: 8, type: 'f64' },
  b: { offset: 16, type: 'f64' },
  a: { offset: 24, type: 'f64' },
} as const
export const WGPUColor_SIZE = 32

/** WGPUColorTargetState — 16 bytes on WASM32 */
export const WGPUColorTargetState: StructLayout = {
  nextInChain: { offset: 0, type: 'ptr' },
  format: { offset: 4, type: 'u32' },
  blend: { offset: 8, type: 'ptr' },
  writeMask: { offset: 12, type: 'u32' },
} as const
export const WGPUColorTargetState_SIZE = 16

/** WGPUCommandEncoderDescriptor — 12 bytes on WASM32 */
export const WGPUCommandEncoderDescriptor: StructLayout = {
  nextInChain: { offset: 0, type: 'ptr' },
  label_data: { offset: 4, type: 'ptr' },
  label_length: { offset: 8, type: 'u32' },
} as const
export const WGPUCommandEncoderDescriptor_SIZE = 12

/** WGPUComputePassDescriptor — 16 bytes on WASM32 */
export const WGPUComputePassDescriptor: StructLayout = {
  nextInChain: { offset: 0, type: 'ptr' },
  label_data: { offset: 4, type: 'ptr' },
  label_length: { offset: 8, type: 'u32' },
  timestampWrites: { offset: 12, type: 'ptr' },
} as const
export const WGPUComputePassDescriptor_SIZE = 16

/** WGPUComputePipelineDescriptor — 40 bytes on WASM32 */
export const WGPUComputePipelineDescriptor: StructLayout = {
  nextInChain: { offset: 0, type: 'ptr' },
  label_data: { offset: 4, type: 'ptr' },
  label_length: { offset: 8, type: 'u32' },
  layout: { offset: 12, type: 'ptr' },
  compute_nextInChain: { offset: 16, type: 'ptr' },
  compute_module: { offset: 20, type: 'ptr' },
  compute_entryPoint_data: { offset: 24, type: 'ptr' },
  compute_entryPoint_length: { offset: 28, type: 'u32' },
  compute_constantCount: { offset: 32, type: 'u32' },
  compute_constants: { offset: 36, type: 'ptr' },
} as const
export const WGPUComputePipelineDescriptor_SIZE = 40

/** WGPUDepthStencilState — 68 bytes on WASM32 */
export const WGPUDepthStencilState: StructLayout = {
  nextInChain: { offset: 0, type: 'ptr' },
  format: { offset: 4, type: 'u32' },
  depthWriteEnabled: { offset: 8, type: 'u32' },
  depthCompare: { offset: 12, type: 'u32' },
  stencilFront_compare: { offset: 16, type: 'u32' },
  stencilFront_failOp: { offset: 20, type: 'u32' },
  stencilFront_depthFailOp: { offset: 24, type: 'u32' },
  stencilFront_passOp: { offset: 28, type: 'u32' },
  stencilBack_compare: { offset: 32, type: 'u32' },
  stencilBack_failOp: { offset: 36, type: 'u32' },
  stencilBack_depthFailOp: { offset: 40, type: 'u32' },
  stencilBack_passOp: { offset: 44, type: 'u32' },
  stencilReadMask: { offset: 48, type: 'u32' },
  stencilWriteMask: { offset: 52, type: 'u32' },
  depthBias: { offset: 56, type: 'i32' },
  depthBiasSlopeScale: { offset: 60, type: 'f32' },
  depthBiasClamp: { offset: 64, type: 'f32' },
} as const
export const WGPUDepthStencilState_SIZE = 68

/** WGPUExtent3D — 12 bytes on WASM32 */
export const WGPUExtent3D: StructLayout = {
  width: { offset: 0, type: 'u32' },
  height: { offset: 4, type: 'u32' },
  depthOrArrayLayers: { offset: 8, type: 'u32' },
} as const
export const WGPUExtent3D_SIZE = 12

/** WGPUFragmentState — 32 bytes on WASM32 */
export const WGPUFragmentState: StructLayout = {
  nextInChain: { offset: 0, type: 'ptr' },
  module: { offset: 4, type: 'ptr' },
  entryPoint_data: { offset: 8, type: 'ptr' },
  entryPoint_length: { offset: 12, type: 'u32' },
  constantCount: { offset: 16, type: 'u32' },
  constants: { offset: 20, type: 'ptr' },
  targetCount: { offset: 24, type: 'u32' },
  targets: { offset: 28, type: 'ptr' },
} as const
export const WGPUFragmentState_SIZE = 32

/** WGPUImageCopyBuffer — 32 bytes on WASM32 */
export const WGPUImageCopyBuffer: StructLayout = {
  nextInChain: { offset: 0, type: 'ptr' },
  layout_nextInChain: { offset: 4, type: 'ptr' },
  layout_offset: { offset: 8, type: 'u64' },
  layout_bytesPerRow: { offset: 16, type: 'u32' },
  layout_rowsPerImage: { offset: 20, type: 'u32' },
  buffer: { offset: 24, type: 'ptr' },
} as const
export const WGPUImageCopyBuffer_SIZE = 32

/** WGPUImageCopyTexture — 28 bytes on WASM32 */
export const WGPUImageCopyTexture: StructLayout = {
  nextInChain: { offset: 0, type: 'ptr' },
  texture: { offset: 4, type: 'ptr' },
  mipLevel: { offset: 8, type: 'u32' },
  origin_x: { offset: 12, type: 'u32' },
  origin_y: { offset: 16, type: 'u32' },
  origin_z: { offset: 20, type: 'u32' },
  aspect: { offset: 24, type: 'u32' },
} as const
export const WGPUImageCopyTexture_SIZE = 28

/** WGPUMultisampleState — 16 bytes on WASM32 */
export const WGPUMultisampleState: StructLayout = {
  nextInChain: { offset: 0, type: 'ptr' },
  count: { offset: 4, type: 'u32' },
  mask: { offset: 8, type: 'u32' },
  alphaToCoverageEnabled: { offset: 12, type: 'bool' },
} as const
export const WGPUMultisampleState_SIZE = 16

/** WGPUPipelineLayoutDescriptor — 24 bytes on WASM32 */
export const WGPUPipelineLayoutDescriptor: StructLayout = {
  nextInChain: { offset: 0, type: 'ptr' },
  label_data: { offset: 4, type: 'ptr' },
  label_length: { offset: 8, type: 'u32' },
  bindGroupLayoutCount: { offset: 12, type: 'u32' },
  bindGroupLayouts: { offset: 16, type: 'ptr' },
  immediateSize: { offset: 20, type: 'u32' },
} as const
export const WGPUPipelineLayoutDescriptor_SIZE = 24

/** WGPUPrimitiveState — 24 bytes on WASM32 */
export const WGPUPrimitiveState: StructLayout = {
  nextInChain: { offset: 0, type: 'ptr' },
  topology: { offset: 4, type: 'u32' },
  stripIndexFormat: { offset: 8, type: 'u32' },
  frontFace: { offset: 12, type: 'u32' },
  cullMode: { offset: 16, type: 'u32' },
  unclippedDepth: { offset: 20, type: 'bool' },
} as const
export const WGPUPrimitiveState_SIZE = 24

/** WGPUQuerySetDescriptor — 20 bytes on WASM32 */
export const WGPUQuerySetDescriptor: StructLayout = {
  nextInChain: { offset: 0, type: 'ptr' },
  label_data: { offset: 4, type: 'ptr' },
  label_length: { offset: 8, type: 'u32' },
  type: { offset: 12, type: 'u32' },
  count: { offset: 16, type: 'u32' },
} as const
export const WGPUQuerySetDescriptor_SIZE = 20

/** WGPURenderPassColorAttachment — 56 bytes on WASM32 */
export const WGPURenderPassColorAttachment: StructLayout = {
  nextInChain: { offset: 0, type: 'ptr' },
  view: { offset: 4, type: 'ptr' },
  depthSlice: { offset: 8, type: 'u32' },
  resolveTarget: { offset: 12, type: 'ptr' },
  loadOp: { offset: 16, type: 'u32' },
  storeOp: { offset: 20, type: 'u32' },
  clearValue_r: { offset: 24, type: 'f64' },
  clearValue_g: { offset: 32, type: 'f64' },
  clearValue_b: { offset: 40, type: 'f64' },
  clearValue_a: { offset: 48, type: 'f64' },
} as const
export const WGPURenderPassColorAttachment_SIZE = 56

/** WGPURenderPassDepthStencilAttachment — 36 bytes on WASM32 */
export const WGPURenderPassDepthStencilAttachment: StructLayout = {
  view: { offset: 0, type: 'ptr' },
  depthLoadOp: { offset: 4, type: 'u32' },
  depthStoreOp: { offset: 8, type: 'u32' },
  depthClearValue: { offset: 12, type: 'f32' },
  depthReadOnly: { offset: 16, type: 'bool' },
  stencilLoadOp: { offset: 20, type: 'u32' },
  stencilStoreOp: { offset: 24, type: 'u32' },
  stencilClearValue: { offset: 28, type: 'u32' },
  stencilReadOnly: { offset: 32, type: 'bool' },
} as const
export const WGPURenderPassDepthStencilAttachment_SIZE = 36

/** WGPURenderPassDescriptor — 32 bytes on WASM32 */
export const WGPURenderPassDescriptor: StructLayout = {
  nextInChain: { offset: 0, type: 'ptr' },
  label_data: { offset: 4, type: 'ptr' },
  label_length: { offset: 8, type: 'u32' },
  colorAttachmentCount: { offset: 12, type: 'u32' },
  colorAttachments: { offset: 16, type: 'ptr' },
  depthStencilAttachment: { offset: 20, type: 'ptr' },
  occlusionQuerySet: { offset: 24, type: 'ptr' },
  timestampWrites: { offset: 28, type: 'ptr' },
} as const
export const WGPURenderPassDescriptor_SIZE = 32

/** WGPURenderPipelineDescriptor — 96 bytes on WASM32 */
export const WGPURenderPipelineDescriptor: StructLayout = {
  nextInChain: { offset: 0, type: 'ptr' },
  label_data: { offset: 4, type: 'ptr' },
  label_length: { offset: 8, type: 'u32' },
  layout: { offset: 12, type: 'ptr' },
  vertex_nextInChain: { offset: 16, type: 'ptr' },
  vertex_module: { offset: 20, type: 'ptr' },
  vertex_entryPoint_data: { offset: 24, type: 'ptr' },
  vertex_entryPoint_length: { offset: 28, type: 'u32' },
  vertex_constantCount: { offset: 32, type: 'u32' },
  vertex_constants: { offset: 36, type: 'ptr' },
  vertex_bufferCount: { offset: 40, type: 'u32' },
  vertex_buffers: { offset: 44, type: 'ptr' },
  primitive_nextInChain: { offset: 48, type: 'ptr' },
  primitive_topology: { offset: 52, type: 'u32' },
  primitive_stripIndexFormat: { offset: 56, type: 'u32' },
  primitive_frontFace: { offset: 60, type: 'u32' },
  primitive_cullMode: { offset: 64, type: 'u32' },
  primitive_unclippedDepth: { offset: 68, type: 'bool' },
  depthStencil: { offset: 72, type: 'ptr' },
  multisample_nextInChain: { offset: 76, type: 'ptr' },
  multisample_count: { offset: 80, type: 'u32' },
  multisample_mask: { offset: 84, type: 'u32' },
  multisample_alphaToCoverageEnabled: { offset: 88, type: 'bool' },
  fragment: { offset: 92, type: 'ptr' },
} as const
export const WGPURenderPipelineDescriptor_SIZE = 96

/** WGPUSamplerDescriptor — 52 bytes on WASM32 */
export const WGPUSamplerDescriptor: StructLayout = {
  nextInChain: { offset: 0, type: 'ptr' },
  label_data: { offset: 4, type: 'ptr' },
  label_length: { offset: 8, type: 'u32' },
  addressModeU: { offset: 12, type: 'u32' },
  addressModeV: { offset: 16, type: 'u32' },
  addressModeW: { offset: 20, type: 'u32' },
  magFilter: { offset: 24, type: 'u32' },
  minFilter: { offset: 28, type: 'u32' },
  mipmapFilter: { offset: 32, type: 'u32' },
  lodMinClamp: { offset: 36, type: 'f32' },
  lodMaxClamp: { offset: 40, type: 'f32' },
  compare: { offset: 44, type: 'u32' },
  maxAnisotropy: { offset: 48, type: 'u16' },
} as const
export const WGPUSamplerDescriptor_SIZE = 52

/** WGPUShaderModuleDescriptor — 12 bytes on WASM32 */
export const WGPUShaderModuleDescriptor: StructLayout = {
  nextInChain: { offset: 0, type: 'ptr' },
  label_data: { offset: 4, type: 'ptr' },
  label_length: { offset: 8, type: 'u32' },
} as const
export const WGPUShaderModuleDescriptor_SIZE = 12

/** WGPUShaderSourceWGSL — 16 bytes on WASM32 */
export const WGPUShaderSourceWGSL: StructLayout = {
  chain_next: { offset: 0, type: 'ptr' },
  chain_sType: { offset: 4, type: 'u32' },
  code_data: { offset: 8, type: 'ptr' },
  code_length: { offset: 12, type: 'u32' },
} as const
export const WGPUShaderSourceWGSL_SIZE = 16

/** WGPUStencilFaceState — 16 bytes on WASM32 */
export const WGPUStencilFaceState: StructLayout = {
  compare: { offset: 0, type: 'u32' },
  failOp: { offset: 4, type: 'u32' },
  depthFailOp: { offset: 8, type: 'u32' },
  passOp: { offset: 12, type: 'u32' },
} as const
export const WGPUStencilFaceState_SIZE = 16

/** WGPUStringView — 8 bytes on WASM32 */
export const WGPUStringView: StructLayout = {
  data: { offset: 0, type: 'ptr' },
  length: { offset: 4, type: 'u32' },
} as const
export const WGPUStringView_SIZE = 8

/** WGPUTextureDescriptor — 64 bytes on WASM32 */
export const WGPUTextureDescriptor: StructLayout = {
  nextInChain: { offset: 0, type: 'ptr' },
  label_data: { offset: 4, type: 'ptr' },
  label_length: { offset: 8, type: 'u32' },
  usage: { offset: 16, type: 'u64' },
  dimension: { offset: 24, type: 'u32' },
  width: { offset: 28, type: 'u32' },
  height: { offset: 32, type: 'u32' },
  depthOrArrayLayers: { offset: 36, type: 'u32' },
  format: { offset: 40, type: 'u32' },
  mipLevelCount: { offset: 44, type: 'u32' },
  sampleCount: { offset: 48, type: 'u32' },
  viewFormatCount: { offset: 52, type: 'u32' },
  viewFormats: { offset: 56, type: 'ptr' },
} as const
export const WGPUTextureDescriptor_SIZE = 64

/** WGPUTextureViewDescriptor — 48 bytes on WASM32 */
export const WGPUTextureViewDescriptor: StructLayout = {
  nextInChain: { offset: 0, type: 'ptr' },
  label_data: { offset: 4, type: 'ptr' },
  label_length: { offset: 8, type: 'u32' },
  format: { offset: 12, type: 'u32' },
  dimension: { offset: 16, type: 'u32' },
  baseMipLevel: { offset: 20, type: 'u32' },
  mipLevelCount: { offset: 24, type: 'u32' },
  baseArrayLayer: { offset: 28, type: 'u32' },
  arrayLayerCount: { offset: 32, type: 'u32' },
  aspect: { offset: 36, type: 'u32' },
  usage: { offset: 40, type: 'u64' },
} as const
export const WGPUTextureViewDescriptor_SIZE = 48

/** WGPUVertexAttribute — 24 bytes on WASM32 */
export const WGPUVertexAttribute: StructLayout = {
  format: { offset: 0, type: 'u32' },
  offset: { offset: 8, type: 'u64' },
  shaderLocation: { offset: 16, type: 'u32' },
} as const
export const WGPUVertexAttribute_SIZE = 24

/** WGPUVertexBufferLayout — 24 bytes on WASM32 */
export const WGPUVertexBufferLayout: StructLayout = {
  nextInChain: { offset: 0, type: 'ptr' },
  stepMode: { offset: 4, type: 'u32' },
  arrayStride: { offset: 8, type: 'u64' },
  attributeCount: { offset: 16, type: 'u32' },
  attributes: { offset: 20, type: 'ptr' },
} as const
export const WGPUVertexBufferLayout_SIZE = 24

/** WGPUVertexState — 32 bytes on WASM32 */
export const WGPUVertexState: StructLayout = {
  nextInChain: { offset: 0, type: 'ptr' },
  module: { offset: 4, type: 'ptr' },
  entryPoint_data: { offset: 8, type: 'ptr' },
  entryPoint_length: { offset: 12, type: 'u32' },
  constantCount: { offset: 16, type: 'u32' },
  constants: { offset: 20, type: 'ptr' },
  bufferCount: { offset: 24, type: 'u32' },
  buffers: { offset: 28, type: 'ptr' },
} as const
export const WGPUVertexState_SIZE = 32
