#!/usr/bin/env python3
"""
Generate WIT interface declarations for the GL functions Skia's
WebGL Ganesh backend needs.

Reads the generated emscripten_gl_shim.h and extracts GL function
declarations, then maps C types to WIT types.

Same approach as generate-wgpu-wit.py — derives signatures from the
shim header rather than maintaining a hand-coded signature database.

Usage:
    python3 scripts/generate-gl-wit.py

Prerequisites:
    Run generate-gl-shim.py first (it generates emscripten_gl_shim.h).

Outputs:
    wit/gl.wit — WIT interface with GL function imports
"""

import re
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
PKG_ROOT = SCRIPT_DIR.parent
SHIM_H = PKG_ROOT / "src" / "zig" / "gl_shim" / "emscripten_gl_shim.h"

# ── C type → WIT type mapping ──

C_TO_WIT = {
    "void": "void",
    "GLenum": "u32",
    "GLuint": "u32",
    "GLint": "s32",
    "GLsizei": "s32",
    "GLfloat": "f32",
    "GLclampf": "f32",
    "GLboolean": "u32",   # GL uses unsigned char but WIT needs u32
    "GLbitfield": "u32",
    "GLchar": "u32",
    "GLubyte": "u32",
    "GLintptr": "u32",    # pointer-sized in WASM32
    "GLsizeiptr": "u32",
    "GLint64": "s64",
    "GLuint64": "u64",
    "GLsync": "u32",      # opaque pointer → u32 in WASM
}


def c_type_to_wit(c_type: str) -> str:
    """Map a C type to a WIT type."""
    t = c_type.strip()

    # Pointer types → u32 (WASM pointer)
    if "*" in t:
        return "u32"

    # Remove const
    clean = t.replace("const", "").strip()

    if clean in C_TO_WIT:
        return C_TO_WIT[clean]

    # Fallback
    return "u32"


def to_wit_name(gl_name: str) -> str:
    """Convert GL function name like ActiveTexture to WIT kebab-case."""
    # Insert hyphens before uppercase letters
    result = []
    for i, ch in enumerate(gl_name):
        if ch.isupper() and i > 0:
            prev_upper = gl_name[i - 1].isupper()
            next_lower = (i + 1 < len(gl_name)) and gl_name[i + 1].islower()
            if not prev_upper or next_lower:
                result.append("-")
        result.append(ch.lower())
    return "".join(result)


WIT_KEYWORDS = {"type", "use", "enum", "flags", "record", "variant", "resource",
                "own", "borrow", "list", "option", "result", "string", "tuple",
                "char", "bool", "u8", "u16", "u32", "u64", "s8", "s16", "s32",
                "s64", "f32", "f64", "interface", "world", "import", "export",
                "include", "package", "static", "func", "ref"}


def escape_wit_param(name: str) -> str:
    if name in WIT_KEYWORDS:
        return f"%{name}"
    return name


def parse_params(params_str: str) -> list[tuple[str, str]]:
    """Parse C parameter list into (name, wit_type) pairs."""
    if not params_str or params_str.strip() in ("void", ""):
        return []

    result = []
    for param in params_str.split(","):
        param = param.strip()
        if not param:
            continue

        parts = param.replace("*", "* ").split()
        if not parts:
            continue

        param_name = parts[-1].strip("*").strip()
        c_type = " ".join(parts[:-1]).strip()
        if not c_type:
            c_type = param_name
            param_name = "arg"

        wit_type = c_type_to_wit(c_type)

        # Clean param name
        param_name = re.sub(r'[^a-zA-Z0-9_]', '', param_name)
        if not param_name:
            param_name = "arg"
        # camelCase → kebab-case
        param_name = re.sub(r'([a-z])([A-Z])', r'\1-\2', param_name).lower()

        result.append((param_name, wit_type))

    return result


def extract_functions(shim_h: Path) -> list[tuple[str, str, str]]:
    """Extract GL function declarations from emscripten_gl_shim.h.

    Returns list of (return_type, short_name, params_str).
    short_name is like "ActiveTexture" (without emscripten_gl prefix).
    """
    content = shim_h.read_text()
    functions = []

    # Match: import_name("emscripten_glName")) ReturnType __wasm_import_gl_Name(params);
    pattern = re.compile(
        r'import_name\("emscripten_gl(\w+)"\)\)\)\s+'
        r'([\w\s\*]+?)\s+'
        r'__wasm_import_gl_\w+\s*'
        r'\(([^)]*)\)\s*;',
        re.MULTILINE
    )

    for m in pattern.finditer(content):
        short_name = m.group(1)
        ret_type = m.group(2).strip()
        params = m.group(3).strip()
        functions.append((ret_type, short_name, params))

    return functions


def main():
    if not SHIM_H.exists():
        print(f"Error: {SHIM_H} not found")
        print("  Run generate-gl-shim.py first to generate the GL shim header.")
        sys.exit(1)

    functions = extract_functions(SHIM_H)
    print(f"Extracted {len(functions)} GL functions from {SHIM_H.name}")

    # Generate WIT
    lines = [
        "// Auto-generated by generate-gl-wit.py — do not edit",
        "// GL functions required by Skia's WebGL Ganesh backend",
        "//",
        f"// {len(functions)} functions extracted from emscripten_gl_shim.h",
        "",
        "interface gl {",
    ]

    for ret_type, short_name, params_str in functions:
        wit_name = to_wit_name(short_name)
        params = parse_params(params_str)
        param_str = ", ".join(f"{escape_wit_param(n)}: {t}" for n, t in params)
        wit_ret = c_type_to_wit(ret_type)

        if wit_ret == "void":
            lines.append(f"    {wit_name}: func({param_str});")
        else:
            lines.append(f"    {wit_name}: func({param_str}) -> {wit_ret};")

    lines.append("}")

    wit_content = "\n".join(lines) + "\n"

    # Write output
    wit_path = PKG_ROOT / "wit" / "gl.wit"
    with open(wit_path, "w") as f:
        f.write(wit_content)

    print(f"Generated {wit_path}")
    print(f"  {len(functions)} functions")


if __name__ == "__main__":
    main()
