export { calcRootCode } from './calcRootCode'
export { solveHorizPoly, solveVertPoly } from './solveQuadratic'
export { calcCoverage } from './calcCoverage'
export { slugRender } from './slugFragment'
export { slugDilate } from './slugDilate'
export { buildSlugVertexNodes } from './slugVertex'
