// Fixture exercising the zzfx() call shapes the codelens-service protocol
// must agree on across the Rust sidecar and the TypeScript client. See
// golden.findings.json — the canonical expected `Finding[]` output for this
// exact file, generated by running the sidecar directly against it and
// reviewed by hand. If you touch this file, regenerate the golden JSON too
// (see tools/codelens-service/CLAUDE.md).

const laserPreset = [1, 0.05, 220, 0, 0.02]

export function playLaser() {
  zzfx(...laserPreset)
}

// Type-annotated declarator — the shape that caught a real bug: defRange
// must cover only the array literal, never "explosionPreset: number[] = ".
// A write-back that (incorrectly) replaced the whole declarator's text
// would delete the name and type annotation here.
const explosionPreset: number[] = [0.6, 0, 100, 0.02, 0.15]

export function playExplosion() {
  zzfx(...explosionPreset)
}

export function playBeep() {
  zzfx(1, 0.1, 440)
}

export function playViaMember() {
  sfx.zzfx(1, -0.5, 0.2)
}

export function playUnresolvedPreset(myPreset: number[]) {
  zzfx(myPreset)
}

// zzfx(9, 9, 9) — commented out, must never appear in findings
export function silence() {
  zzfx()
}

// zzfxm.song — literal array form (first arg isn't an identifier, so no
// varRef) and named-variable form (varRef resolves to laserSong below).
const laserSong = [[[1.5, 0, 220]], [[0, 0, 0, 1]], [1]]

export function playInlineSong() {
  zzfxm([[[1, 0, 440]], [[0, 0, 0, 1]], [1]])
}

export function playLaserSong() {
  zzfxm(laserSong)
}

// zzfxm.song — spread-of-identifier form, `zzfxM(...laserSong)`: the
// canonical zzfxm-tool output shape. Resolves the SAME varRef as the bare
// identifier call above (sidecar/src/parse.rs::extract_zzfxm_call).
export function playLaserSongSpread() {
  zzfxM(...laserSong)
}

// audio.file — direct string argument.
export function playExplosionSfx() {
  new Audio('explosion.mp3').play()
}

// audio.file — Howler-style nested strings (array inside object inside a
// call): two findings sharing this one call's range, one per source file.
export function playAmbient() {
  new Howl({ src: ['ambient.ogg', 'ambient.mp3'] }).play()
}

// audio.file — Wad (github.com/rserota/wad) file-mode source: a string
// nested in a new-expression's object arg, the same generic shape as the
// Howler case above. No dedicated scanner, pinned here by name.
export function playJump() {
  new Wad({ source: 'sounds/jump.wav' }).play()
}

// Wad synthesis-mode source ('sine', 'square', ...) has no audio extension,
// so it's correctly NOT an audio.file finding — but it IS a wad.synth
// finding now (a separate kind: no file is loaded, so the string itself
// never gets an audio.file entry either way). Kept uncommented (not a
// comment-exclusion case) so the golden fixture's full-array equality
// proves both the audio.file negative and the wad.synth positive, not just
// implies either.
export function beep() {
  new Wad({ source: 'sine' }).play()
}

// audio.file — Wad convolution reverb: the impulse-response FILE sits two
// object levels down ({ reverb: { impulse } }); the depth-agnostic walk
// reaches it with no Wad-specific code. One finding: 'ir.wav'.
export function playWithReverb() {
  new Wad({ reverb: { impulse: 'ir.wav' } }).play()
}

// audio.file — Wad.SoundIterator's files array mixes a real path with an
// inline synthesis Wad. ONE audio.file finding ('riff.mp3'), attributed to
// the SoundIterator new-expression — plus ONE wad.synth finding for the
// inner new Wad({source:'square'}), attributed to ITS OWN new-expression
// (wad.synth's scanner fires on any matching new Wad(...) wherever it
// appears, however deeply nested, the same depth-agnostic posture
// audio.file's string walk already has).
export function playIterated() {
  new Wad.SoundIterator({ files: ['riff.mp3', new Wad({ source: 'square' })] }).play()
}

// The REST of Wad's synthesis vocabulary — oscillator shapes, noise, live
// mic input. sawtooth/triangle/noise are wad.synth findings (same as
// 'sine' above); NONE of the four are audio.file findings (no file is
// loaded); 'mic' is live input and is the one keyword that produces NO
// finding of EITHER kind — proven by the golden full-array equality.
export function synthVoices() {
  new Wad({ source: 'sawtooth' }).play()
  new Wad({ source: 'triangle' }).play()
  new Wad({ source: 'noise' }).play()
  new Wad({ source: 'mic' }).play()
}

// An audio sprite alone maps names to [start, duration] SEGMENTS of the
// source — numbers, not files. NOT a finding.
export function spriteOnly() {
  new Wad({ sprite: { hello: [0, 0.4] } }).play()
}

// A stock preset via member expression — no string literal in the
// arguments at all. NOT a finding.
export function hiHat() {
  new Wad(Wad.presets.hiHatClosed).play()
}

// wad.synth — a fresh oscillator keyword not otherwise exercised above
// ('square', vs. sine/sawtooth/triangle/noise covered by beep/synthVoices).
export function playSquareSynth() {
  new Wad({ source: 'square' }).play()
}

// wad.synth — bare-identifier var-ref form. The sidecar can't know
// statically whether an identifier's declaration IS an oscillator config
// without resolving it, so (mirroring zzfx/zzfxm's varRef division of
// labor) it always emits a wad.synth finding with varRef set for a
// bare-identifier Wad argument; validating the resolved text is the TS
// client's job (see wadSynthResolver.ts).
const laserOsc = { source: 'noise' }
export function playLaserOsc() {
  new Wad(laserOsc).play()
}

// tone.synth — Tone.js (tonejs.github.io): detected by DESCENDING from the
// outermost triggerAttackRelease call through any number of intervening
// chain calls (here, one .toDestination()) down to the `new Tone.<Class>`
// constructor — the mirror image of audio.file's walk UP to the nearest
// enclosing call.
export function playTone() {
  new Tone.Synth().toDestination().triggerAttackRelease('C4', '8n')
}

// tone.synth — NoiseSynth has no note, just (duration, time?, velocity?).
// The finding's argRange still covers the whole triggerAttackRelease
// argument list, same as every other class.
export function playNoise() {
  new Tone.NoiseSynth().toDestination().triggerAttackRelease('8n')
}

// tone.synth — PolySynth with an explicit allowlisted voice type
// (Tone.FMSynth, a bare member-expression reference, not a `new` call) and
// a chord: triggerAttackRelease's first argument is an ARRAY of note
// literals rather than a single note.
export function playChord() {
  new Tone.PolySynth(Tone.FMSynth).toDestination().triggerAttackRelease(['C4', 'E4', 'G4'], '4n')
}

// tone.synth negative — the note comes from a parameter, not a static
// literal. Detection here is fully-static-or-nothing (no varRef
// indirection at all, unlike wad.synth's permissive posture) — an
// unresolvable note just means no finding, full stop.
export function playDynamicNote(note: string) {
  new Tone.Synth().toDestination().triggerAttackRelease(note, '8n')
}
