// Fixture exercising the zzfx() call shapes the codelens-service protocol
// must agree on across the Rust sidecar and the TypeScript client. See
// golden.findings.json — the canonical expected `Finding[]` output for this
// exact file, generated by running the sidecar directly against it and
// reviewed by hand. If you touch this file, regenerate the golden JSON too
// (see tools/codelens-service/CLAUDE.md).

const laserPreset = [1, 0.05, 220, 0, 0.02]

export function playLaser() {
  zzfx(...laserPreset)
}

// Type-annotated declarator — the shape that caught a real bug: defRange
// must cover only the array literal, never "explosionPreset: number[] = ".
// A write-back that (incorrectly) replaced the whole declarator's text
// would delete the name and type annotation here.
const explosionPreset: number[] = [0.6, 0, 100, 0.02, 0.15]

export function playExplosion() {
  zzfx(...explosionPreset)
}

export function playBeep() {
  zzfx(1, 0.1, 440)
}

export function playViaMember() {
  sfx.zzfx(1, -0.5, 0.2)
}

export function playUnresolvedPreset(myPreset: number[]) {
  zzfx(myPreset)
}

// zzfx(9, 9, 9) — commented out, must never appear in findings
export function silence() {
  zzfx()
}

// zzfxm.song — literal array form (first arg isn't an identifier, so no
// varRef) and named-variable form (varRef resolves to laserSong below).
const laserSong = [[[1.5, 0, 220]], [[0, 0, 0, 1]], [1]]

export function playInlineSong() {
  zzfxm([[[1, 0, 440]], [[0, 0, 0, 1]], [1]])
}

export function playLaserSong() {
  zzfxm(laserSong)
}

// zzfxm.song — spread-of-identifier form, `zzfxM(...laserSong)`: the
// canonical zzfxm-tool output shape. Resolves the SAME varRef as the bare
// identifier call above (sidecar/src/parse.rs::extract_zzfxm_call).
export function playLaserSongSpread() {
  zzfxM(...laserSong)
}

// audio.file — direct string argument.
export function playExplosionSfx() {
  new Audio('explosion.mp3').play()
}

// audio.file — Howler-style nested strings (array inside object inside a
// call): two findings sharing this one call's range, one per source file.
export function playAmbient() {
  new Howl({ src: ['ambient.ogg', 'ambient.mp3'] }).play()
}

// audio.file — Wad (github.com/rserota/wad) file-mode source: a string
// nested in a new-expression's object arg, the same generic shape as the
// Howler case above. No dedicated scanner, pinned here by name.
export function playJump() {
  new Wad({ source: 'sounds/jump.wav' }).play()
}

// Wad synthesis-mode source ('sine', 'square', ...) has no audio extension
// — correctly NOT a finding. Kept uncommented (not a comment-exclusion
// case) so the golden fixture's full-array equality proves the negative,
// not just implies it.
export function beep() {
  new Wad({ source: 'sine' }).play()
}

// audio.file — Wad convolution reverb: the impulse-response FILE sits two
// object levels down ({ reverb: { impulse } }); the depth-agnostic walk
// reaches it with no Wad-specific code. One finding: 'ir.wav'.
export function playWithReverb() {
  new Wad({ reverb: { impulse: 'ir.wav' } }).play()
}

// audio.file — Wad.SoundIterator's files array mixes a real path with an
// inline synthesis Wad. Exactly ONE finding ('riff.mp3'), attributed to
// the SoundIterator new-expression; the inner new Wad({source:'square'})
// is synthesis and contributes nothing.
export function playIterated() {
  new Wad.SoundIterator({ files: ['riff.mp3', new Wad({ source: 'square' })] }).play()
}

// The REST of Wad's synthesis vocabulary — oscillator shapes, noise, live
// mic input — all name no file; NOT findings, proven by the golden
// full-array equality (same treatment as 'sine' above).
export function synthVoices() {
  new Wad({ source: 'sawtooth' }).play()
  new Wad({ source: 'triangle' }).play()
  new Wad({ source: 'noise' }).play()
  new Wad({ source: 'mic' }).play()
}

// An audio sprite alone maps names to [start, duration] SEGMENTS of the
// source — numbers, not files. NOT a finding.
export function spriteOnly() {
  new Wad({ sprite: { hello: [0, 0.4] } }).play()
}

// A stock preset via member expression — no string literal in the
// arguments at all. NOT a finding.
export function hiHat() {
  new Wad(Wad.presets.hiHatClosed).play()
}
