// Fixture exercising the zzfx() call shapes the codelens-service protocol
// must agree on across the Rust sidecar and the TypeScript client. See
// golden.findings.json — the canonical expected `Finding[]` output for this
// exact file, generated by running the sidecar directly against it and
// reviewed by hand. If you touch this file, regenerate the golden JSON too
// (see tools/codelens-service/CLAUDE.md).

const laserPreset = [1, 0.05, 220, 0, 0.02]

export function playLaser() {
  zzfx(...laserPreset)
}

export function playBeep() {
  zzfx(1, 0.1, 440)
}

export function playViaMember() {
  sfx.zzfx(1, -0.5, 0.2)
}

export function playUnresolvedPreset(myPreset: number[]) {
  zzfx(myPreset)
}

// zzfx(9, 9, 9) — commented out, must never appear in findings
export function silence() {
  zzfx()
}
