// Auto-generated stub Emscripten WebGL header for Zig/WASM build.
// Declares emscripten_gl* functions that Skia's GrGLAssembleWebGLInterfaceAutogen.cpp expects.
// Implementations are in emscripten_gl_shim.c, which delegates to WIT imports.

#pragma once

#include <stdint.h>
#include <stddef.h>

// GL type definitions (matching OpenGL ES 3.2)
typedef unsigned int GLenum;
typedef unsigned char GLboolean;
typedef unsigned int GLbitfield;
typedef void GLvoid;
typedef int GLint;
typedef unsigned int GLuint;
typedef int GLsizei;
typedef float GLfloat;
typedef float GLclampf;
typedef char GLchar;
typedef unsigned char GLubyte;
typedef intptr_t GLintptr;
typedef size_t GLsizeiptr;
typedef int64_t GLint64;
typedef uint64_t GLuint64;
typedef void* GLsync;

#define GL_FALSE 0
#define GL_TRUE 1

extern void emscripten_glActiveTexture(GLenum texture);
extern void emscripten_glAttachShader(GLuint program, GLuint shader);
extern void emscripten_glBeginQuery(GLenum target, GLuint id);
extern void emscripten_glBindAttribLocation(GLuint program, GLuint index, const GLchar* name);
extern void emscripten_glBindBuffer(GLenum target, GLuint buffer);
extern void emscripten_glBindFramebuffer(GLenum target, GLuint framebuffer);
extern void emscripten_glBindRenderbuffer(GLenum target, GLuint renderbuffer);
extern void emscripten_glBindSampler(GLuint unit, GLuint sampler);
extern void emscripten_glBindTexture(GLenum target, GLuint texture);
extern void emscripten_glBindVertexArray(GLuint array);
extern void emscripten_glBlendColor(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
extern void emscripten_glBlendEquation(GLenum mode);
extern void emscripten_glBlendFunc(GLenum sfactor, GLenum dfactor);
extern void emscripten_glBlitFramebuffer(GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter);
extern void emscripten_glBufferData(GLenum target, GLsizeiptr size, const void* data, GLenum usage);
extern void emscripten_glBufferSubData(GLenum target, GLintptr offset, GLsizeiptr size, const void* data);
extern GLenum emscripten_glCheckFramebufferStatus(GLenum target);
extern void emscripten_glClear(GLbitfield mask);
extern void emscripten_glClearColor(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
extern void emscripten_glClearStencil(GLint s);
extern GLenum emscripten_glClientWaitSync(GLsync sync, GLbitfield flags, GLuint64 timeout);
extern void emscripten_glColorMask(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha);
extern void emscripten_glCompileShader(GLuint shader);
extern void emscripten_glCompressedTexImage2D(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const void* data);
extern void emscripten_glCompressedTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const void* data);
extern void emscripten_glCopyBufferSubData(GLenum readTarget, GLenum writeTarget, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size);
extern void emscripten_glCopyTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height);
extern GLuint emscripten_glCreateProgram(void);
extern GLuint emscripten_glCreateShader(GLenum type);
extern void emscripten_glCullFace(GLenum mode);
extern void emscripten_glDeleteBuffers(GLsizei n, const GLuint* buffers);
extern void emscripten_glDeleteFramebuffers(GLsizei n, const GLuint* framebuffers);
extern void emscripten_glDeleteProgram(GLuint program);
extern void emscripten_glDeleteQueries(GLsizei n, const GLuint* ids);
extern void emscripten_glDeleteRenderbuffers(GLsizei n, const GLuint* renderbuffers);
extern void emscripten_glDeleteSamplers(GLsizei n, const GLuint* samplers);
extern void emscripten_glDeleteShader(GLuint shader);
extern void emscripten_glDeleteSync(GLsync sync);
extern void emscripten_glDeleteTextures(GLsizei n, const GLuint* textures);
extern void emscripten_glDeleteVertexArrays(GLsizei n, const GLuint* arrays);
extern void emscripten_glDepthMask(GLboolean flag);
extern void emscripten_glDisable(GLenum cap);
extern void emscripten_glDisableVertexAttribArray(GLuint index);
extern void emscripten_glDrawArrays(GLenum mode, GLint first, GLsizei count);
extern void emscripten_glDrawArraysInstanced(GLenum mode, GLint first, GLsizei count, GLsizei instancecount);
extern void emscripten_glDrawArraysInstancedBaseInstance(GLenum mode, GLint first, GLsizei count, GLsizei instancecount, GLuint baseinstance);
extern void emscripten_glDrawBuffers(GLsizei n, const GLenum* bufs);
extern void emscripten_glDrawElements(GLenum mode, GLsizei count, GLenum type, const void* indices);
extern void emscripten_glDrawElementsInstanced(GLenum mode, GLsizei count, GLenum type, const void* indices, GLsizei instancecount);
extern void emscripten_glDrawElementsInstancedBaseVertexBaseInstance(GLenum mode, GLsizei count, GLenum type, const void* indices, GLsizei instancecount, GLint basevertex, GLuint baseinstance);
extern void emscripten_glDrawRangeElements(GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const void* indices);
extern void emscripten_glEnable(GLenum cap);
extern void emscripten_glEnableVertexAttribArray(GLuint index);
extern void emscripten_glEndQuery(GLenum target);
extern GLsync emscripten_glFenceSync(GLenum condition, GLbitfield flags);
extern void emscripten_glFinish(void);
extern void emscripten_glFlush(void);
extern void emscripten_glFramebufferRenderbuffer(GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer);
extern void emscripten_glFramebufferTexture2D(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level);
extern void emscripten_glFrontFace(GLenum mode);
extern void emscripten_glGenBuffers(GLsizei n, GLuint* buffers);
extern void emscripten_glGenFramebuffers(GLsizei n, GLuint* framebuffers);
extern void emscripten_glGenQueries(GLsizei n, GLuint* ids);
extern void emscripten_glGenRenderbuffers(GLsizei n, GLuint* renderbuffers);
extern void emscripten_glGenSamplers(GLsizei n, GLuint* samplers);
extern void emscripten_glGenTextures(GLsizei n, GLuint* textures);
extern void emscripten_glGenVertexArrays(GLsizei n, GLuint* arrays);
extern void emscripten_glGenerateMipmap(GLenum target);
extern void emscripten_glGetBufferParameteriv(GLenum target, GLenum pname, GLint* params);
extern GLenum emscripten_glGetError(void);
extern void emscripten_glGetFloatv(GLenum pname, GLfloat* data);
extern void emscripten_glGetFramebufferAttachmentParameteriv(GLenum target, GLenum attachment, GLenum pname, GLint* params);
extern void emscripten_glGetIntegerv(GLenum pname, GLint* data);
extern void emscripten_glGetProgramInfoLog(GLuint program, GLsizei bufSize, GLsizei* length, GLchar* infoLog);
extern void emscripten_glGetProgramiv(GLuint program, GLenum pname, GLint* params);
extern void emscripten_glGetQueryObjecti64v(GLuint id, GLenum pname, GLint64* params);
extern void emscripten_glGetQueryObjectui64v(GLuint id, GLenum pname, GLuint64* params);
extern void emscripten_glGetQueryObjectuiv(GLuint id, GLenum pname, GLuint* params);
extern void emscripten_glGetQueryiv(GLenum target, GLenum pname, GLint* params);
extern void emscripten_glGetRenderbufferParameteriv(GLenum target, GLenum pname, GLint* params);
extern void emscripten_glGetShaderInfoLog(GLuint shader, GLsizei bufSize, GLsizei* length, GLchar* infoLog);
extern void emscripten_glGetShaderPrecisionFormat(GLenum shadertype, GLenum precisiontype, GLint* range, GLint* precision);
extern void emscripten_glGetShaderiv(GLuint shader, GLenum pname, GLint* params);
extern const GLubyte* emscripten_glGetString(GLenum name);
extern const GLubyte* emscripten_glGetStringi(GLenum name, GLuint index);
extern GLint emscripten_glGetUniformLocation(GLuint program, const GLchar* name);
extern void emscripten_glInvalidateFramebuffer(GLenum target, GLsizei numAttachments, const GLenum* attachments);
extern void emscripten_glInvalidateSubFramebuffer(GLenum target, GLsizei numAttachments, const GLenum* attachments, GLint x, GLint y, GLsizei width, GLsizei height);
extern GLboolean emscripten_glIsSync(GLsync sync);
extern GLboolean emscripten_glIsTexture(GLuint texture);
extern void emscripten_glLineWidth(GLfloat width);
extern void emscripten_glLinkProgram(GLuint program);
extern void emscripten_glMultiDrawArraysInstancedBaseInstance(GLenum mode, const GLint* firsts, const GLsizei* counts, const GLsizei* instanceCounts, const GLuint* baseInstances, GLsizei drawcount);
extern void emscripten_glMultiDrawElementsInstancedBaseVertexBaseInstance(GLenum mode, const GLsizei* counts, GLenum type, const void* const* offsets, const GLsizei* instanceCounts, const GLint* baseVertices, const GLuint* baseInstances, GLsizei drawcount);
extern void emscripten_glPixelStorei(GLenum pname, GLint param);
extern void emscripten_glQueryCounter(GLuint id, GLenum target);
extern void emscripten_glReadBuffer(GLenum src);
extern void emscripten_glReadPixels(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, void* pixels);
extern void emscripten_glRenderbufferStorage(GLenum target, GLenum internalformat, GLsizei width, GLsizei height);
extern void emscripten_glRenderbufferStorageMultisample(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height);
extern void emscripten_glSamplerParameterf(GLuint sampler, GLenum pname, GLfloat param);
extern void emscripten_glSamplerParameteri(GLuint sampler, GLenum pname, GLint param);
extern void emscripten_glSamplerParameteriv(GLuint sampler, GLenum pname, const GLint* param);
extern void emscripten_glScissor(GLint x, GLint y, GLsizei width, GLsizei height);
extern void emscripten_glShaderSource(GLuint shader, GLsizei count, const GLchar* const* string, const GLint* length);
extern void emscripten_glStencilFunc(GLenum func, GLint ref, GLuint mask);
extern void emscripten_glStencilFuncSeparate(GLenum face, GLenum func, GLint ref, GLuint mask);
extern void emscripten_glStencilMask(GLuint mask);
extern void emscripten_glStencilMaskSeparate(GLenum face, GLuint mask);
extern void emscripten_glStencilOp(GLenum fail, GLenum zfail, GLenum zpass);
extern void emscripten_glStencilOpSeparate(GLenum face, GLenum sfail, GLenum dpfail, GLenum dppass);
extern void emscripten_glTexImage2D(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const void* pixels);
extern void emscripten_glTexParameterf(GLenum target, GLenum pname, GLfloat param);
extern void emscripten_glTexParameterfv(GLenum target, GLenum pname, const GLfloat* params);
extern void emscripten_glTexParameteri(GLenum target, GLenum pname, GLint param);
extern void emscripten_glTexParameteriv(GLenum target, GLenum pname, const GLint* params);
extern void emscripten_glTexStorage2D(GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height);
extern void emscripten_glTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const void* pixels);
extern void emscripten_glUniform1f(GLint location, GLfloat v0);
extern void emscripten_glUniform1fv(GLint location, GLsizei count, const GLfloat* value);
extern void emscripten_glUniform1i(GLint location, GLint v0);
extern void emscripten_glUniform1iv(GLint location, GLsizei count, const GLint* value);
extern void emscripten_glUniform2f(GLint location, GLfloat v0, GLfloat v1);
extern void emscripten_glUniform2fv(GLint location, GLsizei count, const GLfloat* value);
extern void emscripten_glUniform2i(GLint location, GLint v0, GLint v1);
extern void emscripten_glUniform2iv(GLint location, GLsizei count, const GLint* value);
extern void emscripten_glUniform3f(GLint location, GLfloat v0, GLfloat v1, GLfloat v2);
extern void emscripten_glUniform3fv(GLint location, GLsizei count, const GLfloat* value);
extern void emscripten_glUniform3i(GLint location, GLint v0, GLint v1, GLint v2);
extern void emscripten_glUniform3iv(GLint location, GLsizei count, const GLint* value);
extern void emscripten_glUniform4f(GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3);
extern void emscripten_glUniform4fv(GLint location, GLsizei count, const GLfloat* value);
extern void emscripten_glUniform4i(GLint location, GLint v0, GLint v1, GLint v2, GLint v3);
extern void emscripten_glUniform4iv(GLint location, GLsizei count, const GLint* value);
extern void emscripten_glUniformMatrix2fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
extern void emscripten_glUniformMatrix3fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
extern void emscripten_glUniformMatrix4fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
extern void emscripten_glUseProgram(GLuint program);
extern void emscripten_glVertexAttrib1f(GLuint index, GLfloat x);
extern void emscripten_glVertexAttrib2fv(GLuint index, const GLfloat* v);
extern void emscripten_glVertexAttrib3fv(GLuint index, const GLfloat* v);
extern void emscripten_glVertexAttrib4fv(GLuint index, const GLfloat* v);
extern void emscripten_glVertexAttribDivisor(GLuint index, GLuint divisor);
extern void emscripten_glVertexAttribIPointer(GLuint index, GLint size, GLenum type, GLsizei stride, const void* pointer);
extern void emscripten_glVertexAttribPointer(GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const void* pointer);
extern void emscripten_glViewport(GLint x, GLint y, GLsizei width, GLsizei height);
extern void emscripten_glWaitSync(GLsync sync, GLbitfield flags, GLuint64 timeout);
