// Auto-generated GL shim: emscripten_gl* -> skia_gpu_gl_* (WIT imports)
// Generated by generate-gl-shim.py — do not edit

#include "emscripten_gl_shim.h"
#include "../bindings/generated/skia_gl.h"

void emscripten_glActiveTexture(GLenum texture) { skia_gpu_gl_active_texture((texture)); }
void emscripten_glAttachShader(GLuint program, GLuint shader) { skia_gpu_gl_attach_shader((program), (shader)); }
void emscripten_glBeginQuery(GLenum target, GLuint id) { skia_gpu_gl_begin_query((target), (id)); }
void emscripten_glBindAttribLocation(GLuint program, GLuint index, const GLchar* name) { skia_gpu_gl_bind_attrib_location((program), (index), (name)); }
void emscripten_glBindBuffer(GLenum target, GLuint buffer) { skia_gpu_gl_bind_buffer((target), (buffer)); }
void emscripten_glBindFramebuffer(GLenum target, GLuint framebuffer) { skia_gpu_gl_bind_framebuffer((target), (framebuffer)); }
void emscripten_glBindRenderbuffer(GLenum target, GLuint renderbuffer) { skia_gpu_gl_bind_renderbuffer((target), (renderbuffer)); }
void emscripten_glBindSampler(GLuint unit, GLuint sampler) { skia_gpu_gl_bind_sampler((unit), (sampler)); }
void emscripten_glBindTexture(GLenum target, GLuint texture) { skia_gpu_gl_bind_texture((target), (texture)); }
void emscripten_glBindVertexArray(GLuint array) { skia_gpu_gl_bind_vertex_array((array)); }
void emscripten_glBlendColor(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha) { skia_gpu_gl_blend_color((red), (green), (blue), (alpha)); }
void emscripten_glBlendEquation(GLenum mode) { skia_gpu_gl_blend_equation((mode)); }
void emscripten_glBlendFunc(GLenum sfactor, GLenum dfactor) { skia_gpu_gl_blend_func((sfactor), (dfactor)); }
void emscripten_glBlitFramebuffer(GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter) { skia_gpu_gl_blit_framebuffer((srcX0), (srcY0), (srcX1), (srcY1), (dstX0), (dstY0), (dstX1), (dstY1), (mask), (filter)); }
void emscripten_glBufferData(GLenum target, GLsizeiptr size, const void* data, GLenum usage) { skia_gpu_gl_buffer_data((target), (size), (data), (usage)); }
void emscripten_glBufferSubData(GLenum target, GLintptr offset, GLsizeiptr size, const void* data) { skia_gpu_gl_buffer_sub_data((target), (offset), (size), (data)); }
GLenum emscripten_glCheckFramebufferStatus(GLenum target) { return (GLenum)skia_gpu_gl_check_framebuffer_status((target)); }
void emscripten_glClear(GLbitfield mask) { skia_gpu_gl_clear((mask)); }
void emscripten_glClearColor(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha) { skia_gpu_gl_clear_color((red), (green), (blue), (alpha)); }
void emscripten_glClearStencil(GLint s) { skia_gpu_gl_clear_stencil((s)); }
GLenum emscripten_glClientWaitSync(GLsync sync, GLbitfield flags, GLuint64 timeout) { return (GLenum)skia_gpu_gl_client_wait_sync((sync), (flags), (timeout)); }
void emscripten_glColorMask(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha) { skia_gpu_gl_color_mask((red), (green), (blue), (alpha)); }
void emscripten_glCompileShader(GLuint shader) { skia_gpu_gl_compile_shader((shader)); }
void emscripten_glCompressedTexImage2D(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const void* data) { skia_gpu_gl_compressed_tex_image2_d((target), (level), (internalformat), (width), (height), (border), (imageSize), (data)); }
void emscripten_glCompressedTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const void* data) { skia_gpu_gl_compressed_tex_sub_image2_d((target), (level), (xoffset), (yoffset), (width), (height), (format), (imageSize), (data)); }
void emscripten_glCopyBufferSubData(GLenum readTarget, GLenum writeTarget, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size) { skia_gpu_gl_copy_buffer_sub_data((readTarget), (writeTarget), (readOffset), (writeOffset), (size)); }
void emscripten_glCopyTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height) { skia_gpu_gl_copy_tex_sub_image2_d((target), (level), (xoffset), (yoffset), (x), (y), (width), (height)); }
GLuint emscripten_glCreateProgram(void) { return (GLuint)skia_gpu_gl_create_program(); }
GLuint emscripten_glCreateShader(GLenum type) { return (GLuint)skia_gpu_gl_create_shader((type)); }
void emscripten_glCullFace(GLenum mode) { skia_gpu_gl_cull_face((mode)); }
void emscripten_glDeleteBuffers(GLsizei n, const GLuint* buffers) { skia_gpu_gl_delete_buffers((n), (buffers)); }
void emscripten_glDeleteFramebuffers(GLsizei n, const GLuint* framebuffers) { skia_gpu_gl_delete_framebuffers((n), (framebuffers)); }
void emscripten_glDeleteProgram(GLuint program) { skia_gpu_gl_delete_program((program)); }
void emscripten_glDeleteQueries(GLsizei n, const GLuint* ids) { skia_gpu_gl_delete_queries((n), (ids)); }
void emscripten_glDeleteRenderbuffers(GLsizei n, const GLuint* renderbuffers) { skia_gpu_gl_delete_renderbuffers((n), (renderbuffers)); }
void emscripten_glDeleteSamplers(GLsizei n, const GLuint* samplers) { skia_gpu_gl_delete_samplers((n), (samplers)); }
void emscripten_glDeleteShader(GLuint shader) { skia_gpu_gl_delete_shader((shader)); }
void emscripten_glDeleteSync(GLsync sync) { skia_gpu_gl_delete_sync((sync)); }
void emscripten_glDeleteTextures(GLsizei n, const GLuint* textures) { skia_gpu_gl_delete_textures((n), (textures)); }
void emscripten_glDeleteVertexArrays(GLsizei n, const GLuint* arrays) { skia_gpu_gl_delete_vertex_arrays((n), (arrays)); }
void emscripten_glDepthMask(GLboolean flag) { skia_gpu_gl_depth_mask((flag)); }
void emscripten_glDisable(GLenum cap) { skia_gpu_gl_disable((cap)); }
void emscripten_glDisableVertexAttribArray(GLuint index) { skia_gpu_gl_disable_vertex_attrib_array((index)); }
void emscripten_glDrawArrays(GLenum mode, GLint first, GLsizei count) { skia_gpu_gl_draw_arrays((mode), (first), (count)); }
void emscripten_glDrawArraysInstanced(GLenum mode, GLint first, GLsizei count, GLsizei instancecount) { skia_gpu_gl_draw_arrays_instanced((mode), (first), (count), (instancecount)); }
void emscripten_glDrawArraysInstancedBaseInstance(GLenum mode, GLint first, GLsizei count, GLsizei instancecount, GLuint baseinstance) { skia_gpu_gl_draw_arrays_instanced_base_instance((mode), (first), (count), (instancecount), (baseinstance)); }
void emscripten_glDrawBuffers(GLsizei n, const GLenum* bufs) { skia_gpu_gl_draw_buffers((n), (bufs)); }
void emscripten_glDrawElements(GLenum mode, GLsizei count, GLenum type, const void* indices) { skia_gpu_gl_draw_elements((mode), (count), (type), (indices)); }
void emscripten_glDrawElementsInstanced(GLenum mode, GLsizei count, GLenum type, const void* indices, GLsizei instancecount) { skia_gpu_gl_draw_elements_instanced((mode), (count), (type), (indices), (instancecount)); }
void emscripten_glDrawElementsInstancedBaseVertexBaseInstance(GLenum mode, GLsizei count, GLenum type, const void* indices, GLsizei instancecount, GLint basevertex, GLuint baseinstance) { skia_gpu_gl_draw_elements_instanced_base_vertex_base_instance((mode), (count), (type), (indices), (instancecount), (basevertex), (baseinstance)); }
void emscripten_glDrawRangeElements(GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const void* indices) { skia_gpu_gl_draw_range_elements((mode), (start), (end), (count), (type), (indices)); }
void emscripten_glEnable(GLenum cap) { skia_gpu_gl_enable((cap)); }
void emscripten_glEnableVertexAttribArray(GLuint index) { skia_gpu_gl_enable_vertex_attrib_array((index)); }
void emscripten_glEndQuery(GLenum target) { skia_gpu_gl_end_query((target)); }
GLsync emscripten_glFenceSync(GLenum condition, GLbitfield flags) { return (GLsync)skia_gpu_gl_fence_sync((condition), (flags)); }
void emscripten_glFinish(void) { skia_gpu_gl_finish(); }
void emscripten_glFlush(void) { skia_gpu_gl_flush(); }
void emscripten_glFramebufferRenderbuffer(GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer) { skia_gpu_gl_framebuffer_renderbuffer((target), (attachment), (renderbuffertarget), (renderbuffer)); }
void emscripten_glFramebufferTexture2D(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level) { skia_gpu_gl_framebuffer_texture2_d((target), (attachment), (textarget), (texture), (level)); }
void emscripten_glFrontFace(GLenum mode) { skia_gpu_gl_front_face((mode)); }
void emscripten_glGenBuffers(GLsizei n, GLuint* buffers) { skia_gpu_gl_gen_buffers((n), (buffers)); }
void emscripten_glGenFramebuffers(GLsizei n, GLuint* framebuffers) { skia_gpu_gl_gen_framebuffers((n), (framebuffers)); }
void emscripten_glGenQueries(GLsizei n, GLuint* ids) { skia_gpu_gl_gen_queries((n), (ids)); }
void emscripten_glGenRenderbuffers(GLsizei n, GLuint* renderbuffers) { skia_gpu_gl_gen_renderbuffers((n), (renderbuffers)); }
void emscripten_glGenSamplers(GLsizei n, GLuint* samplers) { skia_gpu_gl_gen_samplers((n), (samplers)); }
void emscripten_glGenTextures(GLsizei n, GLuint* textures) { skia_gpu_gl_gen_textures((n), (textures)); }
void emscripten_glGenVertexArrays(GLsizei n, GLuint* arrays) { skia_gpu_gl_gen_vertex_arrays((n), (arrays)); }
void emscripten_glGenerateMipmap(GLenum target) { skia_gpu_gl_generate_mipmap((target)); }
void emscripten_glGetBufferParameteriv(GLenum target, GLenum pname, GLint* params) { skia_gpu_gl_get_buffer_parameteriv((target), (pname), (params)); }
GLenum emscripten_glGetError(void) { return (GLenum)skia_gpu_gl_get_error(); }
void emscripten_glGetFloatv(GLenum pname, GLfloat* data) { skia_gpu_gl_get_floatv((pname), (data)); }
void emscripten_glGetFramebufferAttachmentParameteriv(GLenum target, GLenum attachment, GLenum pname, GLint* params) { skia_gpu_gl_get_framebuffer_attachment_parameteriv((target), (attachment), (pname), (params)); }
void emscripten_glGetIntegerv(GLenum pname, GLint* data) { skia_gpu_gl_get_integerv((pname), (data)); }
void emscripten_glGetProgramInfoLog(GLuint program, GLsizei bufSize, GLsizei* length, GLchar* infoLog) { skia_gpu_gl_get_program_info_log((program), (bufSize), (length), (infoLog)); }
void emscripten_glGetProgramiv(GLuint program, GLenum pname, GLint* params) { skia_gpu_gl_get_programiv((program), (pname), (params)); }
void emscripten_glGetQueryObjecti64v(GLuint id, GLenum pname, GLint64* params) { skia_gpu_gl_get_query_objecti64v((id), (pname), (params)); }
void emscripten_glGetQueryObjectui64v(GLuint id, GLenum pname, GLuint64* params) { skia_gpu_gl_get_query_objectui64v((id), (pname), (params)); }
void emscripten_glGetQueryObjectuiv(GLuint id, GLenum pname, GLuint* params) { skia_gpu_gl_get_query_objectuiv((id), (pname), (params)); }
void emscripten_glGetQueryiv(GLenum target, GLenum pname, GLint* params) { skia_gpu_gl_get_queryiv((target), (pname), (params)); }
void emscripten_glGetRenderbufferParameteriv(GLenum target, GLenum pname, GLint* params) { skia_gpu_gl_get_renderbuffer_parameteriv((target), (pname), (params)); }
void emscripten_glGetShaderInfoLog(GLuint shader, GLsizei bufSize, GLsizei* length, GLchar* infoLog) { skia_gpu_gl_get_shader_info_log((shader), (bufSize), (length), (infoLog)); }
void emscripten_glGetShaderPrecisionFormat(GLenum shadertype, GLenum precisiontype, GLint* range, GLint* precision) { skia_gpu_gl_get_shader_precision_format((shadertype), (precisiontype), (range), (precision)); }
void emscripten_glGetShaderiv(GLuint shader, GLenum pname, GLint* params) { skia_gpu_gl_get_shaderiv((shader), (pname), (params)); }
const GLubyte* emscripten_glGetString(GLenum name) { return (const GLubyte*)skia_gpu_gl_get_string((name)); }
const GLubyte* emscripten_glGetStringi(GLenum name, GLuint index) { return (const GLubyte*)skia_gpu_gl_get_stringi((name), (index)); }
GLint emscripten_glGetUniformLocation(GLuint program, const GLchar* name) { return (GLint)skia_gpu_gl_get_uniform_location((program), (name)); }
void emscripten_glInvalidateFramebuffer(GLenum target, GLsizei numAttachments, const GLenum* attachments) { skia_gpu_gl_invalidate_framebuffer((target), (numAttachments), (attachments)); }
void emscripten_glInvalidateSubFramebuffer(GLenum target, GLsizei numAttachments, const GLenum* attachments, GLint x, GLint y, GLsizei width, GLsizei height) { skia_gpu_gl_invalidate_sub_framebuffer((target), (numAttachments), (attachments), (x), (y), (width), (height)); }
GLboolean emscripten_glIsSync(GLsync sync) { return (GLboolean)skia_gpu_gl_is_sync((sync)); }
GLboolean emscripten_glIsTexture(GLuint texture) { return (GLboolean)skia_gpu_gl_is_texture((texture)); }
void emscripten_glLineWidth(GLfloat width) { skia_gpu_gl_line_width((width)); }
void emscripten_glLinkProgram(GLuint program) { skia_gpu_gl_link_program((program)); }
void emscripten_glMultiDrawArraysInstancedBaseInstance(GLenum mode, const GLint* firsts, const GLsizei* counts, const GLsizei* instanceCounts, const GLuint* baseInstances, GLsizei drawcount) { skia_gpu_gl_multi_draw_arrays_instanced_base_instance((mode), (firsts), (counts), (instanceCounts), (baseInstances), (drawcount)); }
void emscripten_glMultiDrawElementsInstancedBaseVertexBaseInstance(GLenum mode, const GLsizei* counts, GLenum type, const void* const* offsets, const GLsizei* instanceCounts, const GLint* baseVertices, const GLuint* baseInstances, GLsizei drawcount) { skia_gpu_gl_multi_draw_elements_instanced_base_vertex_base_instance((mode), (counts), (type), (offsets), (instanceCounts), (baseVertices), (baseInstances), (drawcount)); }
void emscripten_glPixelStorei(GLenum pname, GLint param) { skia_gpu_gl_pixel_storei((pname), (param)); }
void emscripten_glQueryCounter(GLuint id, GLenum target) { skia_gpu_gl_query_counter((id), (target)); }
void emscripten_glReadBuffer(GLenum src) { skia_gpu_gl_read_buffer((src)); }
void emscripten_glReadPixels(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, void* pixels) { skia_gpu_gl_read_pixels((x), (y), (width), (height), (format), (type), (pixels)); }
void emscripten_glRenderbufferStorage(GLenum target, GLenum internalformat, GLsizei width, GLsizei height) { skia_gpu_gl_renderbuffer_storage((target), (internalformat), (width), (height)); }
void emscripten_glRenderbufferStorageMultisample(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height) { skia_gpu_gl_renderbuffer_storage_multisample((target), (samples), (internalformat), (width), (height)); }
void emscripten_glSamplerParameterf(GLuint sampler, GLenum pname, GLfloat param) { skia_gpu_gl_sampler_parameterf((sampler), (pname), (param)); }
void emscripten_glSamplerParameteri(GLuint sampler, GLenum pname, GLint param) { skia_gpu_gl_sampler_parameteri((sampler), (pname), (param)); }
void emscripten_glSamplerParameteriv(GLuint sampler, GLenum pname, const GLint* param) { skia_gpu_gl_sampler_parameteriv((sampler), (pname), (param)); }
void emscripten_glScissor(GLint x, GLint y, GLsizei width, GLsizei height) { skia_gpu_gl_scissor((x), (y), (width), (height)); }
void emscripten_glShaderSource(GLuint shader, GLsizei count, const GLchar* const* string, const GLint* length) { skia_gpu_gl_shader_source((shader), (count), (string), (length)); }
void emscripten_glStencilFunc(GLenum func, GLint ref, GLuint mask) { skia_gpu_gl_stencil_func((func), (ref), (mask)); }
void emscripten_glStencilFuncSeparate(GLenum face, GLenum func, GLint ref, GLuint mask) { skia_gpu_gl_stencil_func_separate((face), (func), (ref), (mask)); }
void emscripten_glStencilMask(GLuint mask) { skia_gpu_gl_stencil_mask((mask)); }
void emscripten_glStencilMaskSeparate(GLenum face, GLuint mask) { skia_gpu_gl_stencil_mask_separate((face), (mask)); }
void emscripten_glStencilOp(GLenum fail, GLenum zfail, GLenum zpass) { skia_gpu_gl_stencil_op((fail), (zfail), (zpass)); }
void emscripten_glStencilOpSeparate(GLenum face, GLenum sfail, GLenum dpfail, GLenum dppass) { skia_gpu_gl_stencil_op_separate((face), (sfail), (dpfail), (dppass)); }
void emscripten_glTexImage2D(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const void* pixels) { skia_gpu_gl_tex_image2_d((target), (level), (internalformat), (width), (height), (border), (format), (type), (pixels)); }
void emscripten_glTexParameterf(GLenum target, GLenum pname, GLfloat param) { skia_gpu_gl_tex_parameterf((target), (pname), (param)); }
void emscripten_glTexParameterfv(GLenum target, GLenum pname, const GLfloat* params) { skia_gpu_gl_tex_parameterfv((target), (pname), (params)); }
void emscripten_glTexParameteri(GLenum target, GLenum pname, GLint param) { skia_gpu_gl_tex_parameteri((target), (pname), (param)); }
void emscripten_glTexParameteriv(GLenum target, GLenum pname, const GLint* params) { skia_gpu_gl_tex_parameteriv((target), (pname), (params)); }
void emscripten_glTexStorage2D(GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height) { skia_gpu_gl_tex_storage2_d((target), (levels), (internalformat), (width), (height)); }
void emscripten_glTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const void* pixels) { skia_gpu_gl_tex_sub_image2_d((target), (level), (xoffset), (yoffset), (width), (height), (format), (type), (pixels)); }
void emscripten_glUniform1f(GLint location, GLfloat v0) { skia_gpu_gl_uniform1f((location), (v0)); }
void emscripten_glUniform1fv(GLint location, GLsizei count, const GLfloat* value) { skia_gpu_gl_uniform1fv((location), (count), (value)); }
void emscripten_glUniform1i(GLint location, GLint v0) { skia_gpu_gl_uniform1i((location), (v0)); }
void emscripten_glUniform1iv(GLint location, GLsizei count, const GLint* value) { skia_gpu_gl_uniform1iv((location), (count), (value)); }
void emscripten_glUniform2f(GLint location, GLfloat v0, GLfloat v1) { skia_gpu_gl_uniform2f((location), (v0), (v1)); }
void emscripten_glUniform2fv(GLint location, GLsizei count, const GLfloat* value) { skia_gpu_gl_uniform2fv((location), (count), (value)); }
void emscripten_glUniform2i(GLint location, GLint v0, GLint v1) { skia_gpu_gl_uniform2i((location), (v0), (v1)); }
void emscripten_glUniform2iv(GLint location, GLsizei count, const GLint* value) { skia_gpu_gl_uniform2iv((location), (count), (value)); }
void emscripten_glUniform3f(GLint location, GLfloat v0, GLfloat v1, GLfloat v2) { skia_gpu_gl_uniform3f((location), (v0), (v1), (v2)); }
void emscripten_glUniform3fv(GLint location, GLsizei count, const GLfloat* value) { skia_gpu_gl_uniform3fv((location), (count), (value)); }
void emscripten_glUniform3i(GLint location, GLint v0, GLint v1, GLint v2) { skia_gpu_gl_uniform3i((location), (v0), (v1), (v2)); }
void emscripten_glUniform3iv(GLint location, GLsizei count, const GLint* value) { skia_gpu_gl_uniform3iv((location), (count), (value)); }
void emscripten_glUniform4f(GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3) { skia_gpu_gl_uniform4f((location), (v0), (v1), (v2), (v3)); }
void emscripten_glUniform4fv(GLint location, GLsizei count, const GLfloat* value) { skia_gpu_gl_uniform4fv((location), (count), (value)); }
void emscripten_glUniform4i(GLint location, GLint v0, GLint v1, GLint v2, GLint v3) { skia_gpu_gl_uniform4i((location), (v0), (v1), (v2), (v3)); }
void emscripten_glUniform4iv(GLint location, GLsizei count, const GLint* value) { skia_gpu_gl_uniform4iv((location), (count), (value)); }
void emscripten_glUniformMatrix2fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat* value) { skia_gpu_gl_uniform_matrix2fv((location), (count), (transpose), (value)); }
void emscripten_glUniformMatrix3fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat* value) { skia_gpu_gl_uniform_matrix3fv((location), (count), (transpose), (value)); }
void emscripten_glUniformMatrix4fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat* value) { skia_gpu_gl_uniform_matrix4fv((location), (count), (transpose), (value)); }
void emscripten_glUseProgram(GLuint program) { skia_gpu_gl_use_program((program)); }
void emscripten_glVertexAttrib1f(GLuint index, GLfloat x) { skia_gpu_gl_vertex_attrib1f((index), (x)); }
void emscripten_glVertexAttrib2fv(GLuint index, const GLfloat* v) { skia_gpu_gl_vertex_attrib2fv((index), (v)); }
void emscripten_glVertexAttrib3fv(GLuint index, const GLfloat* v) { skia_gpu_gl_vertex_attrib3fv((index), (v)); }
void emscripten_glVertexAttrib4fv(GLuint index, const GLfloat* v) { skia_gpu_gl_vertex_attrib4fv((index), (v)); }
void emscripten_glVertexAttribDivisor(GLuint index, GLuint divisor) { skia_gpu_gl_vertex_attrib_divisor((index), (divisor)); }
void emscripten_glVertexAttribIPointer(GLuint index, GLint size, GLenum type, GLsizei stride, const void* pointer) { skia_gpu_gl_vertex_attrib_i_pointer((index), (size), (type), (stride), (pointer)); }
void emscripten_glVertexAttribPointer(GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const void* pointer) { skia_gpu_gl_vertex_attrib_pointer((index), (size), (type), (normalized), (stride), (pointer)); }
void emscripten_glViewport(GLint x, GLint y, GLsizei width, GLsizei height) { skia_gpu_gl_viewport((x), (y), (width), (height)); }
void emscripten_glWaitSync(GLsync sync, GLbitfield flags, GLuint64 timeout) { skia_gpu_gl_wait_sync((sync), (flags), (timeout)); }
