/**
 * Keeps react subpath wrapper directories in sync with core categories
 * across all packages that follow the subpath export pattern.
 *
 * For each package (three-flatland, presets), the script:
 * 1. Reads `src/index.ts` for `export * from './{category}'` lines
 * 2. Checks each category is a directory with an `index.ts`
 * 3. Generates `src/react/{category}/index.ts` wrappers that:
 *    - Import `../types` (side-effect for ThreeElements augmentation)
 *    - Re-export the core category: `export * from '../../{category}'`
 * 4. Deletes stale wrappers for removed categories
 *
 * The `src/react/types.ts` file in each package is hand-authored by the
 * implementor — this script does NOT generate type augmentation.
 *
 * Usage:
 *   tsx scripts/sync-react-subpaths.ts           # Generate/delete + git add
 *   tsx scripts/sync-react-subpaths.ts --verify  # CI check, exit 1 if out of sync
 */

import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync, rmSync } from 'node:fs'
import { execSync } from 'node:child_process'
import { join, resolve } from 'node:path'

const ROOT = resolve(import.meta.dirname, '..')

const GENERATED_HEADER = '// Generated by sync-react-subpaths.ts — do not edit'

const WRAPPER_TEMPLATE = (name: string) =>
  `${GENERATED_HEADER}\nimport '../types'\nexport * from '../../${name}'\n`

// Match the exact generated pattern
const GENERATED_RE = /^\/\/ Generated by sync-react-subpaths\.ts/

interface SyncResult {
  created: string[]
  deleted: string[]
  missing: string[]
  stale: string[]
  migrate: string[]
}

/**
 * Get expected categories from a package's src/index.ts.
 * Looks for `export * from './{name}'` where {name} is a directory with an index.ts.
 */
function getExpectedCategories(pkgSrc: string): string[] {
  const indexPath = join(pkgSrc, 'index.ts')
  if (!existsSync(indexPath)) return []

  const content = readFileSync(indexPath, 'utf-8')
  const categories: string[] = []

  for (const line of content.split('\n')) {
    const match = line.match(/^export \* from '\.\/([^']+)'$/)
    if (!match) continue

    const name = match[1]
    if (name === 'react') continue

    // Only include directories with an index.ts (skip standalone files like Flatland.ts)
    const indexFile = join(pkgSrc, name, 'index.ts')
    if (existsSync(indexFile)) {
      categories.push(name)
    }
  }

  return categories
}

/**
 * Get existing generated directory wrappers in the react/ directory.
 */
function getExistingGenerated(reactDir: string): Map<string, string> {
  const generated = new Map<string, string>()
  if (!existsSync(reactDir)) return generated

  for (const entry of readdirSync(reactDir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue

    const indexPath = join(reactDir, entry.name, 'index.ts')
    if (!existsSync(indexPath)) continue

    const content = readFileSync(indexPath, 'utf-8')
    if (GENERATED_RE.test(content)) {
      generated.set(entry.name, indexPath)
    }
  }

  return generated
}

/**
 * Detect old-style flat file wrappers for migration.
 */
function getOldStyleGenerated(reactDir: string): Map<string, string> {
  const OLD_RE = /^import '\.\/types'\nexport \* from '\.\.\/([^']+)'\n$/
  const generated = new Map<string, string>()
  if (!existsSync(reactDir)) return generated

  for (const entry of readdirSync(reactDir)) {
    if (!entry.endsWith('.ts') || entry.endsWith('.test.ts')) continue

    const filePath = join(reactDir, entry)
    const content = readFileSync(filePath, 'utf-8')
    if (OLD_RE.test(content)) {
      const name = entry.replace(/\.ts$/, '')
      generated.set(name, filePath)
    }
  }

  return generated
}

/**
 * Sync react subpath wrappers for a single package.
 */
function syncPackage(label: string, pkgSrc: string, verify: boolean): SyncResult {
  const reactDir = join(pkgSrc, 'react')
  const expected = new Set(getExpectedCategories(pkgSrc))
  const existing = getExistingGenerated(reactDir)
  const oldStyle = getOldStyleGenerated(reactDir)

  const missing: string[] = []
  const stale: string[] = []
  const migrate: string[] = []

  // Find missing wrappers
  for (const name of expected) {
    if (!existing.has(name)) {
      if (oldStyle.has(name)) {
        migrate.push(name)
      } else {
        missing.push(name)
      }
    }
  }

  // Find stale wrappers (generated dirs whose category no longer exists)
  for (const [name] of existing) {
    if (!expected.has(name)) {
      stale.push(name)
    }
  }

  // Old-style files that don't correspond to expected categories are also stale
  for (const [name] of oldStyle) {
    if (!expected.has(name)) {
      stale.push(name)
    }
  }

  if (verify && (missing.length > 0 || stale.length > 0 || migrate.length > 0)) {
    console.error(`${label}: React subpath wrappers are out of sync!\n`)

    for (const name of missing) {
      console.error(`  Missing: src/react/${name}/index.ts`)
    }
    for (const name of migrate) {
      console.error(`  Migrate: src/react/${name}.ts → src/react/${name}/index.ts`)
    }
    for (const name of stale) {
      console.error(`  Stale:   src/react/${name}`)
    }

    return { created: [], deleted: [], missing, stale, migrate }
  }

  const createdPaths: string[] = []
  const deletedPaths: string[] = []

  // Migrate old-style flat files → directories
  for (const name of migrate) {
    const oldPath = oldStyle.get(name)!
    rmSync(oldPath)
    deletedPaths.push(oldPath)

    const dirPath = join(reactDir, name)
    mkdirSync(dirPath, { recursive: true })
    const indexPath = join(dirPath, 'index.ts')
    writeFileSync(indexPath, WRAPPER_TEMPLATE(name))
    createdPaths.push(indexPath)
    console.log(`  ${label}: Migrated src/react/${name}.ts → src/react/${name}/index.ts`)
  }

  // Generate missing wrappers
  for (const name of missing) {
    const dirPath = join(reactDir, name)
    mkdirSync(dirPath, { recursive: true })
    const indexPath = join(dirPath, 'index.ts')
    writeFileSync(indexPath, WRAPPER_TEMPLATE(name))
    createdPaths.push(indexPath)
    console.log(`  ${label}: Created src/react/${name}/index.ts`)
  }

  // Delete stale wrappers
  for (const name of stale) {
    // Could be an old flat file or a directory
    const oldPath = oldStyle.get(name)
    if (oldPath) {
      rmSync(oldPath)
      deletedPaths.push(oldPath)
      console.log(`  ${label}: Deleted src/react/${name}.ts`)
    }

    const dirPath = join(reactDir, name)
    if (existsSync(dirPath)) {
      rmSync(dirPath, { recursive: true })
      deletedPaths.push(join(dirPath, 'index.ts'))
      console.log(`  ${label}: Deleted src/react/${name}/`)
    }
  }

  return { created: createdPaths, deleted: deletedPaths, missing, stale, migrate }
}

// ============================================
// Main
// ============================================

const verify = process.argv.includes('--verify')

const packages = [
  { label: 'core', src: join(ROOT, 'packages', 'three-flatland', 'src') },
  { label: 'presets', src: join(ROOT, 'packages', 'presets', 'src') },
]

const toRelative = (p: string) => p.replace(ROOT + '/', '')
let hasErrors = false
let totalChanges = 0

for (const pkg of packages) {
  const result = syncPackage(pkg.label, pkg.src, verify)

  if (verify && (result.missing.length > 0 || result.stale.length > 0 || result.migrate.length > 0)) {
    hasErrors = true
    continue
  }

  // Stage changes
  if (result.created.length > 0) {
    execSync(`git add ${result.created.map(toRelative).join(' ')}`, { cwd: ROOT })
  }

  if (result.deleted.length > 0) {
    const relativePaths = result.deleted.map(toRelative).join(' ')
    execSync(`git rm --cached --ignore-unmatch ${relativePaths}`, { cwd: ROOT, stdio: 'pipe' })
  }

  totalChanges += result.created.length + result.deleted.length
}

if (hasErrors) {
  console.error(
    `\nRun 'pnpm sync:react' locally or install git hooks with 'pnpm prepare'.`,
  )
  process.exit(1)
}

if (totalChanges > 0) {
  console.log(`\nSynced ${totalChanges} react subpath wrapper(s).`)
}

if (verify && !hasErrors) {
  console.log('React subpath wrappers are in sync.')
}
