/**
 * Keeps react subpath wrapper directories in sync with core categories.
 *
 * Each public category (e.g., sprites, animation) gets a thin wrapper at
 * `src/react/{name}/index.ts` that imports the ThreeElements type augmentation
 * and re-exports the core category. This mirrors the core src/ directory
 * structure and enables tree-shakeable imports like `three-flatland/react/sprites`.
 *
 * Usage:
 *   tsx scripts/sync-react-subpaths.ts           # Generate/delete + git add
 *   tsx scripts/sync-react-subpaths.ts --verify  # CI check, exit 1 if out of sync
 */

import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync, rmSync } from 'node:fs'
import { execSync } from 'node:child_process'
import { join, resolve } from 'node:path'

const ROOT = resolve(import.meta.dirname, '..')
const PKG_SRC = join(ROOT, 'packages', 'three-flatland', 'src')
const REACT_DIR = join(PKG_SRC, 'react')

const GENERATED_HEADER = '// Generated by sync-react-subpaths.ts — do not edit'

const WRAPPER_TEMPLATE = (name: string) =>
  `${GENERATED_HEADER}\nimport '../types'\nexport * from '../../${name}'\n`

// Match the exact generated pattern
const GENERATED_RE = /^\/\/ Generated by sync-react-subpaths\.ts/

function getExpectedCategories(): string[] {
  const indexPath = join(PKG_SRC, 'index.ts')
  const content = readFileSync(indexPath, 'utf-8')
  const categories: string[] = []

  for (const line of content.split('\n')) {
    const match = line.match(/^export \* from '\.\/([^']+)'$/)
    if (!match) continue

    const name = match[1]
    if (name === 'react') continue

    // Only include directories with an index.ts (skip standalone files like Flatland.ts)
    const indexFile = join(PKG_SRC, name, 'index.ts')
    if (existsSync(indexFile)) {
      categories.push(name)
    }
  }

  return categories
}

function getExistingGenerated(): Map<string, string> {
  const generated = new Map<string, string>()

  for (const entry of readdirSync(REACT_DIR, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue

    const indexPath = join(REACT_DIR, entry.name, 'index.ts')
    if (!existsSync(indexPath)) continue

    const content = readFileSync(indexPath, 'utf-8')
    if (GENERATED_RE.test(content)) {
      generated.set(entry.name, indexPath)
    }
  }

  return generated
}

// Also detect old-style flat file wrappers for migration
function getOldStyleGenerated(): Map<string, string> {
  const OLD_RE = /^import '\.\/types'\nexport \* from '\.\.\/([^']+)'\n$/
  const generated = new Map<string, string>()

  for (const entry of readdirSync(REACT_DIR)) {
    if (!entry.endsWith('.ts') || entry.endsWith('.test.ts')) continue

    const filePath = join(REACT_DIR, entry)
    const content = readFileSync(filePath, 'utf-8')
    if (OLD_RE.test(content)) {
      const name = entry.replace(/\.ts$/, '')
      generated.set(name, filePath)
    }
  }

  return generated
}

// Main
const verify = process.argv.includes('--verify')

const expected = new Set(getExpectedCategories())
const existing = getExistingGenerated()
const oldStyle = getOldStyleGenerated()

const missing: string[] = []
const stale: string[] = []
const migrate: string[] = []

// Find missing wrappers
for (const name of expected) {
  if (!existing.has(name)) {
    if (oldStyle.has(name)) {
      migrate.push(name)
    } else {
      missing.push(name)
    }
  }
}

// Find stale wrappers (generated dirs whose category no longer exists)
for (const [name] of existing) {
  if (!expected.has(name)) {
    stale.push(name)
  }
}

// Old-style files that don't correspond to expected categories are also stale
for (const [name] of oldStyle) {
  if (!expected.has(name)) {
    stale.push(name)
  }
}

if (missing.length === 0 && stale.length === 0 && migrate.length === 0) {
  if (verify) {
    console.log('React subpath wrappers are in sync.')
  }
  process.exit(0)
}

if (verify) {
  console.error('React subpath wrappers are out of sync!\n')

  for (const name of missing) {
    console.error(`  Missing: src/react/${name}/index.ts`)
  }
  for (const name of migrate) {
    console.error(`  Migrate: src/react/${name}.ts → src/react/${name}/index.ts`)
  }
  for (const name of stale) {
    console.error(`  Stale:   src/react/${name}`)
  }

  console.error(
    `\nRun 'pnpm sync:react' locally or install git hooks with 'pnpm prepare'.`,
  )
  process.exit(1)
}

const createdPaths: string[] = []
const deletedPaths: string[] = []

// Migrate old-style flat files → directories
for (const name of migrate) {
  const oldPath = oldStyle.get(name)!
  rmSync(oldPath)
  deletedPaths.push(oldPath)

  const dirPath = join(REACT_DIR, name)
  mkdirSync(dirPath, { recursive: true })
  const indexPath = join(dirPath, 'index.ts')
  writeFileSync(indexPath, WRAPPER_TEMPLATE(name))
  createdPaths.push(indexPath)
  console.log(`  Migrated: src/react/${name}.ts → src/react/${name}/index.ts`)
}

// Generate missing wrappers
for (const name of missing) {
  const dirPath = join(REACT_DIR, name)
  mkdirSync(dirPath, { recursive: true })
  const indexPath = join(dirPath, 'index.ts')
  writeFileSync(indexPath, WRAPPER_TEMPLATE(name))
  createdPaths.push(indexPath)
  console.log(`  Created: src/react/${name}/index.ts`)
}

// Delete stale wrappers
for (const name of stale) {
  // Could be an old flat file or a directory
  const oldPath = oldStyle.get(name)
  if (oldPath) {
    rmSync(oldPath)
    deletedPaths.push(oldPath)
    console.log(`  Deleted: src/react/${name}.ts`)
  }

  const dirPath = join(REACT_DIR, name)
  if (existsSync(dirPath)) {
    rmSync(dirPath, { recursive: true })
    deletedPaths.push(join(dirPath, 'index.ts'))
    console.log(`  Deleted: src/react/${name}/`)
  }
}

// Stage changes
const toRelative = (p: string) => p.replace(ROOT + '/', '')

if (createdPaths.length > 0) {
  execSync(`git add ${createdPaths.map(toRelative).join(' ')}`, { cwd: ROOT })
}

if (deletedPaths.length > 0) {
  const relativePaths = deletedPaths.map(toRelative).join(' ')
  execSync(`git rm --cached --ignore-unmatch ${relativePaths}`, { cwd: ROOT, stdio: 'pipe' })
}

const total = createdPaths.length + deletedPaths.length
console.log(`\nSynced ${total} react subpath wrapper(s).`)
