import { defineConfig, presetIcons, presetWind4 } from 'unocss'
import { presetStarlightIcons } from 'starlight-plugin-icons/uno'
import { FileSystemIconLoader } from '@iconify/utils/lib/loader/node-loaders'

/**
 * Tokens here are the single source for design-system primitives.
 * They mirror the CSS custom properties in `packages/starlight-theme/styles/theme.css`
 * (base16 Materia) so utility classes (`text-fg`, `bg-bg-2`, `font-prose`, …)
 * resolve to the same values Starlight's overrides consume via `var(--…)`.
 */
export default defineConfig({
  presets: [
    presetStarlightIcons(),
    presetIcons({
      // Force every icon to render via CSS mask + currentColor. Default
      // mode='auto' lets multi-color icons (material-icon-theme brand
      // glyphs, etc.) render in their original palette, which clashes
      // with the gem theme. Mask mode resolves to a single-color
      // silhouette that inherits from the surrounding text color, so
      // brand icons read as monochrome chips and respect dark/light
      // mode, hover gem tints, etc.
      mode: 'mask',
      collections: {
        // Workspace-local custom icon collection. Drop SVGs in `docs/src/icons/tf/`
        // to use them as `<span class="i-tf:name" />` anywhere in the site.
        tf: FileSystemIconLoader('./src/icons/tf'),
      },
      extraProperties: {
        display: 'inline-block',
        'vertical-align': 'middle',
      },
    }),
    presetWind4({
      // Use the renamed cascade layer that `starlight-theme` declares.
      preflights: { reset: false },
    }),
  ],
  theme: {
    colors: {
      // Bearded-theme-inspired technicolor gem palette — names match
      // theme.css custom properties so utilities resolve to the same values
      // Starlight's overrides consume via `var(--…)`. See Design Context
      // (CLAUDE.md) for the gem taxonomy.
      bg: 'var(--background)',
      fg: 'var(--foreground)',
      'bg-1': 'var(--gray-7)',
      'bg-2': 'var(--gray-6)',
      muted: 'var(--muted)',
      'muted-fg': 'var(--muted-foreground)',
      border: 'var(--border)',
      ring: 'var(--ring)',
      primary: 'var(--primary)',
      'primary-fg': 'var(--primary-foreground)',
      accent: 'var(--accent)',
      'accent-fg': 'var(--accent-foreground)',
      link: 'var(--link)',
      'link-hover': 'var(--link-hover)',
      // Gem accents — first-class taxonomy
      gold: 'var(--gold)',
      'gold-soft': 'var(--gold-soft)',
      ruby: 'var(--ruby)',
      'ruby-soft': 'var(--ruby-soft)',
      emerald: 'var(--emerald)',
      'emerald-soft': 'var(--emerald-soft)',
      diamond: 'var(--diamond)',
      'diamond-soft': 'var(--diamond-soft)',
      amethyst: 'var(--amethyst)',
      'amethyst-soft': 'var(--amethyst-soft)',
      pink: 'var(--pink)',
      'pink-soft': 'var(--pink-soft)',
      salmon: 'var(--salmon)',
      'salmon-soft': 'var(--salmon-soft)',
      turquoize: 'var(--turquoize)',
      'turquoize-soft': 'var(--turquoize-soft)',
      // Conventional aliases (alias to the gem closest to each role)
      orange: 'var(--orange)',
      green: 'var(--green)',
      blue: 'var(--blue)',
      purple: 'var(--purple)',
      red: 'var(--red)',
      yellow: 'var(--yellow)',
      teal: 'var(--teal)',
    },
    fontFamily: {
      // Typography stack per Design Context (CLAUDE.md).
      // `display` is reserved for the Silkscreen wordmark only.
      display: ['Silkscreen', 'system-ui', 'sans-serif'],
      sans: ['Public Sans', 'system-ui', 'sans-serif'],
      nav: ['Inter', 'system-ui', 'sans-serif'],
      prose: ['JetBrains Mono', 'ui-monospace', 'SFMono-Regular', 'monospace'],
      mono: ['Commit Mono', 'JetBrains Mono', 'ui-monospace', 'SFMono-Regular', 'monospace'],
    },
  },
  // Safelist gem-prefixed utility classes generated by data-attribute
  // selectors / dynamic component props (e.g., FeatureCard `color="emerald"`
  // produces `bg-emerald-soft`/`text-emerald` strings UnoCSS can't statically
  // extract from a template literal).
  safelist: (() => {
    const gems = [
      'gold', 'ruby', 'emerald', 'diamond', 'amethyst', 'pink', 'salmon', 'turquoize',
    ]
    const out: string[] = []
    for (const g of gems) {
      out.push(`text-${g}`, `bg-${g}`, `bg-${g}-soft`, `border-${g}`, `ring-${g}`)
    }
    return out
  })().concat([
    // FeatureCard / FeatureList content icons
    'i-lucide:lightbulb', 'i-lucide:list', 'i-lucide:user', 'i-lucide:play-circle',
    'i-lucide:sparkles', 'i-lucide:map', 'i-lucide:heart',
    // SoundToggle states
    'i-lucide:volume', 'i-lucide:volume-x', 'i-lucide:volume-1', 'i-lucide:volume-2',
    // ThemeSelect states
    'i-lucide:monitor', 'i-lucide:sun', 'i-lucide:moon',
    // Brand / social
    'i-lucide:github', 'i-lucide:external-link', 'i-lucide:arrow-right', 'i-lucide:arrow-left',
    // Sidebar group icons (also referenced statically in astro.config.mjs)
    'i-lucide:download', 'i-lucide:play', 'i-lucide:rocket', 'i-lucide:palette',
    'i-lucide:terminal', 'i-lucide:image', 'i-lucide:book-open',
    // Package-manager / framework tabs — TabItem `icon=` prop produces
    // dynamic class names UnoCSS can't statically extract (`i-${icon}`).
    // simple-icons gives us proper monochrome brand silhouettes that
    // resolve cleanly through `mode: 'mask'` (material-icon-theme's
    // multi-color glyphs lose detail when masked, especially `bun`).
    'i-simple-icons:npm', 'i-simple-icons:pnpm',
    'i-simple-icons:yarn', 'i-simple-icons:bun',
    'i-simple-icons:react', 'i-simple-icons:threedotjs',
    'i-lucide:sparkles', 'i-lucide:wand-sparkles', 'i-lucide:bot',
  ]),
})
